### ISSUE TITLE
Pagination losses url 

### ISSUE THREAD

**Issue by ChrisSantiago82** [livewire/livewire#1816] opened 2020-10-14 14:32 UTC
I'm using the latest version of Livewire.

If I want use pagination with Livewire\WithPagination and  use WithPagination, and if I visit that site, on the top the url gets replaces with "livewire/message/......". And then when the pagination should do something of course I'm getting a MethodNotAllowedHttpException.

url with pagination enabled:
![image](https://user-images.githubusercontent.com/43000085/96003554-55fb6c80-0e08-11eb-9179-c6891f6e419c.png)

url without pagination (same page):
![image](https://user-images.githubusercontent.com/43000085/96003627-6a3f6980-0e08-11eb-9a57-742cb112759e.png)

Code:
`<?php

namespace App\Http\Livewire\Order;

use Livewire\Component;
use Livewire\WithPagination;
use App\Bearer;

class Insurancemodal extends Component
{

    use WithPagination;

    protected $paginationTheme = 'bootstrap';

    public $search;

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {

        return view('livewire.order.insurancemodal', [
            'bearers' => Bearer::where('company', 'like', '%'.$this->search.'%')->paginate(10),
        ]);

    }
}`

**Comment by ChrisThompsonTLDR** [comment] 2020-10-14 16:43
By chance, you using `wire:click.prevent.prefetch` on pagination/ordering/filtering links?  Or `url()->current()`?

We can replicate this issue with the following:
```
<a href="{{ url()->current() . '?' . http_build_query(['limit' => $limit, 'orderBy' => $name, 'orderDir' => (($orderDir === 'desc') ? 'asc' : 'desc')]) }}" wire:click.prevent.prefetch="order('{{ $name }}', '{{ $orderDir === 'desc' ? 'asc' : 'desc' }}')">
```

If we change to the following we don't experience the issue:
<a href="{{ url()->current() . '?' . http_build_query(['limit' => $limit, 'orderBy' => $name, 'orderDir' => (($orderDir === 'desc') ? 'asc' : 'desc')]) }}" wire:click="order('{{ $name }}', '{{ $orderDir === 'desc' ? 'asc' : 'desc' }}')">
```

**Comment by ChrisThompsonTLDR** [comment] 2020-10-14 16:50
Are you on Laravel 7 and Livewire 2?

**Comment by squishythejellyfish** [comment] 2020-10-29 21:26
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by ChrisSantiago82** [comment] 2020-10-29 22:50
Hey, 
I can't understand this philosophy and I'm feeling that I'm have been silenced. 
Don't get me wrong, I think it's a great project that has grown a lot in a short time. 

I also think I'm a person that can understand a lot.
I could understand if you say you need more information.  I could understand if you say that there is no capacity to resolve it. I could understand if you say that there are not enough people affected by this problem. I could understand if you would ask for money to resolve this issue. I could understand if it's on the lowest priority. 
But just closing it without a comment doesn't give a good feeling. Maybe I also didn't described it well enough and I could accept such an answer as well. 
But with the next issue I could think why bother creating an issue. And maybe other people will think this as well. But I also think the quality of the project has improved alot just of all the issues that have been reported. If people feel like it's not worth it creating issues.. It's a slippery slope.

**Comment by calebporzio** [comment] 2020-11-02 14:09
I declared issue bankruptcy and closed every single issue without comment.

I created a bot to allow anyone at all to re-open an issue, specifically so that people WOULDN'T feel silenced.

Please re-open this issue if you want more attention brought to it.

**Comment by ChrisSantiago82** [comment] 2020-11-03 18:35
I have the same issue again with another project. This time it's with Laravel 8. I couldn't find a way to reopen this issue. Do you want me to open a new one?

**Comment by iksaku** [comment] 2020-12-23 20:01
REOPEN

**Comment by iksaku** [comment] 2020-12-23 20:05
This is indeed still an issue, but thanks to new Laravel documentation, I Think I got a way to get around this.

Every paginator instance can take a [custom path](https://laravel.com/docs/8.x/pagination#customizing-pagination-urls 
) and assign it to the provided URLs of the `links()` method.

I think at the end you could could opt-in for this feature in full-page components, or manually assign it for partial components.

Could be part of the existing WithPagination trait, behind a `protected $trackComponentPath` property.

What do you guys think?

**Comment by austenc** [comment] 2020-12-29 19:51
If someone provides a demo repository that allows me to easily reproduce this bug, I'd be happy to take a look at it.

@iksaku perhaps you have one?

Thanks!

**Comment by ChrisSantiago82** [comment] 2020-12-29 21:39
@austenc 

Here is a demo repository:
https://github.com/ChrisSantiago82/Livewire-Test

When you click on the Pagination link in the sidebar, you can see that the url changes in the browser. And of course then the pagination links go to the wrong url.
If you remove the pagination from the component, then the url doesn't change when you open the link.

**Comment by austenc** [comment] 2020-12-29 23:26
Thank you @ChrisSantiago82 -- I see the issue, but I'm not sure it's an easy one to fix. Since you're loading the component dynamically, any modification to the query string (which `WithPagination` does) will cause this behavior. 

The tricky part is that in this case, sometimes we want livewire to send path updates (like when actually clicking a "Next" pagination link), and sometimes we don't (like when initializing a component dynamically).

**Comment by ChrisSantiago82** [comment] 2020-12-30 11:26
@austenc Thanks a lot investigating it. I can understand the problem. Lately I'm using livewire more and more and I also have created applications almost like a single page application. The sidebar has dropdowns and selected items, and if I just create that as a livewire component and load the other components dynamically, I don't have to save the state of the side bar.

I can imagine that other people also load components dynamically and I assume they would have the same problems.
If I'm the only one that has the problem, I would just program my own pagination but if other people have the same issues then we should do something. 
You have written that the problem is that livewire "wouldn't know" if the component was loaded dynamically or not. Maybe the user could set an additional parameter manually when it's loaded dynamically or we could create a "WithPagination" for dynamic loaded component that would have a different name. Or as iksaku has mentioned, maybe we could set the links parameter or something like this. What do you think?

**Comment by rmrfstern** [comment] 2021-01-14 14:22
I have the same issue. Loading dynamic a component, which includes Pagination, the url changes to .../livewire/message/... . I am new to laravel, so I have no idea how to work around.

**Comment by joshhanley** [comment] 2021-01-15 01:04
I think #2333 is related

**Comment by alisanie** [comment] 2021-01-21 06:19
I have a same problem but just for now I suggest to add `use WithPagination` in you **parent component** too and It's working.
The Problem is I don't think its a good way

**Comment by OscarKolsrud** [comment] 2021-01-24 00:29
> I have a same problem but just for now I suggest to add `use WithPagination` in you **parent component** too and It's working.
> The Problem is I don't think its a good way

You my dear man are a god, the clock is now 01:30 and this is the solution as of now.

@calebporzio Would it be an idea to add this workaround to the documentation until a "proper" fix is implemented?

**Comment by muhaliusman** [comment] 2021-01-29 04:28
> parent compon

Thanks, you saved Me

**Comment by muhaliusman** [comment] 2021-01-29 04:29
> I have a same problem but just for now I suggest to add `use WithPagination` in you **parent component** too and It's working.
> The Problem is I don't think its a good way

Thanks, you saved me

**Comment by ChrisSantiago82** [comment] 2021-02-04 18:14
Yes, that seams to do the trick. Thank you very much @alisanie 
Now I can update from version 1 to version 2.
We even could consider closing this issue if we write it into the documentation.

**Comment by FaycalBorsali** [comment] 2021-02-24 16:23
> I have a same problem but just for now I suggest to add `use WithPagination` in you **parent component** too and It's working.
> The Problem is I don't think its a good way

THANK YOU, it indeed saved my day !

**Comment by Jam0r85** [comment] 2021-03-08 16:41
Having the same issue without a parent livewire component.

The controller returns a simple view.
The view contains a single livewire component

Contents of the livewire component are as follows

`<?php

namespace App\Http\Livewire\Admin\Property;

use App\Models\Property;
use Livewire\Component;
use Livewire\WithPagination;

class SearchEicrProperties extends Component
{
    use WithPagination;

    public $search;

    public $status;

    public $managed;

    protected $listeners = [
        'eicrRecorded' => '$refresh'
    ];

    public function mount()
    {
        $this->search = request()->query('search', $this->search);
        $this->status = request()->query('status', $this->status);
        $this->managed = request()->query('managed', $this->managed);
    }

    public function recordEicr($propertyId)
    {
        $this->emit('recordEicr', $propertyId);
    }

    public function updated()
    {
        $this->reset('page');
    }

    public function render()
    {
        return view('livewire.admin.property.search-eicr-properties', [
            'properties' => Property::filterWithLetting([
                'search' => $this->search,
                'status' => $this->status,
                'managed' => $this->managed
            ])->latest()->paginate()
        ]);
    }
}
`

Whenever I update any of the public properties and try to use the pagination links it contains the error.

**Comment by Jam0r85** [comment] 2021-03-08 16:57
I've just removed my tailwind pagination view and it's resolved the issue?

```
@if ($paginator->hasPages())
    <nav role="navigation" aria-label="{{ __('Pagination Navigation') }}" class="flex items-center justify-between mt-2">
        <div class="flex justify-between flex-1 sm:hidden">
            @if ($paginator->onFirstPage())
                <span class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 cursor-default leading-5 rounded-md">
                    {!! __('pagination.previous') !!}
                </span>
            @else
                <a href="{{ $paginator->previousPageUrl() }}" class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 leading-5 rounded-md hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-gray-100 active:text-gray-700 transition ease-in-out duration-150">
                    {!! __('pagination.previous') !!}
                </a>
            @endif

            @if ($paginator->hasMorePages())
                <a href="{{ $paginator->nextPageUrl() }}" class="relative inline-flex items-center px-4 py-2 ml-3 text-sm font-medium text-gray-700 bg-white border border-gray-300 leading-5 rounded-md hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-gray-100 active:text-gray-700 transition ease-in-out duration-150">
                    {!! __('pagination.next') !!}
                </a>
            @else
                <span class="relative inline-flex items-center px-4 py-2 ml-3 text-sm font-medium text-gray-500 bg-white border border-gray-300 cursor-default leading-5 rounded-md">
                    {!! __('pagination.next') !!}
                </span>
            @endif
        </div>

        <div class="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
            <div>
                <p class="text-sm text-gray-400 leading-5">
                    {!! __('Showing') !!}
                    <span class="font-medium">{{ $paginator->firstItem() }}</span>
                    {!! __('to') !!}
                    <span class="font-medium">{{ $paginator->lastItem() }}</span>
                    {!! __('of') !!}
                    <span class="font-medium">{{ $paginator->total() }}</span>
                    {!! __('results') !!}
                </p>
            </div>

            <div>
                <span class="relative z-0 inline-flex shadow-sm rounded-md">
                    {{-- Previous Page Link --}}
                    @if ($paginator->onFirstPage())
                        <span aria-disabled="true" aria-label="{{ __('pagination.previous') }}">
                            <span class="relative inline-flex items-center px-2 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 cursor-default rounded-l-md leading-5" aria-hidden="true">
                                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
                                </svg>
                            </span>
                        </span>
                    @else
                        <a href="{{ $paginator->previousPageUrl() }}" rel="prev" class="relative inline-flex items-center px-2 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-l-md leading-5 hover:text-gray-400 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100 active:text-gray-500 transition ease-in-out duration-150" aria-label="{{ __('pagination.previous') }}">
                            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
                            </svg>
                        </a>
                    @endif

                    {{-- Pagination Elements --}}
                    @foreach ($elements as $element)
                        {{-- "Three Dots" Separator --}}
                        @if (is_string($element))
                            <span aria-disabled="true">
                                <span class="relative inline-flex items-center px-4 py-2 -ml-px text-sm font-medium text-gray-700 bg-white border border-gray-300 cursor-default leading-5">{{ $element }}</span>
                            </span>
                        @endif

                        {{-- Array Of Links --}}
                        @if (is_array($element))
                            @foreach ($element as $page => $url)
                                @if ($page == $paginator->currentPage())
                                    <span aria-current="page">
                                        <span class="relative inline-flex items-center px-4 py-2 -ml-px text-sm font-medium text-gray-500 bg-white border border-gray-300 cursor-default leading-5">{{ $page }}</span>
                                    </span>
                                @else
                                    <a href="{{ $url }}" class="relative inline-flex items-center px-4 py-2 -ml-px text-sm font-medium text-gray-700 bg-white border border-gray-300 leading-5 hover:text-gray-500 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100 active:text-gray-700 transition ease-in-out duration-150" aria-label="{{ __('Go to page :page', ['page' => $page]) }}">
                                        {{ $page }}
                                    </a>
                                @endif
                            @endforeach
                        @endif
                    @endforeach

                    {{-- Next Page Link --}}
                    @if ($paginator->hasMorePages())
                        <a href="{{ $paginator->nextPageUrl() }}" rel="next" class="relative inline-flex items-center px-2 py-2 -ml-px text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-r-md leading-5 hover:text-gray-400 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100 active:text-gray-500 transition ease-in-out duration-150" aria-label="{{ __('pagination.next') }}">
                            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                            </svg>
                        </a>
                    @else
                        <span aria-disabled="true" aria-label="{{ __('pagination.next') }}">
                            <span class="relative inline-flex items-center px-2 py-2 -ml-px text-sm font-medium text-gray-500 bg-white border border-gray-300 cursor-default rounded-r-md leading-5" aria-hidden="true">
                                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                                </svg>
                            </span>
                        </span>
                    @endif
                </span>
            </div>
        </div>
    </nav>
@endif

```

**Comment by SanderMuller** [comment] 2021-05-19 11:43
Also having this issue without a parent livewire component just like @Jam0r85.
Has anyone found a solution for this issue?

**Comment by chimerakraken** [comment] 2021-06-11 01:02
> Also having this issue without a parent livewire component just like @Jam0r85.
> Has anyone found a solution for this issue?

you can try to use `@include` to the child component rather than` @livewire` to prevent the child pagination from affecting mother component

**Comment by Liam-PVTL** [comment] 2021-06-11 01:19
> > Also having this issue without a parent livewire component just like @Jam0r85.
> > Has anyone found a solution for this issue?
> 
> you can try to use `@include` to the child component rather than` @livewire` to prevent the child pagination from affecting mother component

This is hard when using directly loaded components from a route, e.g

`Route::get('roles', RolesBrowse::class)->name('roles.browse');`

**Closed** 2021-06-19 17:09 UTC
