### ISSUE TITLE
Is there a method to halt polling ?

### ISSUE THREAD

**Issue by snapey** [livewire/livewire#403] opened 2019-12-09 23:01 UTC
I'm successfully using Livewire to monitor the status of some jobs which process input and post to a third party API.  The livewire component reports the real time progression of a number of these task that were all submitted via CSV file(s).

Because the tasks don't actually take that long, I would like sub-second polling.

Sooner or later, all the 'jobs' are complete and I would like to halt polling.  This could be done from either side, but probably easiest signalled from Laravel.

**Comment by rverrips** [comment] 2020-02-12 18:02
Hi @snapey 
I realize your question has remained unanswered for a while, so not sure if this is still relevant/helpful, but giving it a shot regardless. 

First part of your question - Sub second poling?   Just add the timeframe you want in miliseconds to the call, as per the docs at https://laravel-livewire.com/docs/polling/:
```
<div wire:poll.500ms>
    Current time: {{ now() }}
</div>
```
Second part of your question can probably be solved with a simple @while in blade around your polling, depending on what you get back from the API - perhaps something like:
```
@while (job_still_processing)
    <div wire:poll.500ms>
        Job is still processing {{ some_value_from_api }}
    </div>
@endwhile
``` 
Hope that helps.

**Comment by calebporzio** [comment] 2020-03-15 04:07
Closing this as a duplicate of #563 

There are plans to automatically remove the setInterval after an element or component with `wire:poll` has been removed

**Closed by calebporzio** 2020-03-15 04:07 UTC
Labels: Type: Question

**Comment by snapey** [comment] 2020-03-15 07:47
Just so you know, this would not work for me, as the idea is to poll status of back-end activities, and then when those activities are complete, stop polling but SHOW the final outcome.
The element being refreshed will not be removed from view.
So, I have to carry on needlessly polling or reload the whole page , and omit the poll directive because I can see that all the work is complete.

**Comment by thiagolcks** [comment] 2020-04-27 12:15
Same thing here! Is there a way to stop the polling and keep the element?

**Comment by ekandreas** [comment] 2020-06-09 07:28
It would be nice with some kind of "stopPolling" metod or flag.

**Comment by Wulfheart** [comment] 2020-07-03 19:37
This would be nice indeed.

**Comment by jayenne** [comment] 2020-11-10 15:22
my 2€ would add that 'polling conditionals' could allow us to only poll whislt in the visible screen space or whilst an element is hovered / active or other etc.

**Comment by Matthijs-Huisman** [comment] 2020-11-10 18:06
You can conditionally remove the wire:poll from the blade file if you want to stop polling. Seems to work for me.
`<div @if ($payment->status === 'new') wire:poll.5000ms @endif>`

**Comment by Oxicode** [comment] 2021-04-26 03:53
> my 2€ would add that 'polling conditionals' could allow us to only poll whislt in the visible screen space or whilst an element is hovered / active or other etc.

good idea bro

**Comment by joshhanley** [comment] 2021-04-27 20:58
@jayenne and @Oxicode check out PR #2560 and #2730 🙂

**Comment by christoferd** [comment] 2022-10-27 00:26
I want to be able to set polling to halt after the user is idle. 
ie. if AFK (detected where there is no mouse or keyboard activity for a minute or so)
This is handy for something like a booking calendar that is only edited by that same user. 

Or, be able to halt the calendar on the page, overlaying it with a cover and message, while keeping notifications live and active.
