### ISSUE TITLE
initial-data attribute not found in component after updating to 1.0.1

### ISSUE THREAD

**Issue by besrabasant** [livewire/livewire#659] opened 2020-02-29 18:17 UTC
I updated livewire from `0.7.4` to `1.0.1` and after updating I get this error in the console.

```js
index.js:19 Uncaught TypeError: Cannot read property 'data' of null
    at new Component (index.js:19)
    at index.js:69
    at Array.forEach (<anonymous>)
    at Livewire.start (index.js:67)
    at HTMLDocument.<anonymous> (dashboard:38)
```

The attribute is in the rendered HTML but when the component is parsed by livewire, it is not found.

**Update:-**

I dug into the issue a little bit morning. Here are the steps to reproduce the issue. I assume that you have a fresh installation of Laravel with livewire and Turbolinks installed and configured.

1) Create two separate livewire components.
2) Include those two livewire components in two separate pages.
3) Now add links into your layout to navigate between the two pages.
4) Now navigate to any one of the pages and then quickly navigate to another page while the previous page request is still pending.

**Comment by calebporzio** [comment] 2020-03-02 03:35
Sorry, will need more info on the problem.

**Comment by harrysbaraini** [comment] 2020-03-02 14:09
I'm getting this error as well. I have a form with one text field and several selects. If I just type in the text field and wait the debounce time, it works properly. But if I type and then press TAB or click outside the field, this error is thrown.

**Comment by besrabasant** [comment] 2020-03-02 14:19
Sorry for the discreetness @calebporzio. I have a simple counter livewire component on a page. But when I load the page, I get this error in the console. When I debug the component, I find that the `initial-data` prop on the component returns `null`.

**Comment by mikebronner** [comment] 2020-03-03 22:56
Having the same issue ... not sure how to provide more detail. Here is what I'm seeing:

![Screen Shot 2020-03-03 at 2 55 56 PM](https://user-images.githubusercontent.com/1791050/75827698-17c0a980-5d5f-11ea-82f5-46f29190a50f.png)

**Comment by GRardB** [comment] 2020-03-05 21:31
Not sure how much this helps, but I did some poking around since I'm experiencing the same thing. I added some `console.log` calls to `js/component/index.js`:

```
  extractLivewireAttribute(name) {
    console.log(name)
    console.log(this.el.el)
    const value = this.el.getAttribute(name)

    this.el.removeAttribute(name)

    return value
  }
```

This is what I see in the console:

```
initial-data 
<div wire:initial-data="{\"id\":\"Qp1aG1nXNOYnzd…153ee29cebddcbfa2b1b\"}" wire:id="Qp1aG1nXNOYnzd1LuKFT">

initial-data
<div wire:id="Qp1aG1nXNOYnzd1LuKFT">
```

It looks like it is indeed trying to get `initial-data` from a node that doesn't have it. The `wire:id` in both of those ^ is the same, so it looks like it gets removed at some point? I can keep digging, but I'm looking at this code for the first time, so I can't promise I'll get too far, hah.

**Comment by besrabasant** [comment] 2020-03-06 06:48
@GRardB Yes, I have **Turbolinks** installed.

Ok... I dug into the issue a bit... This issue arises only when you move to another route while the previous route request is not completed.

**Comment by stevebauman** [comment] 2020-03-06 20:09
Getting this too on a simple component using Turbolinks... 

```
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'initialData.data')
	Component (livewire.js:1:40192)
	onNodeAdded (livewire.js:1:46283)
	handleNodeAdded (livewire.js:1:28092)
	handleNodeAdded (livewire.js:1:28465)
	(anonymous function) (livewire.js:1:31493)
	morphEl (livewire.js:1:32026)
	(anonymous function) (livewire.js:1:30204)
	morphEl (livewire.js:1:32026)
	(anonymous function) (livewire.js:1:30204)
	morphEl (livewire.js:1:32026)
	(anonymous function) (livewire.js:1:33060)
	value (livewire.js:1:44995)
	value (livewire.js:1:44409)
	value (livewire.js:1:42892)
	value (livewire.js:1:42530)
	value (livewire.js:1:48071)
	(anonymous function) (livewire.js:1:47774)
	(anonymous function) (livewire.js:1:48982)
	promiseReactionJob```

**Comment by stevebauman** [comment] 2020-03-07 17:33
Ok I've also done some digging, this is with nested components *inside* of a `@foreach`:

```blade
<!-- resources/views/livewire/add-risk-areas.blade.php -->

@foreach($risk->areas as $area)
    @component('add-risk-area', ['risk' => $risk, 'area' => $area], key($area->id))
@endforeach
```

Once I removed the sub-component, I didn't get this issue anymore...

**Comment by devcircus** [comment] 2020-03-29 04:41
As this seems like a very common scenario, sub-component inside a foreach, this probably needs to be looked at. 

I just ran into the same issue with a simple list of posts, using a 'post' sub-component. Pagination will only work for the first click. 

Using the bulit-in Laravel pagination without the 'WithPagination' trait, it works fine as well.

Any ideas @calebporzio?

**Comment by freekmurze** [comment] 2020-04-08 15:22
> I just ran into the same issue with a simple list of posts, using a 'post' sub-component. Pagination will only work for the first click.

Seeing this too in my app.

**Comment by devoided** [comment] 2020-04-15 14:26
Also getting this - in my case, the below error (which corresponds to initialData.data) is raised when my search results contain entries the previous search also contained. I've tried adding totally unique keys to each search result and the issue remains.

<img width="1436" alt="Screenshot 2020-04-15 at 3 24 17 pm" src="https://user-images.githubusercontent.com/39875798/79348749-508e9980-7f2d-11ea-8433-693c51bec01c.png">

**Comment by heruputra** [comment] 2020-04-17 17:02
Got the same error when using nested components and not using Turbolinks.

Fixed the issue by changing the nested component's key to a random one.

Before
```
@foreach($contacts as $key => $contact)
    @livewire('child-component', [], key($contact->id))
@endforeach
```

After
```
@foreach($contacts as $key => $contact)
    @livewire('child-component', [], key(rand() * $contact->id))
@endforeach
```

And still don't know why this tweak works 🤔

**Comment by damms005** [comment] 2020-04-19 23:00
> Can confirm I am using nested components inside a foreach

Weighing-in to this too. Reactive reload simply does not work for me when using nested components (i.e. sub-components) in foreach loop. Same console log error as OP

Now for me, it does not matter if reload is due to reacting to event from child component (to kind of re-run the loop) or even through normal `wire:poll`). It just spits that error instead of repainting

**Comment by luchaos** [comment] 2020-04-22 12:38
I get this error as soon as i add any component to a view, an empty one, too (v1.0.12).
Logging `console.log('initialize', this.id, initialData);` in the constructor:

```
export default class Component {
    constructor(el, connection) {
        el.rawNode().__livewire = this
        this.id = el.getAttribute('id')
        const initialData = JSON.parse(this.extractLivewireAttribute('initial-data'))

        console.log('initialize', this.id, initialData);

        this.data = initialData.data || {}
        this.events = initialData.events || []
        this.children = initialData.children || {}
        this.checksum = initialData.checksum || ''
        this.name = initialData.name || ''
        this.errorBag = initialData.errorBag || {}
        this.redirectTo = initialData.redirectTo || false
        this.scopedListeners = new MessageBus,
        this.connection = connection
        this.actionQueue = []
        this.messageInTransit = null
        this.modelTimeout = null
        this.tearDownCallbacks = []
        this.prefetchManager = new PrefetchManager(this)
        this.echoManager = new EchoManager(this)
```
With just one component on the page, it is constructed multiple times, deleting the `initial-data` attribute after the first time (present on initial load)

![Screenshot 2020-04-22 at 14 33 22](https://user-images.githubusercontent.com/1280590/79982561-d0c17b80-84a6-11ea-9924-2d908978bae1.png)

**Comment by togglebroadband** [comment] 2020-04-28 16:14
Just had this issue come up after adding a Livewire component within another.

I'm using the Livewire routing and then a sub component in that view, adding a random key (as suggested) prevents the error but would like to not have to.

I'm not using debugbar so the comment above doesn't fix all issues.

**Comment by Te7a-Houdini** [comment] 2020-04-28 16:16
#889 will fix that

**Comment by Te7a-Houdini** [comment] 2020-04-28 21:54
@togglebroadband @heruputra  are you sure that the key is unique ?

also if possible  @togglebroadband  can you put your code

**Comment by JunaidQadirB** [comment] 2020-05-06 07:04
Is there a temporary solution to this issue until it gets resolved?

**Comment by asantibanez** [comment] 2020-05-08 03:27
Just stumbled into this problem. Got it solved putting :keys to every nested component in a loop. Hopefully it helps!

**Comment by indigoram89** [comment] 2020-05-14 14:21
Adding the key solves the problem for me:

@livewire("path.to.component.{$model->id}", [], key($model->id))

**Comment by asantibanez** [comment] 2020-05-17 20:04
Agreed @indigoram89 

It gets solved also by adding a `key` to every component. Not only to components rendered in loops. 👍

**Comment by bomshteyn** [comment] 2020-05-28 19:26
I have encountered this this error when having a laravel component inside livewire component template that had a livewire component as a slot. Adding `key` didn't solve it for me.

**Comment by jdtanjuaquio** [comment] 2020-05-31 20:35
> Got the same error when using nested components and not using Turbolinks.
> 
> Fixed the issue by changing the nested component's key to a random one.
> 
> Before
> 
> ```
> @foreach($contacts as $key => $contact)
>     @livewire('child-component', [], key($contact->id))
> @endforeach
> ```
> 
> After
> 
> ```
> @foreach($contacts as $key => $contact)
>     @livewire('child-component', [], key(rand() * $contact->id))
> @endforeach
> ```
> 
> And still don't know why this tweak works 🤔



> Got the same error when using nested components and not using Turbolinks.
> 
> Fixed the issue by changing the nested component's key to a random one.
> 
> Before
> 
> ```
> @foreach($contacts as $key => $contact)
>     @livewire('child-component', [], key($contact->id))
> @endforeach
> ```
> 
> After
> 
> ```
> @foreach($contacts as $key => $contact)
>     @livewire('child-component', [], key(rand() * $contact->id))
> @endforeach
> ```
> 
> And still don't know why this tweak works 🤔

After a long search, This one works for me.

**Comment by trollfalgar** [comment] 2020-06-01 02:11
> Got the same error when using nested components and not using Turbolinks.
> 
> Fixed the issue by changing the nested component's key to a random one.
> 
> Before
> 
> ```
> @foreach($contacts as $key => $contact)
>     @livewire('child-component', [], key($contact->id))
> @endforeach
> ```
> 
> After
> 
> ```
> @foreach($contacts as $key => $contact)
>     @livewire('child-component', [], key(rand() * $contact->id))
> @endforeach
> ```
> 
> And still don't know why this tweak works thinking

This works perfectly.

**Comment by cosmospham** [comment] 2020-06-01 03:35
Thank @heruputra

According to [this document](https://laravel-livewire.com/docs/nesting-components)

> Similar to VueJs, if you render a component inside a loop, Livewire has no way of keeping track of which one is which. To remedy this, livewire offers a special "key" syntax:

```
<div>
    @foreach ($users as $user)
        @livewire('user-profile', ['user' => $user], key($user->id))
    @endforeach
</div>
```

**Comment by dgironella** [comment] 2020-06-04 10:00
Any new about this problem. I don't have a loop components, only nestes components, putting a fixed key is not solved problem.

**Comment by cosmospham** [comment] 2020-06-04 10:02
> Any new about this problem. I don't have a loop components, only nestes components, putting a fixed key is not solved problem.

Have you ever tried `key(rand().'name...')`?

**Comment by dgironella** [comment] 2020-06-04 10:10
> > Any new about this problem. I don't have a loop components, only nestes components, putting a fixed key is not solved problem.
> 
> Have you ever tried `key(rand().'name...')`?

Now work, with key(rand()) only not, very stranger....

**Comment by nuernbergerA** [comment] 2020-06-04 12:44
> Got the same error when using nested components and not using Turbolinks.
> 
> Fixed the issue by changing the nested component's key to a random one.
> 
> Before
> 
> ```
> @foreach($contacts as $key => $contact)
>     @livewire('child-component', [], key($contact->id))
> @endforeach
> ```
> 
> After
> 
> ```
> @foreach($contacts as $key => $contact)
>     @livewire('child-component', [], key(rand() * $contact->id))
> @endforeach
> ```
> 
> And still don't know why this tweak works

That's not a good solution at all.

Key should help Livewire to find elements in the DOM.

A better solution would be to combine the component name and the primary key.
```blade
@foreach($contacts as $key => $contact)
    @livewire('child-component', [], key('child-component' . $contact->id))
@endforeach
```

I will open a PR to automagic prefix the key with the component name if the key is numeric.

**Comment by cosmospham** [comment] 2020-06-05 00:59
> > Got the same error when using nested components and not using Turbolinks.
> > Fixed the issue by changing the nested component's key to a random one.
> > Before
> > ```
> > @foreach($contacts as $key => $contact)
> >     @livewire('child-component', [], key($contact->id))
> > @endforeach
> > ```
> > 
> > 
> > After
> > ```
> > @foreach($contacts as $key => $contact)
> >     @livewire('child-component', [], key(rand() * $contact->id))
> > @endforeach
> > ```
> > 
> > 
> > And still don't know why this tweak works
> 
> That's not a good solution at all.
> 
> Key should help Livewire to find elements in the DOM.
> 
> A better solution would be to combine the component name and the primary key.
> 
> ```
> @foreach($contacts as $key => $contact)
>     @livewire('child-component', [], key('child-component' . $contact->id))
> @endforeach
> ```
> 
> I will open a PR to automagic prefix the key with the component name if the key is numeric.

I don't think so. I have tried with fixed keys and it didn't work, but `rand()` worked.

**Comment by nuernbergerA** [comment] 2020-06-05 05:27
Well if you use
```blade
@foreach($contacts as $key => $contact)
    @livewire('child-component', [], key(rand()))
@endforeach
```
It will behave the same as:
```blade
@foreach($contacts as $key => $contact)
    @livewire('child-component')
@endforeach
```

Because livewire will add a random string as key if there is no key defined.

**Comment by cosmospham** [comment] 2020-06-05 07:07
But I wonder why it does not work from the begining, when I didn't use `key()` function. That caused this:

```
index.js:19 Uncaught TypeError: Cannot read property 'data' of null
```

**Comment by nuernbergerA** [comment] 2020-06-05 08:37
That's a good question.
Since the issue has many comments it's hard to me to catch up.

Would you mind posting detailed steps for me to reproduce?

**Comment by taylormaguire** [comment] 2020-06-19 07:02
I've run into the same issue as most people here, issue persists with Turbolinks and without. I've tried to randomize the key and i've tried adding a key to call nested components. same issue across the board.

**Comment by mercuryseries** [comment] 2020-06-20 13:28
In case it might help, I got the same error when including @livewireScripts **twice** by mistake.
(I'm not using Turbolinks nor loops)

**Comment by oliverbj** [comment] 2020-06-22 11:38
Just ran into this issue as well (also for nested components)

**Comment by devoided** [comment] 2020-06-22 16:10
Can confirm I had this issue for a while - turns out it was triggered when content with a duplicate key appeared on the page twice (eg when searching, then subsequently searching again yielding some of the same results as search 1)

Fixed by using the `rand() * $result->id` method mentioned above

**Comment by calebporzio** [comment] 2020-06-24 14:42
First, I'll say that sometimes when you see this error, it's because you are loading `@livewireScripts` twice.

I added a console.warn to Livewire to help people with this case.

It appears there's something deeper here with nested components.

I would love for someone to post an explicit replication of this error that I can copy and past requiring no domain code. Otherwise, it'll be very hard for me to debug.

Thanks!

**Comment by taylormaguire** [comment] 2020-06-24 15:33
i can give you access to my repo and willing to do a quick video or tuple call if you want too

08:26:49.529 Uncaught (in promise) TypeError: can't access property "data", initialData is null
    Component index.js:20
    onNodeAdded index.js:342
    callHook morphdom.js:35
    handleNodeAdded morphdom.js:140
    morphEl morphdom.js:407
    morphEl morphdom.js:219
    morphEl morphdom.js:332
    morphEl morphdom.js:219
    morphdomFactory morphdom.js:463
    handleMorph index.js:252
    value index.js:225
    value index.js:170
    value index.js:146
    value index.js:30
    onMessage index.js:9
    sendMessage http.js:32
    promise callback*sendMessage/< http.js:27
    promise callback*sendMessage http.js:25
    value index.js:41
    value index.js:130
    later debounce.js:50
    setTimeout handler*debounce/< debounce.js:54
    value index.js:116
    emit Store.js:53
    emit Store.js:52
    value index.js:187
    value index.js:177
    value index.js:146
    value index.js:30
    onMessage index.js:9
    sendMessage http.js:32
    promise callback*sendMessage/< http.js:27
    promise callback*sendMessage http.js:25
    value index.js:41
    value index.js:130
    later debounce.js:50
    setTimeout handler*debounce/< debounce.js:54
    value index.js:116
    debouncedHandler node_initializer.js:179
    value index.js:421
    debouncedHandler node_initializer.js:141
    value dom_element.js:183
    attachListener node_initializer.js:193
    attachDomListener node_initializer.js:123
    initialize node_initializer.js:25
    initialize node_initializer.js:9
    value index.js:71
    value index.js:369
    walk walk.js:5
    walk walk.js:10
    walk walk.js:10
    value index.js:356
    value index.js:69
    Component index.js:40
    value index.js:75
    value index.js:364
    walk walk.js:5
    walk walk.js:10
    walk walk.js:10
    value index.js:356
    value index.js:69
    Component index.js:40
    value index.js:73
    value index.js:71
    value index.js:63
    <anonymous> (index):286
    dispatch turbolinks.js:5
    notifyApplicationAfterPageLoad turbolinks.js:6
    visitCompleted turbolinks.js:6
index.js:20:69

**Comment by notomato** [comment] 2020-06-25 16:14
Also getting the same issue - it's definitely something with nested components, with key and without, I will work on reproducing it.

**Comment by notomato** [comment] 2020-06-25 17:07
To reproduce clone https://github.com/notomato/livewire-issue-659, visit `/test` and click the button to add children.

**Comment by asantibanez** [comment] 2020-06-25 17:34
Thanks @notomato for putting an example together. I am able to reproduce the bug.

However, I was able to fix it with the `key` attribute. 

![2020-06-25 12 29 03](https://user-images.githubusercontent.com/5126648/85769459-a034d280-b6df-11ea-8c7a-05833457809b.gif)

(added some styling also 😎) 

I added an unique id to each rendered child component

![image](https://user-images.githubusercontent.com/5126648/85769707-dc683300-b6df-11ea-8a6d-6d59f7a3ac5c.png)

In the parent component the id is set using and uuid4 on the loop

![image](https://user-images.githubusercontent.com/5126648/85769803-f570e400-b6df-11ea-95e3-f4c812315846.png)

I updated the child layout to be show wire:model is also working

![image](https://user-images.githubusercontent.com/5126648/85770062-281adc80-b6e0-11ea-95a5-8382fb2ebd1d.png)

Hope this helps.

**Comment by asantibanez** [comment] 2020-06-25 17:49
Hello everyone! Want to share my two cents on how to fix these kind of bugs. I've had some eureka moments when working with Livewire. It's not a vast list and it's narrowed down to my experience with the framework.

- Always put a `key` attribute when rendering components in a loop. Not `:key` or `wire:key`. Just `key`. This key must be unique among the rendered components. 

![image](https://user-images.githubusercontent.com/5126648/85772175-34079e00-b6e2-11ea-9ef5-b6afaa73b61a.png)

- Nested components by themselves do not need a `key`. However, they can break when rendering next to other dynamics parts of the view. For example

![image](https://user-images.githubusercontent.com/5126648/85771574-a926a380-b6e1-11ea-9424-5d78c60d2017.png)

This will break the nested component when the foreach renders a new element. My wild guess is that Livewire tracks the position in the DOM where the component is located. Let's say we have 10 items rendered, then our NestedComponent will be on the 11th position. When rendering 11 items, our component goes to the 12th position and it breaks. To avoid this, add a wrapper element to every dynamic sections of your view: foreach, if, etc.

![image](https://user-images.githubusercontent.com/5126648/85771872-f0ad2f80-b6e1-11ea-912d-42fd972bae66.png)

This time, the Nested component will be always in the 2nd position, no matter how many the items the loop renders.

Hope this helps!

**Comment by taylormaguire** [comment] 2020-06-25 18:25
Andres, thanks for sharing, this has been my experience as well, however in my case I’ve also had to add a key to both the parent and child components, in and this case both keys had to be randomized.

**Comment by jantinnerezo** [comment] 2020-06-25 18:26
Thank you! @asantibanez

**Comment by notomato** [comment] 2020-06-26 02:18
Thanks @asantibanez - can confirm adding "key" attribute to child component resolves this (and not wire:key). Not sure why though, didn't see mention of a key attribute anywhere in docs.

**Comment by taylormaguire** [comment] 2020-06-26 15:02
@notomato you can find it here in the docs. bottom of the page

https://laravel-livewire.com/docs/nesting-components

**Comment by notomato** [comment] 2020-06-27 07:46
D’oh. Thanks.
GitHub <notifications@github.com> wrote:
“@notomato you can find it here in the docs. bottom of the page


https://laravel-livewire.com/docs/nesting-components”

**Comment by thijsvdanker** [comment] 2020-07-08 19:05
I have the same issue and I've created a repository to reproduce it here https://github.com/thijsvdanker/livewire-initial-data-bug

Some essential ingredients to that example are:

1. Vuejs is loaded
2. there are some nested components (blade view -> livewire component -> blade component -> livewire component)
3. !! there is no text above the blade component :/

Number 3 is what surprised me the most.

This works (no error)
```blade
<div>
    Some text above regular component
    <x-regular-component />
    <button wire:click="next" type="button">Next</button>
</div>
```

And this doesn't (initial data error)
```blade
<div>
    <x-regular-component />
    <button wire:click="next" type="button">Next</button>
</div>
```

I hope this helps a little.

**Comment by thijsvdanker** [comment] 2020-07-10 15:15
My issue (above) was resolved by adding https://github.com/livewire/vue and adding `window.vue = Vue` as described [here](https://github.com/livewire/vue/pull/13/commits/a9258f482244b601a85ae719fc859d44e9f02e1c)

**Comment by jeffochoa** [comment] 2020-07-17 19:48
I just ran into this, using nested components inside a foreach:

```
<livewire:list wire.poll>
    @foreach($items as $item)
        <livewire:item></livewire:item>
    @endforeach
</livewire:list>
```

The error appears when the list is updated from the `wire.poll`


Adding a unique key to the nested component did the trick for me:

```
<livewire:list wire.poll>
    @foreach($items as $item)
        <livewire:item :key="$item->id"></livewire:item>
    @endforeach
</livewire:list>
```

Adding the `key` attribute is not a big deal, although it is not a very obvious solution; maybe just adding a more verbose error message could help.

**Comment by ardyn** [comment] 2020-07-31 03:17
Had an issue "initialData is null". Similar setup:

```
foreach(...) {
<livewire:parent>
   foreach(...) {
     <livewire:child />
  }
</livewire:parent>
}
```
At first I added `:keys="$model->id"` to parent and child. Same issue.
Then I prefixed the model name to keys `:keys="model-name.$model->id"`
Then I realized I really don't know how this syntax works.
Finally this actual code snippet worked `<livewire:component-name :mount-parameter-name="$model" key="model-name.{{ $model->id }}" />`

I added these keys to each component, nested or not. So far everything seems to work. Notice curly braces and lack of colon : before keys.

**Comment by fontenele** [comment] 2020-08-14 18:17
I have this bug caused by lib laravel debugbar.
Fixed changing options.views.data = false at /config/debugbar.php

```
options' => [
    ...
    'views' => [
        'data' => false, // change to false with livewire
    ],'
```

**Comment by calebporzio** [comment] 2020-09-17 17:51
Closing due to inactivity

**Closed by calebporzio** 2020-09-17 17:51 UTC
Labels: Needs Better Reproducibility

**Comment by jearsonbgomez** [comment] 2020-09-18 08:20
> Got the same error when using nested components and not using Turbolinks.
> 
> Fixed the issue by changing the nested component's key to a random one.
> 
> Before
> 
> ```
> @foreach($contacts as $key => $contact)
>     @livewire('child-component', [], key($contact->id))
> @endforeach
> ```
> 
> After
> 
> ```
> @foreach($contacts as $key => $contact)
>     @livewire('child-component', [], key(rand() * $contact->id))
> @endforeach
> ```
> 
> And still don't know why this tweak works 🤔

Yeah this works.

**Comment by mattyl** [comment] 2021-03-09 09:28
I wanted to add to this thread as I spent a lot of time trying to work it out - I had a similar issue as everyone else with the same error message. But i was adding using include


`                    @foreach($product->operations as $operation)
                        @php
                            $counter = 0;
                        @endphp
                               @include('livewire.item.operationslist')
                    @endforeach`

in my include  i had nested elements like

` @livewire('edit-field',['id'=>$operation->pivot->id,'object'=>'ProductOperation','field'=>'qty'], key(rand() * $operation->pivot->id))
`
these elements were all working - but in my main template i had a modal - which suddenly stopped working correctly

`            @if($isOpen)
                @include('livewire.tag-create')
            @endif`

I couldn't work it out - i tried all sorts of mucking about with the keys - removing the nested elements, it worked. Then as a hail mary I went back and stuck the divs around the modal in the main template - and wow it works! Now i found the solution it seems obvious - without any nested elements - the componet was happy - with nested elements it wasnt. And ther eis a big red eclamation mark int he livewire documents. but I hope this helps someone else searching and goign mad with keys.... it might be you are not rendering the componets correctly. Just to be clear my solution was

`<div>
            @if($isOpen)
                @include('livewire.tag-create')
            @endif
</div>`

**Comment by claytonrcarter** [comment] 2021-03-12 20:40
I was also bitten by this, and I'm also just learning LW. In my case, I had a LW component that rendered a regular blade component in a loop, and that blade component included a LW component in each iteration. In my case I had to add `wire:key` to each of the blade component iterations AND to the LW component w/i each iteration. Leaving either out would trigger this error.

This wasn't working:
```
<livewire:table>
  @foreach(...)
    <!-- this is just a blade component -->
    <x-table-row>  
      <td>...</td>
      <td>...</td>
      <td>
        <livewire:sub-component>
      </td>
    </tr>
  @endforeach
</table>
```

This **is** working:
```
<livewire:table>
  @foreach(...)
    <!-- this is just a blade component -->
    <x-table-row wire:key="{{ $model->id }}">
      <td>...</td>
      <td>...</td>
      <td>
        <livewire:sub-component :key="$model->id">
      </td>
    </tr>
  @endforeach
</table>
```

Hope that helps someone else.

**Comment by troccoli** [comment] 2021-05-08 11:04
I had a very simila issue to this.

I have a `posts.list-posts` component and a `posts.single-post` component. The homepage blade view is

```html
<x-app-layout>
    <x-slot name="header">
        <x-banner/>
    </x-slot>

    <livewire:posts.list-posts/>

</x-app-layout>
```

and the `posts.lists-posts` template was

```html
<div class="flex flex-col">
    @foreach($posts as $post)
        <livewire:posts.single-post :post="$post"/>
    @endforeach
    <div class="flex">
        <button wire:click="loadMorePosts" wire:loading.attr="disabled">
            <x-loading-icon/>
            <span>More posts</span>
        </button>
    </div>
</div>
```
(I removed some styling for semplicity)

By clicking the `More posts` button I got `Uncaught (in promise) TypeError: initialData is null` error in the console.

After reading all this thread the only solution that works for me was to add a key to the `posts.single-post` component as follows

```html
<livewire:posts.single-post :post="$post" key="{{ $post->id }}"/>
```

Using `:key`, `wire:key` or even ':wire:key` (as the documentation says) **did not work**.

So, make sue your use just `key` and notice the key is wrapped in `{{ }}`.

**Comment by joshhanley** [comment] 2021-05-09 00:09
@troccoli if you use `:key` on a nested Livewire component it needs to be a PHP expression so like this `:key="$post->id"`. Basically you can't use the blade echo tags `{{ }}` if you are adding `:` before a property name. But if you don't have the `:` in front, then that is why your key with `{{ $post->id }}` works.

The reason why `wire:key` or `:wire:key` probably didn't work would be due to Livewire version. It was only recently added for nested Livewire components in Livewire v2.4.4, so I'd recommend upgrading to that first and testing it out.

Hope this helps!

**Comment by troccoli** [comment] 2021-05-09 11:16
@joshhanley, my mistake, I thought it was obvious that I didn't user the curly brackets when not necessary, as I tried all possible solutions in the thread.

As for the version, I did have Livewire v2.4.2, and when I upgraded to v2.4.4 I can confirm that both `:wire:key="$post-id"` and `:key="$post-id"` work.

**Comment by viaativaweb** [comment] 2021-05-26 14:16
This issue needs to be reopened ASAP. The error was never fixed and the exception message is still completely obscure and leaves no clue what's wrong. I lost count of how many times I faced this bug and have to comment out my components one by one to find the wrong key. This is seriously fustrating and demoralizing.
