### ISSUE TITLE
@entangle works a bit randomly

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#1761] opened 2020-10-06 12:27 UTC
### Description
I know this is an awful bug report, but so is the bug. I tried to understand the pattern but I thought maybe someone else has a similar problem and we can work it together.

So, I have created a `date-picker` with Alpinejs. there's a `selected` variable on this component that is `entangled` with the `wire:model`. So you pick a date, the component changes its `selected` and it should update livewire right? Well sometimes!

I noticed if that's the first thing I do on the page, it works. But if I change values of other livewire inputs, then click on a date, it doesn't work and I have to click on a different date a second time for it to start working.

### Stripped-down, copy-pastable code snippets
This is the datepicker component:
https://gist.github.com/mokhosh/ccd231b1ffd19d5aea3e666b8224b98a
and this is how I use it with one other input:
```php
<div class="mt-8">
    <label class="block text-gray-700 uppercase">Percent Done</label>
    <div class="flex">
        <input wire:model.lazy="project.percent_done" class="flex-1 p-2 border border-gray-300 rounded-lg focus:outline-none">
    </div>
</div>
<div class="mt-8">
    <label class="block text-gray-700 uppercase">Project Due Date</label>
    <x-date-picker wire:model="project.due_date"/>
</div>

```

**Context**
- Livewire version: latest
- Laravel version: latest
- Browser: chrome

**Comment by Slowwie** [comment] 2020-10-06 13:17
Yes, I am about to create a select2 like choice picker with alpine and livewire. I thought it would be great to use @entangle - and experimented now 2 days around with it. Things like this also happened to me. I try now to drop @entangle and use v1 techniques until this alpinejs/livewire connection is less buggy.

**Comment by basepack** [comment] 2020-10-07 06:10
Please show only the relevant code, stripped down to as few lines as possible.

**Comment by mokhosh** [comment] 2020-10-07 14:23
Ok I got the problem, and fixed it with a hack. Don't know what is the real fix.

So, if my `@entangle`d property is changing from `null` to a value, livewire doesn't send a request. BUT if I set a dummy value if it's null, and only THEN set the real value, everything works:

```js
```

**Comment by austenc** [comment] 2020-10-17 16:27
@mokhosh are you still experiencing this with Livewire `2.3.0` ?

**Comment by mokhosh** [comment] 2020-10-17 17:32
Yes, still there

**Comment by mokhosh** [comment] 2020-10-19 18:03
I have to do some nasty hacks to work around this:
```
x-on:change="value = window.mde.value()+' ';value = window.mde.value().slice(0,-1);" 
```

**Comment by squishythejellyfish** [comment] 2020-10-29 21:26
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by mokhosh** [comment] 2020-10-29 21:34
REOPEN

**Comment by mokhosh** [comment] 2020-10-29 21:35
I love you @calebporzio

**Comment by austenc** [comment] 2020-11-02 21:53
@mokhosh just a guess here, but when I've seen strange things like this in my own projects, it always comes down to a conflicting event listener. If you're using extra javascript libraries that manipulate the element's value, try to reproduce this without those.

**Comment by mokhosh** [comment] 2020-11-03 04:10
No javascript libraries. I hate most libraries for the reason you mentioned and do my best to avoid using them.

**Comment by joshhanley** [comment] 2020-11-04 03:12
@mokhosh with your date picker component, I'm assuming it is initialising Alpine just for it's own purposes (I can't see the gist)?

If that is the case, do you also have Alpine initialised outside the component in a parent element that is wrapping it somewhere? 

Here's what I think is happening, Alpine is loaded on the page somewhere near the top, but when it gets another Alpine element nested inside of it, such as your date picker, thats when \@entangle isn't firing correctly to start with on the inner component. But after click around a bit, it does eventually start working.

Can you confirm if that is the case?

If so, I will see if I can get a test to replicate the issue.
I believe #1952 might be related.

**Comment by mokhosh** [comment] 2020-11-04 04:27
On one of my pages it's nested, on another it's not.

On the nested page, the datepicker wouldn't work the first time you select a date even if you do it before touching other inputs.

On the non nested page, it worked if you selected the date first and then modified other inputs, or if you only modified only one input before it. But if you change two inputs and then use the datepicker it doesn't work here either!

Very random.

**Comment by joshhanley** [comment] 2020-11-04 20:40
Ok thanks, I will see if I can replicate some of the issues more consistently to write some tests.

**Comment by joshhanley** [comment] 2020-11-05 01:26
I think I have found one of the issues to do with entangling model properties and the changes not triggering from Alpine to Livewire correctly. I have created a test to replicate the issue, but there is an issue on master that is stopping me finishing the test and confirming what I have found with a failing test. I will PR that soon.

Basically what I found is if you have say a user model bound to `public User $user` and you have rules such as below, and you have entangled a property such as `active: @entangle('user.active')`. When you use Livewire to change `$this->user` to another user, then the Livewire entangle watchers don't run for the first couple of changes.

Rules:
```php
$rules = [
    'name' => 'required|string',
    'active' => 'required|boolean'
];
```

Does that sound similar to what you might be running into?

Have a look here, if you click toggle active you will see it toggle fine. But if you then click "change to user 2" and then click toggle once, you will see it doesn't toggle the Livewire end. But clicking twice more finally gets toggling running again.

![Toggle Model Property](https://user-images.githubusercontent.com/882837/98185781-729b4800-1f61-11eb-9720-2046666a08c8.gif)

Interestingly if you comment out the 'name' rule above, everything works fine first time around.

![Toggle Model Property Working](https://user-images.githubusercontent.com/882837/98186011-f6553480-1f61-11eb-9965-310b690942de.gif)

**Comment by mokhosh** [comment] 2020-11-05 02:39
In my case I don't change the eloquent model after I've loaded it in `mount`. Does that count as changing as well?

**Comment by Matthijs-Huisman** [comment] 2020-11-10 13:43
I'm experiencing the same issues with a "select" that has an entangled x-model variable. It just won't pick up the updated value in any of the requests to the livewire endpoint. When I add an <span x-text="variable"></span> it shows correct, and it will update too.

**Comment by joshhanley** [comment] 2020-11-10 19:39
@Matthijs-Huisman can you show your code? If so, can you show your blade (where you use select and entangle) and your rules array from the component?

**Comment by Matthijs-Huisman** [comment] 2020-11-10 19:54
Blade file:
`<form wire:submit.prevent="startCheckout">
    <div x-data="{ bank: @entangle('bank').defer }">
<select x-model="bank">
<option value="-">- select your bank</option>
<option value="bank1">Bank 1</option>
<option value="bank2">Bank 2</option>
</select>
    </div>
<button type="submit">Checkout</button>
</form>
`

This code won't update my 'bank' variable in the livewire component, only the first time I pick bank1 for example. I always check it in the network-tab, the bank variable will only update once, after that it won't change anymore. Doesn't seems to be in the rules array I used, when I also add wire:model.defer="bank" to the select it works fine.

If you need more, let me know.

**Comment by joshhanley** [comment] 2020-11-10 20:06
@Matthijs-Huisman ah ok yeah, this thread is more about problems when entangling properties of a model like `$user->name` is used `@entangle('user.name')`.

With your issue (if I understand it correct), there is a bug with @entangle.defer that will be fixed in the next release. Have a look at this issue #1774 and this PR #1947.

**Comment by Matthijs-Huisman** [comment] 2020-11-10 20:10
@joshhanley Yup, seems to be that issue! Thanks for fixing it, will implement it after release 👌🏼

**Comment by jeffchown** [comment] 2020-11-30 17:50
REOPEN

I've been experiencing exactly the same unpredictable behaviour with the datepicker using entangle as described in @mokhosh 's original post (even after reverting to Livewire 2.3.1 per help from @joshhanley in another issue thread), and wanted to make sure that both cases if identified (which have been mentioned separately by other people above) will be addressed in the next Livewire release ('cause I'd really like to use entangle in my custom input components! :).

So, I've found the behaviour @mokhosh described is reproducibly triggered in my tests by either of the following:

1. if I use a nested model attribute (e.g. user.birthday) in the <x-input.date> (entangled version) - therefore, switching to a non-nested (e.g. public $birthday) seems to work as expected (though not easily utilized as a workaround in my app)

2. if I use the entangled version of <x-input.date> from the Surge screencasts - therefore, reverting to the previous Livewire v1.x version shown in an earlier Surge video works fine (the workaround that seems best for my app until the issues are resolved) 

Using entangle in other places in my code (e.g. isOpen for dropdowns, modals, etc.) seems to consistently work as expected.  My challenges have been re: the inconsistent (and, therefore, unreliable in production code right now) behaviour experienced in custom input components when combining entangle with wire:model.

I apologize if this is repetitive, but felt a summary/consolidation might help after the extensive experiments/troubleshooting performed by many people which is made evident spread across multiple issues/threads.

Thanks.

**Comment by jeffchown** [comment] 2020-11-30 17:51
I've been experiencing exactly the same unpredictable behaviour with the datepicker using entangle as described in @mokhosh 's original post (even after reverting to Livewire 2.3.1 per help from @joshhanley in another issue thread), and wanted to make sure that both cases if identified (which have been mentioned separately by other people above) will be addressed in the next Livewire release ('cause I'd really like to use entangle in my custom input components! :).

So, I've found the behaviour @mokhosh described is reproducibly triggered in my tests by either of the following:

1. if I use a nested model attribute (e.g. user.birthday) in the <x-input.date> (entangled version) - therefore, switching to a non-nested (e.g. public $birthday) seems to work as expected (though not easily utilized as a workaround in my app)

2. if I use the entangled version of <x-input.date> from the Surge screencasts - therefore, reverting to the previous Livewire v1.x version shown in an earlier Surge video works fine (the workaround that seems best for my app until the issues are resolved) 

Using entangle in other places in my code (e.g. isOpen for dropdowns, modals, etc.) seems to consistently work as expected.  My challenges have been re: the inconsistent (and, therefore, unreliable in production code right now) behaviour experienced in custom input components when combining entangle with wire:model.

I apologize if this is repetitive, but felt a summary/consolidation might help after the extensive experiments/troubleshooting performed by many people which is made evident spread across multiple issues/threads.

Thanks.

**Comment by jeffchown** [comment] 2020-12-01 17:26
UPDATE: I just tested Livewire 2.3.4 with my @entangle'd version of my custom Livewire input components in all of the above scenarios and all seems to be working 👍  😄   (and that includes a toggle input component which addresses the boolean issue described in another issue thread)

Thanks @joshhanley for your help and Thanks @calebporzio for the updates!

**Comment by calebporzio** [comment] 2020-12-01 21:07
Woot! Thanks!

**Comment by squishythejellyfish** [comment] 2020-12-01 21:07
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed** 2020-12-01 21:07 UTC
