### ISSUE TITLE
new Laravel 7 tag not working with multiple parameters

### ISSUE THREAD

**Issue by alewolf** [livewire/livewire#988] opened 2020-05-19 20:07 UTC
### Description

I have converted this working tag

`@livewire('price-table', ['table' => $table, 'local_country' => $local_country])`

to the new Laravel 7 tag

`<livewire:price-table :table="$table" :local_country="$local_country">`

and get following error:

`Unresolvable dependency resolving [Parameter #1 [ <required> $local_country ]] in class App\Http\Livewire\PriceTable (View: /Users/example/dev/apps/example/resources/views/example.blade.php)`

When I reduce this to only one parameter, then it works:

`<livewire:price-table :table="$table">`

Is there a specific way to pass two parameters in the new tag? Or is this maybe a bug?

**Context**
- Livewire version: 1.1.0
- Laravel version: 7.11.0
- Browser: Chrome

**Comment by ManojKiranA** [comment] 2020-05-20 06:26
I have Gone through the issue this is not because of Multiple Parameters its because of assigning the constructor variables as snake case.

For now change `local_country` variable of constrcutor to `localCountry` will fix the issue

You don't need to change the the props

```
public function mount($localCountry)
 {
  $this->local_country= $localCountry;
 }
```

**Comment by alewolf** [comment] 2020-05-20 11:32
Thanks @ManojKiranA 

I can confirm that this works with your suggested change. 

Should I keep this open as a bug? Because clearly in my mind this should be either addressed in the Livewire code or in the documentation.

**Comment by ManojKiranA** [comment] 2020-05-20 12:10
@alewolf  it's definitely a bug. For now i have given a suggestion. i am not sure about why it is converting parameters name or may be its expected behaviour.

cc @calebporzio

**Comment by calebporzio** [comment] 2020-06-30 23:38
I believe this is happening on the Laravel end. I would recommend either camelCasing or kebab-casing params.

Closing for now.

**Closed by calebporzio** 2020-06-30 23:38 UTC

**Comment by blhi-jed** [comment] 2021-04-12 13:16
just got the same bug, apart from camel/kebab, 
if the data passed is a string (mine contained a space and hyphen), I just enclosed in single-quotes

`<livewire:mycomponent :my_param="my sample-data" />`

changed to

`<livewire:mycomponent :myParam="'my sample-data'" />`
