### ISSUE TITLE
Set wire:model value on suggestion click?

### ISSUE THREAD

**Issue by sukhcha-in** [livewire/livewire#2742] opened 2021-04-20 12:55 UTC
I have `input` field with model named `item`, now below I have some suggestions like `Burger` and `Pizza`, The question is how can I set value of model when suggestion is clicked?
```
<div class="flex flex-col">
    <small>Item Name</small>
    <input class="bg-white px-2 w-full border-gray-200 rounded disabled:opacity-50" type="text" placeholder="Name of item" wire:model="item">
    <div class="flex flex-wrap text-xs font-bold gap-2 mt-1">
        <a class="bg-indigo-500 text-white px-2 py-1 rounded-full cursor-pointer" wire:click="???">Burger</a>
        <a class="bg-indigo-500 text-white px-2 py-1 rounded-full cursor-pointer" wire:click="???">Pizza</a>
    </div>
</div>
```

**Comment by calebporzio** [comment] 2021-04-20 13:17
Thanks for submitting, but this is a question, not a bug, so I'm going to close it all I see you already have a discussion on it open. Thanks!

**Comment by squishythejellyfish** [comment] 2021-04-20 13:17
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed** 2021-04-20 13:17 UTC

**Comment by sukhcha-in** [comment] 2021-04-20 14:47
> Thanks for submitting, but this is a question, not a bug, so I'm going to close it all I see you already have a discussion on it open. Thanks!

Sorry for that, Is there a solution for my case? Please answer that need asap! :(
