### ISSUE TITLE
why laravel-livewire.com Boycotted our country?

### ISSUE THREAD

**Issue by MahdiPishguy** [livewire/livewire#2770] opened 2021-04-26 08:27 UTC
when i try to visit `laravel-livewire.com` website it doesn't available for us without `proxy` or `vpn`. if this package is `opensource` why this action happened?

we like to use this package of laravel and we wondering why we should use `proxy` or `vpn`?

**Comment by calebporzio** [comment] 2021-04-26 13:57
What country? I host the site using digital ocean servers. I have no idea why you're experiencing that. Very odd, and certainly not intentional.

**Comment by squishythejellyfish** [comment] 2021-04-26 13:57
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment] 2021-04-26 13:58
Closing this as not a bug in livewire. Please carry this on in a "Discussion"

**Closed by squishythejellyfish** 2021-04-26 13:57 UTC

**Comment by MahdiPishguy** [comment] 2021-04-26 15:25
@calebporzio 

> What country? I host the site using digital ocean servers. I have no idea why you're experiencing that. Very odd, and certainly not intentional.

Iran
