### ISSUE TITLE
Test validation with assertHasErrors fails when using more than one key value pairs

### ISSUE THREAD

**Issue by Pen-y-Fan** [livewire/livewire#490] opened 2019-12-24 15:54 UTC
**Describe the bug**

I've been running through the form validation example on https://laravel-livewire.com/docs/input-validation/ when using the example with key-value pairs:

```php
        ->assertHasErrors([
            'name' => 'required',
            'email' => 'required',
        ]);
`````

The test fails with an error **ErrorException : Undefined index: name**

**To Reproduce**

Follow the example https://laravel-livewire.com/docs/input-validation/

New Laravel 6.9 install with livewire 0.5.2

1. Create a ContactForm.php and contact-form.blade.php as per the example using `php artisan make:livewire contact-form`
2. Create a test **name_and_email_fields_are_required_for_saving_a_contact()** as per the second example (with key => value pairs to be validated.
3. Create a route to contact-form
4. Create a contact-form\index.blade.php which has @livewireAssets and @livewire('contact-form')
3. Run the test
4. See error **ErrorException : Undefined index: name**

**Expected behavior**

The test should pass.

If the webpage is viewed (e.g. localhost/contact-view) the form does behave as expected.

**Desktop (please complete the following information):**

- Chrome (workes as expected)

**Additional context**

I am doubting myself, as the example given in the documentation should work. I'm unable to find any other reports of this failure in the forum or as a Github issue. My guess is as the example contains `Contact::create($validatedData);`, they expected it to fail as they hadn't created a database with a contacts table.

I actually change the example I my test project to `Log::info('Created - name: ' . $this->name . ' email: ' . $this->email);` so I could view the log file created in storage/logs/laravel.log

I also reset the form after each successful submission, it may be worth updating the examples?

```php
        $this->name = "";
        $this->email = "";
```

Taking on board Cal's comments, in his excellent Podcasts, about many issues, but few PRs,  I have managed to get the test to pass by modifying the MakeAssertions trait' assertHasErrors method. the problem is `array_keys($this->lastValidator->failed()[$key]);` returns the lastValidator, so in this example it is 'email', therefore the 'name' index is undefined. This can be confirmed by only passing one rule (e.g. comment out 'email' => 'required',).  I have modified a few other lines to make it easier for me to understand (there were too many rule/rules to know which rule was which).  Also, assertContains is depreciated in PHPUnit 9, so I updated to assertStringContainsString, as per the notice. I hope this makes sense and easier to read:

```php
    public function assertHasErrors($keys = [])
    {
        $errors = new MessageBag($this->errorBag ?: []);

        PHPUnit::assertTrue($errors->isNotEmpty(), 'Component has no errors.');

        $keys = (array) $keys;

        foreach ($keys as $key => $value) {
            if (is_int($key)) {
                PHPUnit::assertTrue($errors->has($value), "Component missing error: $value");
            } else {
                // $rules = array_keys($this->lastValidator->failed()[$key]);
                $errorMessages = $errors->messages()[$key];

               // $lowerCaseRules = array_map('strtolower', $rules);
                $lowerCaseErrorMessages = strtolower(implode(" ",$errorMessages));

                foreach ((array) $value as $rule) {
                    // PHPUnit::assertContains($rule, $lowerCaseRules, "Component has no [{$rule}] errors for [{$key}] attribute.");
                    PHPUnit::assertStringContainsString($rule, $lowerCaseErrorMessages, "Component has no [{$rule}] errors for [{$key}] attribute.");
                }
            }
        }
```

There should be a try-catch block around the `$errorMessages = $errors->messages()[$key];`, if the above is used with an undefined key e.g. 'contact' it will throw `ErrorException : Undefined index: contact` 

I have as only written a small number of tests I don't know what the effect of changing this trait will be. Therefore before I do a PR, can someone validate my findings and run other tests?

Feel free to assign the fix to me.

Edit: Corrected code block.

**Comment by Pen-y-Fan** [comment] 2019-12-24 18:53
If it helps, I have uploaded my example project to my repo: <https://github.com/Pen-y-Fan/Livewire-Examples>, currently all the tests pass, as I have commented out `'email' => 'required'` in the test, see https://github.com/Pen-y-Fan/Livewire-Examples/blob/master/tests/Unit/ContactFormTest.php, if the line is uncommented the test will fail.

**Comment by Pen-y-Fan** [comment] 2019-12-24 18:59
Sorry, I click the wrong button :worried:

**Comment by Pen-y-Fan** [comment] 2020-01-24 20:59
I've created a pull request #559, this is an interim step. I am going around in circles on this one! The tests in the livewire app are passing, so should give some confidence. However, if I copy the **MakesAssertions.php** file to a working Laravel app with livewire v0.7.0, using the example on [Form Validation](https://laravel-livewire.com/docs/input-validation/) see [my implementation example here](https://github.com/Pen-y-Fan/Livewire-Examples/blob/master/tests/Unit/ContactFormTest.php), when using the example with key-value pairs it still doesn't work :( 

```text
Component has no errors.
Failed asserting that false is true.
````

Please can someone take a look at this, as I'm struggling to figure it out?

**Comment by redgluten** [comment] 2020-05-14 08:42
Adding to cents here since I struggled with validating a `not_in` rule today: it seems the current code should use `Str::slug` instead of `strtolower` so that rules names with more than one word behave correctly. Otherwise you won’t see the error key in your test despite using the proper validation name.

You can reproduce this by trying to test some validation error for something like `not_in:Foo,Bar` and then using `Livewire::test(SomeComponent::class)->set('some_key', 'Foo')->call('submit')->assertHasErrors(['some_key' => 'not_in'])`. This will fail but `->assertHasErrors(['title' => 'notin'])` will pass.

I might be over my head since I only recently begun to use Livewire and this seems to be the most relevant place to discuss this. If you want me to open a new issue for it, I’ll happily do it. 

Also I think this `assertHasErrors` could provide some more useful message when the tested validation key hasn’t been found but others were. If the maintainers can confirm this is indeed a bug I could also submit a P.R for that.

**Comment by calebporzio** [comment] 2020-06-23 18:50
Good catch @redgluten, this has been addressed in a previous release:
![image](https://user-images.githubusercontent.com/3670578/85444817-ba947200-b560-11ea-8154-4e0a8afff7da.png)

@Pen-y-Fan, I'm going to close this as it's hard for me to follow and reproduce. Please re-open with the simplest, copy-pastable representation of this problem if it still persists.

Thank you.

**Closed by calebporzio** 2020-06-23 18:50 UTC
