### ISSUE TITLE
404 for livewire.js when not using php artisan serve

### ISSUE THREAD

**Issue by 2kodes** [livewire/livewire#84] opened 2019-07-29 10:02 UTC
**Describe the bug**
I have the counter livewire example app  being served from the htdocs folder of my local xampp.
When I access the app I get a 404 for the livewire.js file. 
However when I use use `php artisan serve` to serve the app and access it the livewire.js is served correctly

**To Reproduce**
1. Create a new laravel app.
2. Install livewire in it
3. Serve or run it with a normal web server instead of `php artisan serve`
4. See error in the network tabs of the browser

**Expected behavior**
Expected the path to the livewire.js file to be resolved correctly no matter where itsa being served from

**Screenshots**

**Error when served from localhost with a webserver**

![liveiwire-2](https://user-images.githubusercontent.com/2084398/62039617-95c83b00-b1e7-11e9-8b44-5d819bfe65a9.png)

**Loaded correctly when served with `php artisan serve`**

![liveiwire-3](https://user-images.githubusercontent.com/2084398/62039682-abd5fb80-b1e7-11e9-9725-4c41a9bf3254.png)

**Desktop (please complete the following information):**
 - Browser - chrome

**Comment by lancepioch** [comment] 2019-07-30 21:01
I have this running with Apache just fine

**Comment by calebporzio** [comment] 2019-07-31 13:14
This has been addressed in the latest release: v0.1.1

**Comment by 2kodes** [comment] 2019-07-31 16:12
@calebporzio ... sweet..will test and feedback..thanks

**Comment by Krato** [comment] 2019-08-31 10:13
Is giving me same error. Using artisan works fine.

Using a domain with vhost in my local, gives me a 404 NOt found. Route is registered but no working. :(

**Comment by robsontenorio** [comment] 2019-09-25 02:13
In my case i just run my localhost on 8080.
I can confirm. Error 404.

**Comment by robsontenorio** [comment] 2019-09-25 02:32
Just notice when publishing config files it works:

```
php artisan vendor:publish --tag=livewire:assets
```

According docs this **is not** mandatory.

**Comment by faustbrian** [comment] 2019-12-13 10:40
@robsontenorio is this still an issue?

**Comment by lancepioch** [comment] 2019-12-15 19:54
I tested this with Apache and this is not an issue. (same setup from [here](https://github.com/livewire/livewire/issues/243#issuecomment-565830288))

My guess is that OP is having issues because of using subdirectories in their url `/public/` instead of pointing the root path to the public directory itself.

I believe this can be closed.

**Comment by calebporzio** [comment] 2019-12-17 19:19
Closing this for now, thanks @faustbrian and @lancepioch for digging in and resolving.

**Closed by calebporzio** 2019-12-17 19:19 UTC

**Comment by RafaTorices** [comment] 2020-10-14 10:02
This not work for me. I have error 404, 
how can i solve it?
thanks !! 
I'm desperate

**Comment by we-pe** [comment] 2020-11-02 14:45
@RafaTorices try run: `php artisan livewire:publish`
then open **config/livewire.php** 
change `'asset_url'  => null` to `'asset_url'  => 'http://localhost/laravel8/public'`

**Comment by RafaTorices** [comment] 2020-11-03 08:32
thank you very much for your answer but this doesn't work either

I don't know what to do anymore


*Rafael Torices*
------------------------------

E-mail: torices.rafael@gmail.com

*ADVERTENCIA LEGAL*
La información incluida en este e-mail es CONFIDENCIAL, siendo para uso
exclusivo del destinatario arriba mencionado. Si Usted lee este mensaje y
no es el destinatario indicado, le informamos que está totalmente prohibida
cualquier utilización, divulgación, distribución y/o reproducción de esta
comunicación, total o parcial, sin autorización expresa en virtud de la
legislación vigente. Si ha recibido este mensaje por error, le rogamos nos
lo notifique inmediatamente por esta misma vía y proceda a su eliminación
junto con sus ficheros anexos sin leerlo ni grabarlo.
------------------------------

Antes de imprimir este correo electrónico piense bien si es necesario
hacerlo: el medio ambiente es cosa de todos.

**Comment by we-pe** [comment] 2020-11-03 14:25
okay, let's try once again with follow this steps
1. install laravel with jetstream livewire normally (until step `php artisan migrate`)
2. register 1 new user through `http://localhost/laravel8/public/register`
3. run `php artisan vendor:publish --tag=jetstream-views`
4. run `php artisan livewire:publish --assets`
5. run `php artisan livewire:publish`
6. open **config/livewire.php** change `'asset_url' => null` to `'asset_url' => 'http://localhost/laravel8/public'`

I to do that and everything running well without artisan serve

**Comment by RafaTorices** [comment] 2020-11-04 08:31
Impossible, I have followed steps as you indicate me and it does not work either, it's very strange

**Comment by LoongGx** [comment] 2021-03-23 00:15
> @RafaTorices try run: `php artisan livewire:publish`
> then open **config/livewire.php**
> change `'asset_url' => null` to `'asset_url' => 'http://localhost/laravel8/public'`

thanks, solve my issue by following this

**Comment by RafaTorices** [comment] 2021-10-15 06:31
it has not been solved for me

**Comment by FZH2001** [comment] 2022-07-21 23:58
@RafaTorices did you find the solutions ,im struggling with the same issue

**Comment by halocedark** [comment] 2022-11-15 21:23
me too, it keeps displaying 404 not found error.
my livewire components fetches data with no issues, but whenever I try to interact with component it show error 404, I'm using apache server on subdomain

**Comment by AAUU-Ansari** [comment] 2024-05-08 09:27
I have the same problem with Livewire 3 in Laravel 10

changed the config/Livewire.php file
'asset_url'  => 'http://localhost/acc/me2/public',

but still facing the issue 
GET http://localhost/acc/me2/public/ net::ERR_ABORTED 403 (Forbidden)

**Comment by Muniraj25** [comment] 2024-05-23 09:25
I have followed all steps i got this error..
﻿
Uncaught SyntaxError: Unexpected token '<' (at public:3:1)
