### ISSUE TITLE
`app()` helper breaks after re-render

### ISSUE THREAD

**Issue by Larsklopstra** [livewire/livewire#1405] opened 2020-08-22 15:17 UTC
## Updated

[GitHub repository with bug](https://github.com/Larsklopstra/livewire-bug)

**Here's a repository where you can see it in action, simply type in the "Hello world" input and you'll see an error modal appear.**

The files you'll be looking at are:

- web.php
- ExampleComponent.php
- SetAppInstanceExample.php
- example-component.blade.php

---

### Description

The application breaks if you're trying to use the `app()` helper in your template

**Error**

```php
Illuminate\Contracts\Container\BindingResolutionException
Target class [organisation] does not exist.
```

**Blade**
```php
<x-slot name="title">
  Create workspace in {{ app('organisation')->name }}
</x-slot>
```

### Steps to reproduce

1. `app()->instance('organisation', $organisation);` create an instance with your model.
2. Display it in your template like shown above
3. Write in a text input which is bound to a livewire model

**Context**
- Livewire version: [^1.3]
- Laravel version: [^7.24]
- Browser: [Microsoft Edge]

**Comment by Larsklopstra** [comment] 2020-08-28 10:28
@nuernbergerA I'll make an example repository :)

**Comment by Larsklopstra** [comment] 2020-08-28 10:50
@nuernbergerA added the repository

**Comment by austenc** [comment] 2020-10-16 04:29
@Larsklopstra thank you for the repo, it made reproducing this much faster!

This is happening because you are binding the object to the container in a middleware instead of in a server provider or somewhere else. So it works for the first request (to the `/` route), but the middleware is not applied for subsequent requests that Livewire makes. 

If you look at chrome's network tab, you'll see the URL for those is different. 
![image](https://user-images.githubusercontent.com/575421/96213016-40379580-0f35-11eb-84dc-7305f33074bc.png)

**There are a few ways you might consider solving this:**
- Apply the middleware as a global `web` middleware in `App\Http\Kernel`
- Bind the object to the service container elsewhere, such as a service provider

**Comment by calebporzio** [comment] 2020-10-16 14:07
Thanks @austenc ! Closing

**Closed by calebporzio** 2020-10-16 14:07 UTC
