### ISSUE TITLE
Embedded Components DOM Diff Issue

### ISSUE THREAD

**Issue by intellow** [livewire/livewire#328] opened 2019-10-10 14:09 UTC
I have nested components in my site and they don't work very well together.

Steps to Reproduce:
Go to laravelstl.com/login and use test@laravelstl.com / password
Go to laravelstl.com/events
Click the button to "Hide Unscheduled Events", then click it again to unhide

Results:
You can no longer click that button anymore, and the site is now missing some content. At this point, livewire is no longer recognizing any clicks on any of the filter buttons.

Expected Behavior:
It should just unhide the Unscheduled Events

If I remove the nested `@livewire('event', $event, key($event->id))` then the filters continue to be interactive, so there must be something with the nesting that is causing a problem.

This is an open source site, so feel free to pull it down to see for yourself, or I'm happy to do a pairing session.

https://github.com/intellow/laravelstl

**Comment by cbaconnier** [comment] 2019-10-11 18:51
I'm not familiar with `key()` but I don't think it belongs there. What are you trying to do with?

**Comment by intellow** [comment] 2019-10-11 20:08
The key is there as stated in the nested components section of the docs. If I remove it it doesn’t change the behavior. 

https://laravel-livewire.com/docs/nesting-components/

**Comment by calebporzio** [comment] 2019-10-13 14:55
I see an error in the console when I follow those steps:

![image](https://user-images.githubusercontent.com/3670578/66717507-d62b6400-eda7-11e9-8052-1fcf5f84ec4b.png)

See if that has anything to do with an SVG in the DOM or something else like that? If not, I'll dig in when I get a chance.

**Comment by marksalmon** [comment] 2019-10-13 15:10
Hey,

I had this exact same problem today. Turns out it was related to having the
a wire:modelled select input inside nested components. I was able to solve
the problem by giving each one a unique name:



Hope this helps

Mark



On 13 October 2019 at 15:55:06, Caleb Porzio (notifications@github.com)
wrote:

I see an error in the console when I follow those steps:

[image: image]
<https://user-images.githubusercontent.com/3670578/66717507-d62b6400-eda7-11e9-8052-1fcf5f84ec4b.png>

See if that has anything to do with an SVG in the DOM or something else
like that? If not, I'll dig in when I get a chance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/livewire/livewire/issues/328?email_source=notifications&email_token=ABVNGNRA2LKPIBI72HJ25LDQOMZETA5CNFSM4I7NPFKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBCX4EI#issuecomment-541425169>,
or unsubscribe

**Comment by calebporzio** [comment] 2019-10-14 19:22
Hey @marksalmon, thanks for pitching in. Would you be able to post a simple code snippet for me to reproduce? Can just be pseudo-code if need-be

**Comment by intellow** [comment] 2019-10-15 02:22
> I see an error in the console when I follow those steps:
> 
> ![image](https://user-images.githubusercontent.com/3670578/66717507-d62b6400-eda7-11e9-8052-1fcf5f84ec4b.png)
> 
> See if that has anything to do with an SVG in the DOM or something else like that? If not, I'll dig in when I get a chance.

There are SVGs on the page, but none inside of either livewire component.

**Comment by marksalmon** [comment] 2019-10-15 17:37
Hi @calebporzio,

I don't think I can do a simple code snippet because the problem comes from a complex component that can be nested inside itself. I am building a 'query builder' to use in conjunction with my Livewire Datatable and therefore have a concept of a `query-group` that itself can contain `rules` or further `query-groups`

So I have created a repo to demo this issue: 

https://github.com/marksalmon/livewire-error-demo

You should be able to clone this and run it, there is no DB or anything. There are 2 endpoints:
- '/' has the working components (with `name="{{ \Str::random(16) }}"` on the select)
- '/without' has the component that causes the error (without `name="{{ \Str::random(16) }}"` on the select)

Hope this helps

M

**Comment by calebporzio** [comment] 2019-10-25 09:05
Hey @marksalmon, thanks for making this easy for me. Unfortunately, the "without" page for me works fine. No console errors, and here is my usage:

![image](https://user-images.githubusercontent.com/3670578/67558447-51313a80-f717-11e9-8a3d-6e3b8727fa53.png)

Am I missing something, or is this a case of "works on my machine"

**Comment by marksalmon** [comment] 2019-10-25 14:04
The plot thickens.

I just tried again using incognito chrome (Version 77.0.3865.120 (Official Build) (64-bit)) and I still get the error
![image](https://user-images.githubusercontent.com/7000886/67576300-36ba8980-f736-11e9-9a54-34ec7cbdca0c.png)

In firefox I get a different error on adding nested groups, but the component does appear to continue to function
![image](https://user-images.githubusercontent.com/7000886/67577505-7edaab80-f738-11e9-95fa-4b9171e5b367.png)


I don't know how else to debug this. I have tried removing chrome extensions etc as things that might be different to your setup but beyond that I'm stumped. That was a clean laravel install, running valet on a macbook. All default. 

Side note: weird that in your screenshots the value inputs appear empty, that doesn't happen on my version.

**Comment by intellow** [comment] 2019-11-08 22:27
My specific issue is fixed by removing `wire:model="score"` from the div, which shouldn't have been there anyway, but I spoke with Caleb and there is an underlying issue that he is looking into. Will close this one when that is resolved.

**Comment by calebporzio** [comment] 2019-11-11 14:54
@intellow (and everyone else). This should be fixed in `dev-master` (the master branch). 

Mind pulling it down and testing it in your project before I tag it? (there's a pretty big refactor that just makes me nervous to tag without others confirming it's good)

Thanks!

**Comment by intellow** [comment] 2019-11-11 15:43
I just updated to dev-master and when I tried to load my page to test, I am got this error: 
```Object of class Illuminate\Support\Fluent could not be converted to string (View: /Users/kevinmckee/Code/laravelstl/resources/views/livewire/events.blade.php)```

running `php artisan view:clear` fixed that.

After that, everything is running beautifully. I tested every aspect of our livewire implementation on the page and it's all working as expected. :+1:

**Comment by calebporzio** [comment] 2019-11-11 16:11
Perfect, thanks @intellow 

I just paired with @marksalmon - and the `dev-master` branch fixed all his issues.

I'll tag the release now.

**Closed** 2019-11-11 16:11 UTC
