### ISSUE TITLE
Autofill in Safari does not work

### ISSUE THREAD

**Issue by redbastie** [livewire/livewire#1519] opened 2020-09-10 03:19 UTC
Using autofill in Safari does not update the models in the component.

It fills out the form, sure, but Livewire fails to pick up the values.

**Comment by jimpeters** [comment] 2020-09-14 05:18
I don't think Safari is triggering a change event when you auto fill.  This is probably out of scope for Livewire to deal with.  Maybe this thread will provide some guidance.

[https://github.com/vuejs/vue/issues/7058](url)

**Comment by redbastie** [comment] 2020-09-14 08:02
@jimpeters whats odd is that the laravel jet stream login component does not have issues with safari auto fill. I’m going to look into it and see what workaround they did.

**Comment by dubcanada** [comment] 2020-09-14 14:18
There is already a thread about this https://github.com/livewire/livewire/issues/1081 maybe check there to see if that solves the issue.

**Comment by nuernbergerA** [comment] 2020-09-14 15:31
Hey, @redbastie 

please post a domain-free code example that's easy to copy and paste to reproduce your issue.

Thanks!

**Comment by redbastie** [comment] 2020-09-15 13:53
Open up Safari.

Go here: https://laravelplayground.com/#/snippets/350d5f68-ab64-492f-a599-76f924a18278

Enter an email & password, then click "login". You will see the dump of the `$output` variable is accurate.

When Safari prompts, save the email & password.

Now focus the email input, have Safari autofill the fields, then click "login". You will see the `$output` dump contains an array with 2 empty values.

**Comment by redbastie** [comment] 2020-09-15 15:45
OK check this out, this works:

	<div>
	    <form>
	        <input type="email" placeholder="Email" wire:model.defer="state.email">
	        <input type="password" placeholder="Password" wire:model.defer="state.password">
	        <button type="submit">Submit</button>
	    </form>

	    {{ print_r($state, true) }}
	</div>

	@push('scripts')
	    <script>
	        $('form').submit(function (event) {
	            event.preventDefault();

	            $(':-webkit-autofill').each(function () {
	                @this.set($(this).attr('wire:model.defer'), $(this).val());
	            });

	            @this.call('submit');
	        });
	    </script>
	@endpush

I'm using jQuery but I'm sure it can be translated into vanilla JS or whatever.

All we have to do is add `:webkit-autofill` checks when an action is made, then wire it accordingly if it is null, no?

**Comment by glaesser** [comment] 2020-09-21 15:01
This is an issue especially in mobile safari (iOS), was really hoping v2 would've fixed this glaring issue...!

**Comment by brenjt** [comment] 2020-09-22 16:22
Looks like someone might have found a solution for this #1661

**Comment by redbastie** [comment] 2020-09-22 21:54
> Looks like someone might have found a solution for this #1661

Yeah, me :P

**Comment by redbastie** [comment] 2020-09-25 19:09
PR that fixes the bug with IE11 support: https://github.com/livewire/livewire/pull/1696

**Comment by calebporzio** [comment] 2020-09-29 15:08
Safari autofill should be fixed in 2.2.8

Please run php artisan view:clear, update Livewire, and report here if the problem is fixed, otherwise, re-submit please.

Thanks everyone!

**Comment by f-liva** [comment] 2021-02-22 15:52
Still present in 2.3.18

**Comment by jevail** [comment] 2021-03-15 12:23
Still present in 2.4

**Comment by sytheveenje** [comment] 2021-04-20 07:31
I can confirm that it's still present in 2.4.3 as well

**Comment by zepfietje** [comment] 2021-04-23 14:48
I'm also running into this using the latest Livewire version.

**Comment by Liam-PVTL** [comment] 2021-05-08 09:01
I'm also running into this problem, bump!

**Comment by Liamso** [comment] 2021-05-08 09:02
I'm also running into this problem, bump!

Edit; Just because it can seem like people come to you with more problems (issues) than compliments & I feel that I need to balance that out a bit with my pump - thank you so much for the package Caleb :)

**Comment by calebporzio** [comment] 2021-05-08 13:50
Thanks @Liamso , very encouraging to hear!

**Comment by Liamso** [comment] 2021-05-09 00:33
Upgrading to 2.4.4 and running `php artisan view:clear` seems to have solved the issue

**Comment by zepfietje** [comment] 2021-05-24 10:05
@Liamso, not sure if you're talking about this exact issue.
I've tried running `php artisan view:clear` and the bug is still present in Livewire 2.4.4.

**Comment by ahinkle** [comment] 2021-05-27 02:07
Same here - it was once fixed but now the issue has come back 😞 

Will try to pinpoint which version caused the issue.

**Comment by ahinkle** [comment] 2021-05-27 02:20
I'm having an issue where it doesn't fill multiple autofill fields (filling in a full address for example), but it does work on single 1 to 1 autofill fields.

Example:
Working 1 to 1: Phone number field - autofills the phone number saved in safari

Not working: 

Saved address:  123 main st new york ny

Fields: 
Address
City
State

When selected, it flashes and removes the values.

**Comment by mokrusoft** [comment] 2021-06-05 21:07
I had the same issue with autofill and a workaround I found was replacing `wire:model` with `x-model` (AlpineJS) using `@entangle`
`<input x-data="{email: @entangle('email')}"	x-model="email"/>`

**Closed** 2021-06-19 17:10 UTC
