### ISSUE TITLE
AuthorizeRequests exceptions not handled by assertForbidden

### ISSUE THREAD

**Issue by tiago-sb** [livewire/livewire#837] opened 2020-04-20 13:16 UTC
**Describe the bug**
`$this->authorize(..) `throws an AuthorizationException that is not catched by the `assertForbidden() `methods

**To Reproduce**

component:

```php
use App\Http\Livewire\LivewireComponent;
use App\Modules\Actions\Models\ModelAction;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class ListEntry extends LivewireComponent
{
    use AuthorizesRequests;

    public $modelAction;

    public function mount(ModelAction $modelAction)
    {
        $this->modelAction = $modelAction;

        $this->authorize('view', $this->modelAction);
    }

    public function render()
    {
        return view(....);
    }
}
```

test:

```php
/** @test */
    public function user_cannot_see_action_details()
    {
        $modelAction = $this->newModelAction();

        // actAs a user withOUT proper permissions
        $this->asUser();

        Livewire::test(ListEntry::class, ['modelAction' => $modelAction])
            ->assertForbidden();
    }
```

this test outputs:
```

There was 1 error:

1) Tests\Feature\Actions\ActionsControllerShowTest::user_cannot_see_action_details
ErrorException: This action is unauthorized. (View: ...
[...]
Caused by
Illuminate\Auth\Access\AuthorizationException: This action is unauthorized.
[...]

```

Looking at the `assertForbidden()` code, it expects an `HttpException`, however this is not the type that is thrown.
We can argue that technically it is not a bug since the `assertForbidden` confirms an `HttpException` with code 403, however it does not handle such case, which is the one exampled in the documentation.
More, is there a real scenario where an `HttpException` is actually thrown inside a livewire component (except if we do it manually, of course?)

Maybe I'm missing something and should be testing this differently....

**Expected behavior**
`assertForbidden()` handles `AuthorizationException`

**Comment by DanHarrin** [comment] 2020-04-22 07:18
Potentially fixed by #843.

**Comment by devcircus** [comment] 2020-04-22 07:22
I noticed the authorization exception works as expected if used within an action. Just not when used in "render" or "mount".  Dont know if that even matters, just pointing it out.

**Comment by DanHarrin** [comment] 2020-04-22 07:25
@devcircus not being able to cleanly throw on `mount()` is a massive issue, ends up being a big limitation to SPA components, which I've had to workaround in the past.

**Comment by devcircus** [comment] 2020-04-22 07:27
Definitely. Just curious why it would work in an action and not render. What is different about the functionality in that case.

**Comment by DanHarrin** [comment] 2020-04-22 07:33
@devcircus it's caused by the fact that the Blade compiler that runs on first page load wraps them in an `ErrorException` which causes the 500. The Blade compiler is not used in this way when an action is called.

**Comment by tiago-sb** [comment] 2020-04-22 09:24
> Potentially fixed by #843.

Thanks for the fix, @DanHarrin ! So, if I understood correctly this will allow `authorize` to be called anywhere in the component, correct?

**Comment by DanHarrin** [comment] 2020-04-22 09:26
@tiago-sb yes that should be the case, it'll now return a clean 403 instead of it being wrapped in a 500 `ErrorException`.

**Comment by devcircus** [comment] 2020-04-22 14:11
Ah. Are there any other exceptions affected by this that may need to be fixed?

**Comment by calebporzio** [comment] 2020-04-22 14:28
Thanks for the fix, I'll try to get this merged later today.

**Comment by DanHarrin** [comment] 2020-04-22 15:30
@tiago-sb my PR has now been merged, pull in the `dev-master` version of the package and see if your issue is fixed.

**Comment by DanHarrin** [comment] 2020-04-22 15:31
If not, I can work on a fix if you don't have time.

**Comment by tiago-sb** [comment] 2020-04-22 16:09
Hi @DanHarrin it worked perfectly for the scenario of the first post, but then I started getting this undefined index error in other tests:

```
1) Tests\Feature\Requests\RequestsCreateTest::user_with_permission_cannot_create_request_for_another_clients_contract
ErrorException: Undefined index: id

[...]/site_blade/vendor/livewire/livewire/src/Testing/TestableLivewire.php:102
```

Gonna dig a bit deeper and try to see when/why it happens and how to reproduce it in the simplest way possible.

**Comment by DanHarrin** [comment] 2020-04-22 16:20
Were those tests previously clear of issues?

**Comment by tiago-sb** [comment] 2020-04-22 16:20
@DanHarrin 

Ok, so the issue is with my test: the assertForbidden() needs to be called right after the failing function (create, set, call).

This won't work since the exception is thrown in the `test()` call:

```php
Livewire::test(CreateForm::class, ['contract' => $anotherContract])
    ->set('type', RequestType::all()->random()->id)
    ->assertForbidden();
```

This works:
```php
Livewire::test(CreateForm::class, ['contract' => $anotherContract])
    ->assertForbidden();
```

All seems ok to me with the PR 👍
...and thanks for the quick fix!!

Can be closed.

**Comment by tiago-sb** [comment] 2020-04-22 16:35
One suggestion if it makes sense:
in the example of my previous post that does not work, it would be great if any call to `set()` to or `call()` would throw any previous handled exception, instead of actually calling the method.

Without this, calling for example `set()` will throw an exception like the one I had (undefined index) and would masquerade the real one.

**Comment by DanHarrin** [comment] 2020-04-22 16:39
I kinda disagree, I'd like to prioritise my test being written correctly as without it the component may be returning a false positive, if it's not set up correctly. I see the frustration though :)

**Comment by tiago-sb** [comment] 2020-04-22 16:55
hmm, (maybe a discussion for another forum...but) really think it should handle this differently.
Take this scenario

```php
Livewire::test(CreateForm::class)
    ->set('type', 1)
    ->call('create');
```

and let's say that the `set()` call throws an `AuthorizationException`.

I don't think the `call()` method should be executed, I mean, an exception just happened., but still what we will have is an attempt to execute it and then another unrelated exception is thrown because of some inconsistency (caused by the previous exception, yes) in livewire internals (TestableLivewire:101 - $this->payload is empty - to be more precise).

The developer would then need to debug and see that it is actually the `set() `that in throwing an exception, while he/she could have seen that exception in the phpunit output..

My suggestion is to, in this scenario, when calling call('create') and exception saying something like: 
"Cannot call '$namel' method with '$params' since a previous exception was thrown: $previousException"

or print something like what we already have with ErrorExceptions where we can see the 'Caused by':
```
1) Tests\Feature\Actions\ActionsControllerShowTest::user_cannot_see_action_details
ErrorException: This action is unauthorized. (View: ...
[...]
**Caused by**
Illuminate\Auth\Access\AuthorizationException: This action is unauthorized.
[...]
```

Anyway, as I said, it is an improvement suggestion.

Thanks again !!

**Comment by nuernbergerA** [comment] 2020-06-27 16:34
Hey @tiago-sb 

since the initial issue is fixed I will close this, feel free to open a new issue/feature request if needed.

**Closed by nuernbergerA** 2020-06-27 16:34 UTC
