### ISSUE TITLE
Loading state not working on $emit

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#183] opened 2019-08-22 12:59 UTC
**Describe the bug**
I am not sure if this is a bug or intended behavior.

I am emitting an event on `wire:click`, like below and expecting the loading message to appear:

```html
<div wire:click="$emit('showModal')">Show Modal</div>
<div wire:loading>
    Loading modal...
</div>
```

However, when I click on the Show Modal, the loading message "Loading Modal..." does not appear.

If I don't use the `$emit` method with the `wire:click`, but call the method directly:

```html
<div wire:click='showModal'>Show Modal</div>
```

Then the loading message will appear.

**Comment by calebporzio** [comment] 2019-08-22 14:12
Yeah, It's kind of intended behavior.

Right now, events aren't scoped to a component, so calling `$emit()` directly as an action will emit to all components on the page. Because there's no way of knowing who is listening for the emit and when they are finished, `wire:loading` doesn't really make sense here.

Make sense?

If you see a logical way this should behave, I'm open to hearing it and brainstorming solutions.

**Comment by oliverbj** [comment] 2019-08-28 06:53
This makes sense, thanks for pointing it out! I am not sure if it's possible, just thinking out loud.. But maybe it's possible to append a key to the `$emit()`, so we can listen for that key in the loading component?

Something like:

```
<div wire:click="$emit('showModal', ['loadingRef' => 'myLoader')">Show Modal</div>
<div wire:loading wire.emit.target='myLoader'>
    Loading modal...
</div>
```

Not sure if this is possible, or is even a feature that's wanted in Livewire.

**Comment by calebporzio** [comment] 2020-03-14 16:44
Closing this for now.

**Closed by calebporzio** 2020-03-14 16:44 UTC
Labels: Type: Enhancement

**Comment by farhanianz** [comment] 2020-10-05 04:54
So it's the intended behaviour & I was going mad thinking a way to solve it. 

Here's what I'm doing (v2)
```blade
    @foreach($items as $item)
         <button x-on:click="$dispatch('open-that', '{ id: {{$item->id}}')">Open that to view</button>
    @endforeach
    <livewire:open-that />
```
open that component:

```blade
    <div id="this-is-what-should-be-opened" x-data="{show:false}" x-on:open-that.window="show=true">
        <div wire:loading.class="loading" wire:target="myAwesomeId"></div>
        <div x-on:open-that.window="$wire.myAwesomeId = $event.detail.id"></div>

         Hey! I was expecting it to be working. I wanted a loader when I changed the attribute via events.
         Any solution/alternative/workaround for this?
    </div>
```

**Comment by metavin007** [comment] 2021-12-14 15:54
in view
<div wire:click="go_showModal()">Show Modal</div>
<div wire:loading>
    Loading modal...
</div>

in companant
    public function go_showModal() {
        $this->emit('showModal');
    }

**Comment by michelvermeulen** [comment] 2022-03-25 09:11
Hey guys. Having the same issues and I can't wrap my head around it. I have a component for a comment form, another one for the comment list, and I want to show a loader only when the list is being refreshed after a new comment is posted (but not when something else in the list happens, like deleting one comment).

I have the following:

`<img wire:loading.block src="/img/loader dark.svg" class="h-8 w-8 mx-auto" alt="">`

Which is triggered when any request is sent. I would like this to be triggered only when I emit the event:

`$this->emit('commentAdded');`

I tried to add wire:target="commentAdded" to the loader but then it doesn't show at all.

Not sure if there's a workaround or if I'm doing something wrong?

**Comment by kaulvimal** [comment] 2022-09-08 14:42
I am using jquery. That element that I need to show when other elements are loading, I have added d-none

```
<div class="row d-none loading_block">
  Please wait. Loading...
</div>
```

and when emitting the event, I am removing d-none class

```
$('body').on('change', '#select_customer', function(e) {
  
  Livewire.emit('setSelectedCustomer')

  $('.loading_block').removeClass('d-none');

})
```

When the page renders back with the the data, the loading element has d-none added to it and it does not show.

Hope it helps.
