### ISSUE TITLE
Redirecting to the current page with anchors

### ISSUE THREAD

**Issue by bdweix** [livewire/livewire#289] opened 2019-09-22 16:51 UTC
**Describe the bug**
Livewire redirects will not reload the current page if the route contains anchors, it will just add the anchor to the URL. For example if you are on the page `"/home"` and you return the following responses from your Livewire controller:

`return redirect('/home'); //Page properly reloads itself`

`return redirect('/home#anchor')` //Page will not reload, just appends the anchor to the url`

Notably, this only happens if you are trying to return back to the current page you are on. If you try to return a redirect to a different page with anchors, it works as intended. 

**Expected behavior**
I expect a redirect to reload the entire page, regardless if it's the same url or not (and with or without anchors). Oftentimes I have users taking actions with Livewire and when they are complete I want to reload the current page with the updates information.

Also, with the current behavior, Livewire will no longer work on a page if a controller returns a redirect and the page doesn't redirect.  

**Browser:**
I have tried in Safari, Chrome, and Firefox and get the same response.

**Comment by lancepioch** [comment] 2019-12-18 17:12
I think this is a javascript issue.

I believe I've got a solution that I'll try soon.

**Comment by lancepioch** [comment] 2020-03-17 18:16
One solution to this that you can add to your javascript:

```js
window.onhashchange = () => window.location.reload()
```

This will work perfectly for Livewire but will break any 3rd party hash change listeners.

**Comment by calebporzio** [comment] 2020-06-21 16:18
Closing this for now.

I suggest @lancepioch's suggestion if this is your desired behavior.

**Closed by calebporzio** 2020-06-21 16:18 UTC
Labels: Type: Bug

**Comment by Icrmsoftware** [comment] 2020-09-20 08:58
Because I was using turbolinks that's why I faced this issue. But you can disable turbolink for specific href like this:

<a href="/link" data-turbolinks="false">Page without Turbolinks</a>

**Comment by elephantux** [comment] 2021-02-16 18:27
The problem is still relevant. Is there a good solution?

**Comment by Tonyhh** [comment] 2022-12-13 04:31
This is definitely still an issue and makes working with pagination a nightmare

**Comment by daihop** [comment] 2025-02-22 07:42
Would be great to get full solution for this.
