### ISSUE TITLE
File Inputs: Two wire:model in same page forward data to last wire:model

### ISSUE THREAD

**Issue by mercuryseries** [livewire/livewire#1157] opened 2020-06-24 20:34 UTC
### Description

I have two wire:model on the same page:

```
<x-filepond-input wire:model="photos"></x-filepond-input>
<x-filepond-input wire:model="attachments"></x-filepond-input>
```

When uploading files, both are sync in attachments attribute of the component livewire class even if the files are uploaded through the photos filepond input.

**Context**
- Livewire version: 1.2.0
- Laravel version: 7.17.1
- Browser: Chrome

**Comment by dioumapita** [comment] 2020-06-24 21:09
Merci beaucoup monsieur je voudrait que vous faite pour nous le turbolinks
de livewire pour un faire spa svp

Le mer. 24 juin 2020 à 20:35, Honoré Hounwanou <notifications@github.com> a
écrit :

**Comment by nuernbergerA** [comment] 2020-06-27 16:44
Hey @mercuryseries please provide code to reproduce your issue

**Comment by gorelog** [comment] 2020-07-01 20:33
He may be doing something like the following:

Blade
`
<div>

    @if (is_object($photo))
        <img src="{{ $photo->temporaryUrl() }}" style="width: 100%;" alt="temp photo" />
    @elseif (is_string($photo))
        <img src="{{ Storage::disk('s3')->url($photo) }}" style="width: 100%;" alt="From S3" />
    @endif
    <div
        wire:key="photo"
        wire:ignore
        x-data
        x-init="
        FilePond.setOptions({
            server: {
                process: (fieldName, file, metadata, load, error, progress, abort, transfer, options) => {
                    @this.upload('photo', file, load, error, progress)
                },
                revert: (filename, load) => {
                    @this.removeUpload('photo', filename, load)
                },
            },
        });
        FilePond.create($refs.input);
    "
    >
        <input type="file" x-ref="input">
    </div>

    @if (is_object($foo))
        <img src="{{ $foo->temporaryUrl() }}" style="width: 100%;" alt="temp photo" />
    @elseif (is_string($foo))
        <img src="{{ Storage::disk('s3')->url($foo) }}" style="width: 100%;" alt="From S3" />
    @endif
    <div
            wire:key="foo"
            wire:ignore
            x-data
            x-init="
            FilePond.setOptions({
                server: {
                    process: (fieldName, file, metadata, load, error, progress, abort, transfer, options) => {
                        @this.upload('foo', file, load, error, progress)
                    },
                    revert: (filename, load) => {
                        @this.removeUpload('foo', filename, load)
                    },
                },
            });
            FilePond.create($refs.foo);
        "
    >
        <input type="file" x-ref="foo">
    </div>

</div>
`

Component

`
	namespace App\Http\Livewire\Filepond;
	
	use Livewire\Component;
	use Livewire\WithFileUploads;
	
	class Photo extends Component
	{
	    use WithFileUploads;
	
	    public $photo;
	    public $foo;
	
	    public function render()
	    {
	        return view('livewire.filepond.photo');
	    }
	}

`

In this example the preview uploads only to the second input foo and only the second filepod has full functionality without error as filePond is always referencing the second image, foo. Only foo is being set. Photo is always null.

**Comment by AdrianMrn** [comment] 2020-09-17 09:35
I believe I'm running into the same problem. Calling `@this.upload(…)` when there are multiple instances of the same file uploading component on one page, it always tries to upload the file for the last component on the page.

[This section in the Livewire docs](https://laravel-livewire.com/docs/2.x/file-uploads#js-api) tells us to check out the Alpinejs docs for more info on the `@this` decorator, but it isn't talked about anywhere (anymore) on [the linked page](https://laravel-livewire.com/docs/2.x/alpine-js#communicating-with-js) 😕

**Comment by calebporzio** [comment] 2020-10-21 19:34
@AdrianMrn - thanks for pointing that out. I've updated the reference in the docs to be more accurate.

I'm going to close this issue because the original poster hasn't chimed in, AND the issues others are having are potentially unrelated?

Anyhow, I'd love someone to boil down the issue they are having to a small/reproducible code snippet so others can pitch in with more clarity.

Thanks!

**Closed by calebporzio** 2020-10-21 19:34 UTC
Labels: Needs Better Reproducibility

**Comment by taufanbasri** [comment] 2020-11-18 08:58
> I believe I'm running into the same problem. When calling `@this.upload(…)` when there are multiple instances of the same file uploading component on one page, it always tries to upload the file for the last component on the page.
> 
> [This section in the Livewire docs](https://laravel-livewire.com/docs/2.x/file-uploads#js-api) tells us to check out the Alpinejs docs for more info on the `@this` decorator, but it isn't talked about anywhere (anymore) on [the linked page](https://laravel-livewire.com/docs/2.x/alpine-js#communicating-with-js) 
> 
> In Livewire 1.x.x the `@this` decorator used to return a complete overview of the current component, including which props it was passed, this doesn't seem to be the case anymore.
> 
> UPDATE: I managed to find a "fix" for this by passing `@this` as a prop in my `x-data` method. It only seems to go wrong when calling `@this` from a script tag.

Can you show the code please. I have same problem and i don't know how to fix.
thanks

**Comment by AdrianMrn** [comment] 2020-11-18 09:29
@taufanbasri 

```html
<div x-data="init(@this)"> … </div>

<script>
function init(_this) {
    function handleUploader() {
        _this.upload( … );
    }
}
</script>
```

**Comment by taufanbasri** [comment] 2020-11-18 11:29
Thanks @AdrianMrn 

Beautiful place, right? :)

**Comment by booni3** [comment] 2020-11-30 22:14
Quick fix for this here:

https://forum.laravel-livewire.com/t/two-file-pond-components-in-the-same-page/1913/2

```blade
<div
    wire:ignore
    x-data="{pond: null}"
    x-init="
        FilePond.registerPlugin(FilePondPluginImagePreview);
        pond = FilePond.create($refs.input);
        pond.setOptions({
            allowMultiple: {{ isset($attributes['multiple']) ? 'true' : 'false' }},
            labelIdle:'Veuillez sélectionner un fichier',
            labelFileProcessingComplete: 'Upload terminé',
            server: {
                process: (fieldName, file, metadata, load, error, progress, abort, transfer, options) => {
                    @this.upload('{{ $attributes['wire:model'] }}', file, load, error, progress)
                },
                revert: (filename, load) => {
                    @this.removeUpload('{{ $attributes['wire:model'] }}', filename, load)
                },
            },
        });
">
    <input type="file" name="{{$inputname}}" x-ref="input">
</div>
```

**Comment by newtek-bneff** [comment] 2023-05-24 18:24
I don't know if this is relevant, I was having the same issue with a regular file input (not using `FilePond`) and the issue was that the input didn't have a unique `id`. Once I gave each input a unique `id` the issue went away.

I was using the following in each nested component
```
<input id="upload-file" wire:model.lazy="file" type="file" class="hidden"/>
```

Once I added the `uuid` it worked
```
<input id="{{ $uuid }}-upload-file" wire:model.lazy="file" type="file" class="hidden"/>
```
