### ISSUE TITLE
Property [$] not found on component

### ISSUE THREAD

**Issue by tnt-freskim-veliu** [livewire/livewire#2744] opened 2021-04-20 14:19 UTC
### Description

When I try to update an input, it shows me this error :
Livewire\Exceptions\PropertyNotFoundException Property [$] not found on component

**Context**
- Livewire version: [2.4.2]
- Laravel version: [8.0]
- Alpine version: [2.7.0]
- Browser: [Chrome]

**Comment by joshhanley** [comment] 2021-04-20 21:41
@tnt-freskim-veliu please share your code and more details about what property you are trying to update.

**Comment by tonybyng** [comment] 2021-04-21 13:57
I have the same issue

I have a component within a component and the error reports that the child components property does not exist on the parent component.  In my case

Property [$file] not found on component: [entity-form]

Where $file is on the child component and not on the entity-form

However if I move the sub component outside of  the div of the main component it will work. I saw a few previous issues about this bug - one relating to a sub component in a table and one referring to  broken html causing it.  In my case I have  a 
```

<div>
    <form>
        @livewire("utils.file-uploader")
   </form>
</div>

```

which causes the issue but if i do

```

<div>
    <form>
   </form>
</div>
@livewire("utils.file-uploader")
```

it works ! but I need it within the form....

**Comment by tonybyng** [comment] 2021-04-21 15:07
I think Ive figured a bit more of a pattern

If I cut my sub component (the file uploader) blade file down so its simply

<input wire:model="file" type="file">

it works when the component is within the form, where its meant to be

But as soon as I add a <div></div> immediately above it within the sub component, it fails with the property error. It doesn't matter if a div goes below it, its  above that matters.  However, weirdly the divs below gets removed after a re-render when there is nothing to indicate they should be removed

(Im using livewire 2.4.3 by the way)

**Comment by tnt-freskim-veliu** [comment] 2021-04-21 16:19
The problem occurs when we have a component inside another component, and after two or more requests it shows that error. At components, I added wire:key but it didn't fix it.

**Comment by joshhanley** [comment] 2021-04-21 19:51
@tonybyng or @tnt can either of you please provide stripped down code (component class and blade file) that demonstrates the issue so we can replicate it?

If you think it's due to nested components, can you provide a sample parent component and child component?

Also can you provide a screenshot of the error that also shows the stack trace?

Thanks!

**Comment by tonybyng** [comment] 2021-04-22 08:29
@joshhanley 

Here is the screen shot with some of the stack trace

![image](https://user-images.githubusercontent.com/9347905/115678818-d5cf3a00-a349-11eb-8e0e-c9c7b0120408.png)

Ive hacked down  the main component and the sub component to a much smaller code base

Apparently I cant drag php files here so .......

the parent is simply started with a 

`        @livewire("entry.widget")`

The class file for the parent is 

```
<?php

namespace App\Http\Livewire\Entry;

use Livewire\Component;
use Livewire\WithFileUploads;

class Widget extends Component
{
    use WithFileUploads;
    public $name=null;

    protected $listeners = ["image_file_chosen_event"=>"imageUploaded"];

    public function imageUploaded()
    {
    }

    protected $rules = [
        'name' => 'max:200|required',
    ];

    public function render()
    {
        return view('livewire.entry.widget');
    }

    public function save()
    {

        dd("it works if we get here");
    }

}

```

The blade file for the parent is

```

<div class="mx-auto max-w-6xl py-5 px-1 md:px-5 lg:px-12 mb-24">
    <div>
        @if (session()->has('message'))
            <div class="alert alert-success">
                {{ session('message') }}
            </div>
        @endif
    </div>
    <form wire:submit.prevent="save">
        <div class="px-1 pt-6 pb-8 mb-4 flex flex-col md:px-8">

                <div class="-mx-3 md:flex mb-3">
                    <div class="md:w-1/2 px-3 mb-3 md:mb-0">
                        <label class="finso-label" for="created_at">
                            Created At
                        </label>
                    </div>
                    <div class="md:w-1/2 px-3">
                        <label class="finso-label" for="updated_at">
                            Last Updated At
                        </label>
                    </div>
                </div>
                <div class="-mx-3 md:flex mb-3">
                    <div class="md:w-3/4 px-3 mb-3 md:mb-0">
                        <label class="finso-label" for="id">
                            Internal ID
                        </label>
                    </div>
                    <div class="md:w-1/4 px-3">
                    </div>
                </div>


            <div class="-mx-3 md:flex mb-3">
                <div class="w-full px-3 mb-3 md:mb-0">
                    <label class="finso-label" for="name">
                        Name
                    </label>
                    <input class="w-full border border-gray-200 rounded py-3 px-4 mb-3 finso-form-input" id="name"
                           type="text" placeholder="Widget Name" wire:model.lazy="name">
                    <div>
                        @if($errors->has('name'))
                            <div class="error">{{ $errors->first('name') }}</div>
                        @endif
                    </div>
                </div>
            </div>
            <div class="-mx-3 md:flex mb-3">
                <div class="w-full px-3 mb-3 md:mb-0">
                    <label class="finso-label" for="name">
                        Image
                    </label>
                    @livewire("utils.file-uploader",["name"=>"image","text"=>"Drop your image here"])

                    <div>
                        @if($errors->has('image'))
                            <div class="error">{{ $errors->first('image') }}</div>
                        @endif
                    </div>
                </div>
            </div>

        </div>
    </form>
</div>

```
The class file for the child is

```
<?php

namespace App\Http\Livewire\Utils;

use Livewire\Component;
use Livewire\WithFileUploads;

class FileUploader extends Component
{
    use WithFileUploads;
    public $name;   // what is the name of the field to return the path back to
    public $file;   // what is the field to store the upload
    public $text="Drop your file here";
    public $type = "image";
    public $maxSize=20000;

    public function render()
    {
        return view('livewire.utils.file-uploader');
    }

    public function updatedFile($value)
    {
        if ($this->type==="image"){
            $this->validate([
                "file" => "image|max:".$this->maxSize
            ]);
        }
        $this->emit($this->name."_file_chosen_event");
    }

}

```

and the blade file for the child is

```
<div>

</div>
<div class="-mx-3 md:flex mb-3">
    <div>
        <input wire:model="file" type="file">
    </div>
</div>

```

If you change the blade file for the child to just be

`<input wire:model="file" type="file">`

then it seems to work

It might be that less code can produce the same issue but when i hacked it to bare bones it seemed to work so this was bare bones++ ;-)

**Comment by joshhanley** [comment] 2021-04-22 08:55
@tonybyng thanks for the detailed response, it really helps 🙂

The issue is the multiple root elements in the child blade file. Try wrapping it all in a div. 

You can only have one root element in a Livewire component, see "returning blade views" here in the docs https://laravel-livewire.com/docs/2.x/rendering-components
> Make sure your Blade view only has ONE root element.

Hope this helps!

**Comment by tonybyng** [comment] 2021-04-22 09:06
@joshhanley I am a muppet. Why did I not realise that?  All my others have one element and I goofed on that one.  You are a star. Many thanks.

**Comment by joshhanley** [comment] 2021-04-22 20:53
@tonybyng no worries, happens to all of us 🙂

@tnt-freskim-veliu does the above solve your issue too? If not, can you please provide code that demonstrates the issue?

Thanks!

**Comment by tnt-freskim-veliu** [comment] 2021-04-23 08:20
Yes is fixed, the problem was with multiple root elements in child

**Comment by joshhanley** [comment] 2021-05-02 20:52
@tnt ok great, thanks for confirming! Glad it worked. I'm going to close this now 🙂

**Comment by squishythejellyfish** [comment] 2021-05-02 20:52
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed** 2021-05-02 20:52 UTC

**Comment by pagegwood** [comment] 2021-06-18 00:52
This just drove me crazy for many hours... I've found another scenario that will throw this exact error!

I'm working on a dynamic auth form where a user can toggle between the login or register forms. I had an email field on each form, both associated with the $email property.

I was overlooking something very simple. One form used wire:model="email" whereas the other used wire:model.defer="email". Removing .defer to bring them both in sync fixed the issue.

**Comment by paul-adams-985** [comment] 2021-07-07 10:14
@pagegwood Good spot! Thank you.

**Comment by torian257x** [comment] 2021-07-17 00:37
err I have the same error
but I do have a single root div element.

I dont use defer either

It doesn't always happen either.

you guys should probably really run some basics checks. This error is an error that should never happen right? because it's useless to me.

**Comment by aphoe** [comment] 2021-08-15 14:55
I had this same issue when I forgot to bind another input field to `null ` ie I left the other field as `wire:model=""`

**Comment by thevalo** [comment] 2021-10-04 07:40
For me, it was not adding `.lazy` to model binding of a checkbox.

**Comment by TechMessiah** [comment] 2021-10-16 22:53
I think that there are many issues that may result in this error, in my case, I was resetting a property with $this->reset('prop'); after inserting it into the database.
I had to change it $this->prop = empty_value;

**Comment by BLWTF** [comment] 2022-02-01 06:38
@uxivimbi I agree, in my case, I used `wire:model.prevent` on an input.

**Comment by jayenne** [comment] 2022-02-08 18:46
FYI: you may also receive this same error if you're trying to use/set a reserved keyword like $queryString

**Comment by BLWTF** [comment] 2022-03-14 04:10
For some reason, debouncing an input causes this sometimes.

**Comment by mousa4007** [comment] 2022-10-14 15:03
> 

it solve my problem .. many thanks

**Comment by ousid** [comment] 2022-10-31 12:28
Late to the party.

Sometimes, the cache can cause this issue as well. 

- Try to wrap your component inside a `div` tag
- Try to clear the view cache `php artisan optimize:clear` (since the component is a blade file)

**Comment by isaacdarcilla** [comment] 2023-02-16 02:07
In my case, it was the `.defer` modifier. Removing it fixed the issue.

**Comment by DevIP98** [comment] 2024-01-25 20:47
It happened to me too "Property [$id] not found on component: [profile.update-profile-information-form]" and I solved it with:

` php artisan view:clear`
