### ISSUE TITLE
Weird behavior with HTML comments inside blade file

### ISSUE THREAD

**Issue by Highjhacker** [livewire/livewire#505] opened 2019-12-30 21:36 UTC
**Describe the bug**
Wanted to add a TODO comment at the top of my .blade file, which I did, but once the changes saved and the page refreshed, the whole layout was destroyed by a "dump" of livewire as shown in my screenshot.

**To Reproduce**
1. Use `php artisan livewire:make test` to create a new .blade and .php file
2. Go to the freshly created .blade file
3. Write an HTML comment as first line such as : 

```
<!-- Oh no -->
<div>
   ...
</div>
```
4. Include that in another .blade file, such as `home.blade.php`
5. Refresh your browser and see the livewire "dump" on the page.

**Screenshots**
https://gyazo.com/1548759212410c8e9cd6249f85461889

**Desktop (please complete the following information):**
 - Browser : Chrome

**Additional context**
Tried with another .blade file that wasn't created with `php artisan livewire:make` and no problems there.

**Comment by faustbrian** [comment] 2019-12-31 03:38
This is most likely caused by the DOM parser because it thinks that the comment is the root element. The `div` has to be the root element like it has to be with vue.

Also TODO comments should be made with blade comments or other developers will be able to see them by looking at the websites source in the browser.

**Comment by lancepioch** [comment] 2020-01-02 01:23
Expected behavior is that there is only a single root html element. I think it says that in the docs

**Comment by calebporzio** [comment] 2020-01-03 20:46
Yeah, I'm going to close this for now. Good call.

**Closed by calebporzio** 2020-01-03 20:46 UTC
Labels: Type: Question
