### ISSUE TITLE
Errors validations disappears when livewire make a call to 'messages' endpoint

### ISSUE THREAD

**Issue by rodrigore** [livewire/livewire#70] opened 2019-07-26 16:47 UTC
**Describe the bug**
Errors validations disappears when livewire make a call to 'messages' endpoint

**To Reproduce**

Hi, I'm testing Livewire with a simple form with validations. The inputs are lazy and when I submit the form it show sthe validations, but when I click outside of the input, the 'errors' disappears (livewire make an ajax to 'messages' endpoint).

In this gist I have the component and the blade files
https://gist.github.com/rodrigore/6f9ee280c0464200231b9e6e92697b89

**Expected behavior**
Errors objects in the 'messages' endpoint

**Screenshots**
![livewire](https://user-images.githubusercontent.com/1557305/61967400-30840800-afa3-11e9-89a2-b432854c9e66.gif)

**Desktop (please complete the following information):**
 - OS:  Mac OS
 - Browser: Chrome

**Comment by calebporzio** [comment] 2019-07-26 18:26
Yeah, so, this is the current behavior. The error bag is only passed through for the request it was thrown on. After that, it will be wiped unless you re-throw it.

I felt like this is desired behavior, but I could see how you wouldn't want a change in one input to wipe validation for the others.

I think the perfect behavior would be if Livewire wiped the validation for the input you are typing into and left the others. I can't really think of the best way to make this work off the top of my head, so I'm open to ideas about how it should work.

**Comment by chinleung** [comment] 2019-07-26 18:42
> I think the perfect behavior would be if Livewire wiped the validation for the input you are typing into and left the others. I can't really think of the best way to make this work off the top of my head, so I'm open to ideas about how it should work.

@calebporzio How about sending the error bag in the Livewire response and then send it back to the server on the next request?

**Comment by calebporzio** [comment] 2019-08-15 02:58
@chinleung - yeah, I think this might be the best course of action. I'm always hesitant to add more to the payload, but that might be the way to go.

**Comment by faustbrian** [comment] 2019-12-10 15:19
@rodrigore does still happen for you with the latest version?

**Comment by rodrigore** [comment] 2019-12-10 17:14
It doesn't, now the error doesn't disappear but I notice that if I make the next step:
* Click the submit button
* Livewire show all the errors message
* Focus on the first input and write something
* When I lose the focus of the input, livewire trigger an ajax request but the errors are still present
* But if I click the submit button again, livewire send the same ajax request but the errors disappear

![livewire](https://user-images.githubusercontent.com/1557305/70552026-5e837680-1b57-11ea-981f-54664e67d8d0.gif)


I write this code the first day that livewire was public and now the only thing that I did was update composer to use version 0.5.0, maybe some changes are required.

**Comment by calebporzio** [comment] 2019-12-12 09:53
@rodrigore, this is expected behavior. Because you are only calling `->validate()` from the "create" method in your component, the validation will only run when you click the submit button.

If you want "real-time" validation. You can either run the validation on every request (from the render method or something), or the best thing to do would be to use the new `->validateOnly`d a method in an update hook. Here are the docs for that: https://laravel-livewire.com/docs/input-validation/#real-time-validation

Closing this for now.

**Closed by calebporzio** 2019-12-12 09:53 UTC
