### ISSUE TITLE
Alpine lose state after a wire:click

### ISSUE THREAD

**Issue by TCM-dev** [livewire/livewire#671] opened 2020-03-03 09:58 UTC
**Describe the bug**
I have a dropdown
If I click on it I want it to open, if I click away I want it to close (it works)
Now if I click on a an option I want to set the new option in livewire and also close the dropdown.
That does not work. The new option is set, the dropdown closes itself and immediatly open again.
When I x-text the value of my variable "show" it displays, false, true and then nothing once I click on an option.

**To Reproduce**
This is the full code
`<div x-data="{show: false}" class="text-lg relative {{isset($first) ? '' : 'mt-2'}}">
    @include('components.inputs.label', ['name' => $name, 'label' => $label])
    <button @click="show = true" type="button" id="input-{{$name}}"
            class="p-2 w-full flex justify-between rounded border-transparent hover:border-gray-500 border bg-transparent hover:bg-gray-100 focus:bg-gray-100">
        <span>{{$choices[$value]}}</span>
        <span>@svg('arrow_down')</span>
    </button>
    <div x-show.transition.in="show" @click.away="show = false"
         class="text-base absolute top-auto mt-2 bg-white border border-gray-600 rounded w-full overflow-hidden">
        <ul>
            @foreach($choices as $key => $choice)
                <li class="font-medium p-2 hover:bg-gray-100"
                    @click.prevent="show = false; @this.set('{{$name}}', '{{$key}}');">
                    {{$choice}}</li>
            @endforeach
        </ul>
    </div>
</div>`

1. `x-data="{show: false}"` on main div
`@click="show = true"` on the button to open the dropdown
`x-show.transition.in="show"` and `@click.away="show = false"` on the dropdown div
` @click.prevent="show = false; @this.set('{{$name}}', '{{$key}}');"` on each options

2. Click on the dropdown
Click on an option
Expected behaviour : the dropdown closes itself and the new value is set
Actual behaviour : the dropdown closes itself, the new value is set, the dropdown opens itself

I'll also add that individually `show = false` and `@this.set('{{$name}}', '{{$key}}');` works as expected it just does not once there are the two.

**Comment by GRardB** [comment] 2020-03-22 16:40
For anyone else looking at this issue, here is the code in a formatted code block with indentation:

```
@include('components.inputs.label', ['name' => $name, 'label' => $label])

<button
  @click="show = true"
  type="button"
  id="input-{{$name}}"
  class="p-2 w-full flex justify-between rounded border-transparent hover:border-gray-500 border bg-transparent hover:bg-gray-100 focus:bg-gray-100"
>
  {{$choices[$value]}}
  @svg('arrow_down')

  <div
    x-show.transition.in="show"
    @click.away="show = false"
    class="text-base absolute top-auto mt-2 bg-white border border-gray-600 rounded w-full overflow-hidden"
  >
    @foreach($choices as $key => $choice)
      <li
        class="font-medium p-2 hover:bg-gray-100"
        @click.prevent="show = false; @this.set('{{$name}}', '{{$key}}');"
      >
        {{$choice}}
    @endforeach
```

You're missing a closing tag for the `<li>`. Not sure if that's a problem or not. I'm also wondering if there's any other code missing, aside from the root element with the `x-data` attribute.

I'm not sure if this will fix your problem, because I don't fully understand what you wrote, but if your Livewire component is re-rendering elements that relie on AlpineJS, you're going to lose all the events and whatnot that are bound to the old elements. In order to fix that, I put this in my `app.js` (not sure if this is recommended or not):

```
window.livewire.hook('afterDomUpdate', () => {
  window.Alpine.discoverUninitializedComponents((el) => {
    window.Alpine.initializeComponent(el)
  })
})
```

If that doesn't help, it may be worth recording your screen or something to show what the problem is, and perhaps providing more code (the full markup + the Livewire component's PHP code). I think you'll get more answers that way 👍

**Comment by calebporzio** [comment] 2020-06-24 14:46
Closing because @TCM-dev never responded to @GRardB's help (Thank you btw!)

If you want to re-open, you can resubmit an issue with an exactly copy and pastable Livewire component to reproduce the issue. Thanks!

**Closed by calebporzio** 2020-06-24 14:46 UTC
