### ISSUE TITLE
loading.attr not working for alternating buttons

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#411] opened 2019-12-12 16:52 UTC
I've created a `product` card that has a *Add to Cart* button. This button turns into *Remove from Cart* if the item is already attached to the `cart`.

When I keep clicking on the buttons, the loading state only works for the state that was initially set when I loaded the page. If the product is not in cart when I open or refresh the page, only the `addToCart` fires the loading state. If I add some products to cart and refresh the page, the added products have loading when I remove them, and not when I add them again.

```php

@unless($inCart)
    <button
        wire:click="addToCart"
        wire:loading.attr="disabled"
    >
        @lang('shop.add_to_cart')
    </button>
@else
    <button
        wire:click="removeFromCart"
        wire:loading.attr="disabled"
    >
        @lang('shop.remove_from_cart')
    </button>
@endunless
```

P.S. the structure is very similar to what Caleb did [here](https://calebporzio.com/video-realtime-livewire-w-laravel-echo-pusher/) in the first video. Just add a `loading` to it. `attr` or simple loading with `target`.

**Comment by calebporzio** [comment] 2020-06-21 16:22
I believe the problem is that Livewire doesn't realize you  are completely swapping the buttons.

I would add a `wire:key="some-unique key"` to each of the buttons and see if that fixes it.

Closing for now.

**Closed by calebporzio** 2020-06-21 16:22 UTC
Labels: Type: Bug
