### ISSUE TITLE
redirect with flash data throws an exception

### ISSUE THREAD

**Issue by SanderMuller** [livewire/livewire#1103] opened 2020-06-14 12:32 UTC
### Description
`return redirect()->route('home')->with('alert-success', 'Redirect worked!');` throws a `BadMethodCallException`

### Steps to reproduce
From a LiveWire component:
`return redirect()->route('home')->with('alert-success', 'Redirect worked!');`

**Context**
- Livewire version: v1.1.0
- Laravel version: 7.15.0

It would be great if the redirect could support flashing data through the fluent with method, just like regular Laravel redirects!

P.s. Livewire is amazing!

**Comment by Braunson** [comment] 2020-07-30 21:52
This is related to #841

**Comment by stancl** [comment] 2020-09-28 22:46
It's a duplicate of #841. I think this should be closed.

**Closed** 2020-10-16 16:13 UTC
