### ISSUE TITLE
TypeError: initialData is null

### ISSUE THREAD

**Issue by michele-grifa** [livewire/livewire#1632] opened 2020-09-17 18:17 UTC
### Description
I have this error when i call a method in the component, using $wire from Alpine JS.
 
```
Uncaught (in promise) TypeError: initialData is null
    Component index.js:29
    onNodeAdded index.js:484
    callHook morphdom.js:35
    handleNodeAdded morphdom.js:140
    morphEl morphdom.js:407
    morphEl morphdom.js:219
    morphEl morphdom.js:332
    morphEl morphdom.js:219
    morphEl morphdom.js:332
    morphEl morphdom.js:219
    morphdomFactory morphdom.js:463
    value index.js:357
    value index.js:268
    value index.js:239
    value index.js:7
    value index.js:50
    promise callback*value/< index.js:45
    promise callback*value index.js:43
    sendMessage index.js:212
    value index.js:222
    later debounce.js:8
    setTimeout handler*debounce/< debounce.js:12
    value index.js:195
    value index.js:153
    value index.js:150
    get index.js:678
    setupContextMenu alpine.min.js line 7 > Function:12
    jQuery 8
    setupContextMenu alpine.min.js line 7 > Function:11
    open alpine.min.js line 7 > Function:52
    anonymous alpine.min.js line 7 > AsyncFunction:3
    evaluateCommandExpression alpine.js:140
    evaluateCommandExpression alpine.js:1700
    C alpine.js:883
    c alpine.js:859
    P alpine.js:878
    registerListeners alpine.js:1631
    registerListeners alpine.js:1623
    initializeElement alpine.js:1569
    initializeElements alpine.js:1554
    walkAndSkipNestedComponents alpine.js:1544
    e alpine.js:87
    walkAndSkipNestedComponents alpine.js:1532
    initializeElements alpine.js:1549
    fe alpine.js:1459
    initializeComponent alpine.js:1852
    start alpine.js:1795
    discoverComponents alpine.js:1811
    discoverComponents alpine.js:1810
    start alpine.js:1794
    async* alpine.js:1881
    deferLoadingAlpine anagrafiche:51
    dispatch dispatch.js:6
    value index.js:83
    <anonymous> anagrafiche:56
    EventListener.handleEvent* anagrafiche:55
index.js:29:32
    Component index.js:29
    onNodeAdded index.js:484
    callHook morphdom.js:35
    handleNodeAdded morphdom.js:140
    morphEl morphdom.js:407
    morphEl morphdom.js:219
    morphEl morphdom.js:332
    morphEl morphdom.js:219
    morphEl morphdom.js:332
    morphEl morphdom.js:219
    morphdomFactory morphdom.js:463
    value index.js:357
    value index.js:268
    value index.js:239
    value index.js:7
    value index.js:50
    (Asinc.: promise callback)
    value index.js:45
    (Asinc.: promise callback)
    value index.js:43
    sendMessage index.js:212
    value index.js:222
    later debounce.js:8
    (Asinc.: setTimeout handler)
    debounce debounce.js:12
    value index.js:195
    value index.js:153
    value index.js:150
    get index.js:678
    setupContextMenu alpine.min.js line 7 > Function:12
    jQuery 8
    setupContextMenu alpine.min.js line 7 > Function:11
    open alpine.min.js line 7 > Function:52
    anonymous alpine.min.js line 7 > AsyncFunction:3
    evaluateCommandExpression alpine.js:140
    evaluateCommandExpression alpine.js:1700
    C alpine.js:883
    c alpine.js:859
    (Asinc.: EventListener.handleEvent)
    P alpine.js:878
    registerListeners alpine.js:1631
    forEach self-hosted:216
    registerListeners alpine.js:1623
    initializeElement alpine.js:1569
    initializeElements alpine.js:1554
    walkAndSkipNestedComponents alpine.js:1544
    e alpine.js:87
    walkAndSkipNestedComponents alpine.js:1532
    initializeElements alpine.js:1549
    fe alpine.js:1459
    initializeComponent alpine.js:1852
    start alpine.js:1795
    discoverComponents alpine.js:1811
    forEach self-hosted:216
    discoverComponents alpine.js:1810
    start alpine.js:1794
    AsyncFunctionNext self-hosted:684
    (Asinc.: async)
    <anonima> alpine.js:1881
    deferLoadingAlpine anagrafiche:51
    dispatch dispatch.js:6
    value index.js:83
    <anonima> anagrafiche:56
    (Asinc.: EventListener.handleEvent)
    <anonima> anagrafiche:55
```

### Exact steps to reproduce

- Load the page
- Open the context menu on the table row
- Click on the second menu item
- The method on the component is called, but in the browser console, i get the error.

### Stripped-down, copy-pastable code snippets
**This is the view of the component**

```html
<tbody>
	@foreach($anagrafiche as $anagrafica)
		<tr wire:key="{{ $anagrafica->id }}" class="row_listino
			@if($anagrafica->elaborata && trim($anagrafica->descrizione_errore)=="") positive
			@elseif($anagrafica->elaborata && trim($anagrafica->descrizione_errore)!="") error
			@endif
		" x-ref="row" x-data="{ id: {{ $anagrafica->id }},
			setupContextMenu(popup) {
				var parent = this;
				$(this.$refs.item_imm).on('click', function(event) {
					$(popup).popup('hide');
					$('.import-modal[data-modalid=\'' + parent.id + '\']').modal('show');
				});
				$(this.$refs.item_delete).on('click', function(event) {
					$wire.removedRiga(parent.id);
				});
			},
			open(event, element) {
				let target;
				if(event.explicitOriginalTarget) {
					target = event.explicitOriginalTarget;
				}
				else if(event.srcElement) {
					target = event.srcElement;
				}
				let html = '<div class='ui vertical menu'>
							<a class='item' x-ref='item_imm'>
								<i class='image icon'></i>
								Modifica Immagini
							</a>
							<a class='item' x-ref='item_delete'>
								<i class='delete icon'></i>
								Elimina
							</a>
						</div>';
				if(!$(target).popup('is visible')) {
					$(target)
						.popup({
							html: html,
							context: target,
							target: target,
							exclusive: true,
							hoverable: false,
							on: 'manual',
							position: 'bottom center',
							onHide: function(module) {
								$(target).off('click');
							}
						});
					$(target).popup('show');
					this.setupContextMenu(target);
				}
			}
		 }
		 " x-on:contextmenu.prevent="open($event,$refs.row)">
		</tr>
	@endforeach
	</tbody>
```

**This is the component code**

```php
public $testata;
    public $anagrafiche;

    public function mount(Request $request, $testata)
    {
        $this->testata = $testata;
        if($this->testata == null) $this->anagrafiche = array();
        else $this->anagrafiche = $this->testata->anagrafiche;
    }

    public function removedRiga($idAnagrafica) {
        if($idAnagrafica) {
            $anagrafica = Anagrafica::find($idAnagrafica);
            Storage::disk('allegati')->delete(array($anagrafica->allegato1,
                $anagrafica->allegato2,$anagrafica->allegato3,$anagrafica->allegato4,
                $anagrafica->allegato5,$anagrafica->allegato6,$anagrafica->allegato7,
                $anagrafica->allegato8,$anagrafica->allegato9,$anagrafica->allegato10));
            $anagrafica->delete();
            $this->anagrafiche->forget($idAnagrafica);
        }
    }

    public function render()
    {
        return view('livewire.import-list');
    }
```

**Context**
- Livewire version: 2.2.3
- Laravel version: 8.4.0
- Browser: Firefox

**Comment by calebporzio** [comment] 2020-09-18 14:04
Sorry you came across an issue. I'm closing this because the provided code is too difficult to reproduce because it references other parts of your system that other people don't have.

Please narrow down the problem and re-submit/open with more easily copy-pastable-stripped-down code.

Thanks!

**Closed by calebporzio** 2020-09-18 14:04 UTC
