### ISSUE TITLE
Emitting an event from the mount method doesn't work (fails silently)

### ISSUE THREAD

**Issue by isaackearl** [livewire/livewire#1869] opened 2020-10-21 19:53 UTC
### Description
There are cases when we want to notify a parent component that our child component has mounted or has been accessed by the user.  The problem is that it seems that $this->emit is not supported on the mount method.

### Exact steps to reproduce

1. Create two simple components
2. first an event from the first component on mount
3. listen for the event on the second component
4. realize it doesn't work

### Stripped-down, copy-pastable code snippets

```
class ComponentOne extends Component
{

    // emitting an event to be picked up by the other component
    public function mount(){
      $this->emit('hello');
    }

    public function render()
    {
        return view('component-one');
    }
}
```
second component
```
class ComponentTwo extends Component
{

    protected $listeners = ['hello' => 'doSomething'];    

    public function doSomething(){
        dump('this never happens');
    }

    public function render()
    {
        return view('component-two');
    }
}
```

in this very simple example you'd expect it to immediately dump 'this never happens' because when both components are on the page, the first one should emit an event when mounted, but I don't think it ever does.

**Context**
- Livewire version: 2.3.0
- Laravel version: 8.11.2
- Browser: chrome (probably any)

**Comment by danharrin** [comment] 2020-10-21 19:59
Hey, I believe this is a duplicate of #1592, if you could post your example there (even PR a failing test if possible), that would be perfect 👍

**Closed by danharrin** 2020-10-21 19:59 UTC
