### ISSUE TITLE
wire:loading isn't working when setting the value of a component using $wire

### ISSUE THREAD

**Issue by abishekrsrikaanth** [livewire/livewire#2271] opened 2020-12-28 19:29 UTC
### Exact steps to reproduce

I have a loading state setup to show when `product_id` is updated.

```
<img src="/images/wait-icon.gif" alt="Processing" class="h-10 w-auto ml-1 inline-flex" 
     wire:loading wire:target="product_id">
```

I am setting the value for `product_id` through javascript

```
$wire.set('product_id','SOME_VALUE');
```

This doesn't show the loading state.

**Context**
- Livewire version: [e.g. 2.3.5]
- Laravel version: [e.g. 8.20.1]
- Alpine version: [e.g. 2.8.0]
- Browser: [e.g. Chrome]

**Comment by austenc** [comment] 2021-02-01 12:43
@abishekrsrikaanth using `wire:target` this way will only work if `product_id` is updated via `wire:model`.

See here: https://laravel-livewire.com/docs/2.x/loading-states#targeting-actions

As a workaround, you could create a method on your component and target that instead, something like this:

**Component**
```
public function updateProduct($id) {
    $this->product_id = $id;
}
```

**Blade View**
```
<div wire:loading wire:target="updateProduct">Loading...</div>
<button @click="$wire.updateProduct(123)">Update</button>
```

Going to close this since it's not a bug. Hope that helps!

**Comment by squishythejellyfish** [comment] 2021-02-01 12:44
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed** 2021-02-01 12:43 UTC
