### ISSUE TITLE
Nested alpine component, entangle, error causes object assignment

### ISSUE THREAD

**Issue by cutigersfan** [livewire/livewire#1763] opened 2020-10-06 13:29 UTC
### Description
In the playground below, press the button. You will notice that the value of the input now is: [object Object]. 

In narrowing down this issue for the playground it seems that you need 3 things to reproduce:

1. Nested alpine components
2. @entangle on the innermost component
3. The @error directive on the input style also makes a difference. I originally used this on a class for a similar effect, but this seems to reproduce the issue

### Exact steps to reproduce
https://laravelplayground.com/#/snippets/d85657ce-19a2-4575-b619-11476b21115a

**Context**
- Livewire version: 2.2.9 (Not 100% sure what playground is using)
- Laravel version: 8.7.1 (Not 100% sure what playground is using)
- Browser: Chrome, Safari

**Comment by cihantas** [comment] 2020-10-08 17:06
#1781 This seems to be the same issue. Thanks for adding the playground example.

**Comment by calebporzio** [comment] 2020-10-14 16:19
Thanks for writing such a reproducible issue. Makes the life of a maintainer much easier.

I tested that playground locally with the next version of Livewire (will be v2.3.0 when it's released) - and it worked perfectly.

Closing this, thanks!

**Closed by calebporzio** 2020-10-14 16:19 UTC
