### ISSUE TITLE
Easy access to all form-data after form submit

### ISSUE THREAD

**Issue by ducopro** [livewire/livewire#313] opened 2019-10-04 12:50 UTC
Right now we can easily create interactive forms by using `wire:model` on a variety of input elements. Even nested properties are now supported so we can put all the interactive form-data elements in an array if we want. So far so good.

No problem at all if we are creating LiveWire components that are specifically made for hard coded forms.

But what if some of the input elements in the form do not need to be reactive? How do we get to those values in the component? `wire:model` on them is a little to much. We dont want an ajax request every time they change. We only want to know the value once the form is submitted.

There is also the case of meta-data programming. What if we do not want to hard-code the form, but create it based on metadata? In that case the LiveWire component should be more dynamic.

What I am looking for is a way to retrieve all the form-data at once in the LiveWire component.

Right now i just haven't found a good way of doing this. *Maybe I am just not seeing the obvious.* Maybe there is already some sort of workaround?

At the least I would want to send the form-data with the submit-event on the form level.

Anyone any ideas?

**Comment by calebporzio** [comment] 2019-10-04 13:41
I totally agree. This would be very helpful. I'll spit out some API ideas:

Ok, here's a way you could actually do this right now:
```html
<form wire:submit.prevent="submit(Object.fromEntries(new FormData($event.target)))">
    <input type="text" name="foo">
    <input type="text" name="bar">

    <button>Submit</button>
</form>
```

Then, in your component, here's the submit method:
```php
public function submit($formData)
{
    dd($formData);
}
```

After typing in "baz" and "bob" into the inputs and submitting, this will output:
![image](https://user-images.githubusercontent.com/3670578/66211446-1ee96b80-e68a-11e9-879b-b3cc26bed50c.png)

This will work in the meantime. But there are two things this lacks:

1. This won't handle nested data (like `name="foo[a]"`)
2. This feels hacky and ugly

Here are a three proposals for different APIs to supports this:

## Proposal A:
Pass the form data directly to the method by default (if no other parameters are specified)
### View
```
<form wire:submit="submit">
```

### Component
```php
public function submit($data)
```

## Proposal B:
Add a magic variable to get the form data and pass it in.
### View
```
<form wire:submit="submit($formData)">
```

### Component
```php
public function submit($data)
```

## Proposal C:
A custom directive that's in charge of handling forms. There is extra potential here for custom behavior on the backend and frontend? Maybe there would be a convenient way to validate against this data, or use a form object or something.
### View
```
<form wire:form="foo">
```

### Component
```php
public function onFooSubmit($data)
```

Currently, **B** is my favorite and could be implemented fairly easily. But obviously **C** has some serious potential. But maybe we wait until this idea is fleshed out further to move to something like **C**

Thoughts?

**Comment by ducopro** [comment] 2019-10-04 17:08
Nice to see we're following the same line of thinking:-) I was initially also thinking about options A and B. But to me they both felt a little bit *hacky*

Before you know it there are *magic* variables everywhere. It doesn't feel *clean*. And listening to your podcasts, i think you feel the same. It is not intuitive. You need to check the docs. 

I commented yesterday or the day before on an issue that someone hadn't read the docs about `key()` in the docs ...... I think keeping the LiveWire API as simple as possible will help adoption. I still see tremendous potential in LiveWire.

About your option C, I was thinking more in the line of `wire:model` on the form element. That feels clean. But........ `wire:model` is all about 2-way data-binding. Is that something you would consider? I am not talking about implementation yet. We could even use the same modifiers on the form level.

I probably would use `wire:model.lazy="formData"` on the form level and would expect my inputs to be initialized from this array on the component and updated on every change event.

For more dynamic forms this could be a life saver. We could add input elements and `change` events on the new inputs could be handled generically.

That said. I remember a discussion in the early days of Angular 2 about data binding and the api/interface. They split the binding in two ways. In other words there is a separate API for up- and downstream. On top of that there is an API that combines the two for easy 2-way data binding. Does that make sense? Just an idea to make the API more consistent.

Last but not least about your proposed workaround. It feels hacky to you, you say. Well, yes and no.
We cannot support everything in an API. There comes a time you have to resort to the javascript side of things :-) What I understand is that LiveWire supports inline javascript? `form.submit="<javascript that will be evaluated>"`

If this was documented, well, than it doesn't feel hacky to me. It feels powerfull!

@calebporzio Just some thoughts on a nice Dutch friday evening ........

**Comment by bdweix** [comment] 2019-10-05 17:10
> I probably would use wire:model.lazy="formData" on the form level and would expect my inputs to be initialized from this array on the component and updated on every change event.

I would love a feature like this. For me I care less about binding individual inputs, and more about easily binding our entire forms. Once the user submits the form then all of the inputs are passed to the controller. Would be very interesting to see what a Livewire form model could open up for validation/loading states as well.

**Comment by calebporzio** [comment] 2019-10-07 22:19
All these thoughts make good sense. Thanks for the feedback. Does anyone have ideas of what attaching `wire:model` to form element would look like in the backend?

Some initial thoughts:
would wire:model="foo", bind to a public property called `$foo` that's just a plain array of data? OR will `$foo` be a Livewire object called "LivewireForm" or something that get's hydrated. How ill someone validate against the form? How would we show specific validadtion errors next to input elements. Will the dev need to list out every single input name in the backend to prevent mass assignment stuff?

There's a lot of question marks here for me.

**Comment by bdweix** [comment] 2019-10-08 02:07
@calebporzio I'm not exactly sure how this could work, but would it be plausible to leverage the existing request object somehow? Or a Livewire specific request object? 

For example, if a user submits a form with `wire:form="store"` or `wire:submit="store"`, a request object will be passed to the controller function `store(Request $request)`. The `$request` would contain all of the inputs that were submitted with the form, regardless if they have public properties or not. 

I haven't spent much time looking at how Livewire connects everything behind the scene so this may simply not be possible. I'll try to dive in more this week.

**Comment by jwktje** [comment] 2019-10-14 13:37
Using forms this way solves my issue #117 after some refactoring. So this would be great!

**Comment by calebporzio** [comment] 2019-10-14 19:30
Hey @bdweix - that's a really interesting suggestion. It would be a HUGE win in terms of usability. The question is, do we want to "fake" the Laravel request. 

We would have to work some black magic (totally possible), but we have to decide if it would be too much magic.

**Comment by calebporzio** [comment] 2019-10-14 19:32
Hey @jwktje - can you expound on how this solves your problem? Thanks, it's just hard to context switch, and you spelling it out for me will be much easier. Thanks!

**Comment by bdweix** [comment] 2019-10-14 19:58
@calebporzio - I agree I think faking a Laravel request would be too confusing. Instead of "faking" it, I think you could potentially provide access to the original request that Livewire grabs. This may require some moving of the Livewire data into a single field `livewire` to avoid confusion. 

That way if I attached Livewire to a form and did `dd($request)`, all of the form inputs are visible inside of the request like normal. I would also presumably see the Livewire information, which could be very helpful towards understanding some of the magic of Livewire.

I will think about this a bit more, especially regarding validation/responses/etc. If you're looking for podcast/docs ideas - a section dedicated to the "Request Lifecycle of Livewire" showing what happens through the code when something is bound to wire:model would be extremely helpful. I'm sure you've got endless work on your plate already though and thank you for spending so much time on all this!

**Comment by jwktje** [comment] 2019-10-15 10:47
@calebporzio Sure! The refactor below results in the expected behavior that I mention in my issue #117
**chat.blade.php***
```
<div>
    <div class="messages-wrap" wire:poll.5000ms="$refresh">
        @foreach ($messages as $message)
            <div>{{$message->text}}</div>
        @endforeach
    </div>
    <form wire:submit.prevent="newMessage(Object.fromEntries(new FormData($event.target)))" wire:ref="send-message">
        <input type="text" name="message" wire:loading.attr="disabled" wire:target="send-message">
        <button>Send</button>
        <button id="clearMessages" wire:click="clearMessages">Clear</button>
    </form>
</div>
```

**Chat.php**
```
namespace App\Http\Livewire;
use Livewire\Component;
use App\Messages;

class Chat extends Component
{
    public function render()
    {
        return view('livewire.chat',['messages' => Messages::all()]);
    }
    public function newMessage($formData)
    {
        if($formData['message']) {
            Messages::create(['text' => $formData['message']]);
        }
    }
    public function clearMessages()
    {
        Messages::truncate();
    }
}
```

**Comment by K2ouMais** [comment] 2020-01-07 10:07
Is there a way to send a hidden field?

I want to know wich ID on DB I want to update, but the hidden field isnt sent to the controller.

If you have another way to do it, would be very cool.

Thank you

**Comment by calebporzio** [comment] 2020-02-04 13:24
Closing this for now. Unless more people really pull for a `$formData` magic value, OR automatically sending it along on submit.

**Closed by calebporzio** 2020-02-04 13:24 UTC
Labels: Type: Enhancement

**Comment by shahvirag** [comment] 2020-07-07 05:07
> I totally agree. This would be very helpful. I'll spit out some API ideas:
> 
> Ok, here's a way you could actually do this right now:
> 
> ```
> <form wire:submit.prevent="submit(Object.fromEntries(new FormData($event.target)))">
>     <input type="text" name="foo">
>     <input type="text" name="bar">
> 
>     <button>Submit</button>
> </form>
> ```
> 
> Then, in your component, here's the submit method:
> 
> ```
> public function submit($formData)
> {
>     dd($formData);
> }
> ```
> 
> After typing in "baz" and "bob" into the inputs and submitting, this will output:
> ![image](https://user-images.githubusercontent.com/3670578/66211446-1ee96b80-e68a-11e9-879b-b3cc26bed50c.png)
> 
> This will work in the meantime. But there are two things this lacks:
> 
> 1. This won't handle nested data (like `name="foo[a]"`)
> 2. This feels hacky and ugly
> 
> Here are a three proposals for different APIs to supports this:
> 
> ## Proposal A:
> Pass the form data directly to the method by default (if no other parameters are specified)
> 
> ### View
> ```
> <form wire:submit="submit">
> ```
> 
> ### Component
> ```
> public function submit($data)
> ```
> 
> ## Proposal B:
> Add a magic variable to get the form data and pass it in.
> 
> ### View
> ```
> <form wire:submit="submit($formData)">
> ```
> 
> ### Component
> ```
> public function submit($data)
> ```
> 
> ## Proposal C:
> A custom directive that's in charge of handling forms. There is extra potential here for custom behavior on the backend and frontend? Maybe there would be a convenient way to validate against this data, or use a form object or something.
> 
> ### View
> ```
> <form wire:form="foo">
> ```
> 
> ### Component
> ```
> public function onFooSubmit($data)
> ```
> 
> Currently, **B** is my favorite and could be implemented fairly easily. But obviously **C** has some serious potential. But maybe we wait until this idea is fleshed out further to move to something like **C**
> 
> Thoughts?

Not working for select input with multiple option enabled.

**Comment by jiteshdhamaniya** [comment] 2020-10-05 07:59
> @calebporzio Sure! The refactor below results in the expected behavior that I mention in my issue #117
> **chat.blade.php***
> 
> ```
> <div>
>     <div class="messages-wrap" wire:poll.5000ms="$refresh">
>         @foreach ($messages as $message)
>             <div>{{$message->text}}</div>
>         @endforeach
>     </div>
>     <form wire:submit.prevent="newMessage(Object.fromEntries(new FormData($event.target)))" wire:ref="send-message">
>         <input type="text" name="message" wire:loading.attr="disabled" wire:target="send-message">
>         <button>Send</button>
>         <button id="clearMessages" wire:click="clearMessages">Clear</button>
>     </form>
> </div>
> ```
> 
> **Chat.php**
> 
> ```
> namespace App\Http\Livewire;
> use Livewire\Component;
> use App\Messages;
> 
> class Chat extends Component
> {
>     public function render()
>     {
>         return view('livewire.chat',['messages' => Messages::all()]);
>     }
>     public function newMessage($formData)
>     {
>         if($formData['message']) {
>             Messages::create(['text' => $formData['message']]);
>         }
>     }
>     public function clearMessages()
>     {
>         Messages::truncate();
>     }
> }
> ```

How do you validate this data ?

**Comment by Keoghan** [comment] 2020-10-07 16:10
@jiteshdhamaniya I am playing with this at the moment and have used something like this:

```php
 try {
            $validator = Validator::make($formData, ['name' => 'required']);
            $validator->validate();
        } catch (ValidationException $e) {
            return redirect()->back()->withErrors($validator->errors())->withInput($formData);
        }
```

Literally started playing with LiveWire today, so no idea if that is the best way but might help.

**Comment by xtfer** [comment] 2020-10-15 11:52
Disappointing that this was closed. The example given in https://github.com/livewire/livewire/issues/313#issuecomment-538401606 no longer seems to work.

**Comment by gavinhewitt** [comment] 2020-10-15 18:55
> Disappointing that this was closed. The example given in [#313 (comment)](https://github.com/livewire/livewire/issues/313#issuecomment-538401606) no longer seems to work.

I literally just implemented this and seems to work just fine.

**Comment by jiteshdhamaniya** [comment] 2020-10-16 02:48
> @jiteshdhamaniya I am playing with this at the moment and have used something like this:
> 
> ```
> try {
>       $validator = Validator::make($formData, ['name' => 'required']);
>       $validator->validate();
> } catch (ValidationException $e) {
>       return redirect()->back()->withErrors($validator->errors())->withInput($formData);
> }
> ```
> 
> Literally started playing with LiveWire today, so no idea if that is the best way but might help.

I am using controlled inputs instead now (thats react phrase I know). so you put that validator in save method ?

**Comment by lnfel** [comment] 2021-03-11 07:02
Was doing some dynamic form input fields today and tried the solution below:

> ```
> <form wire:submit.prevent="submit(Object.fromEntries(new FormData($event.target)))">
>     <input type="text" name="foo">
>     <input type="text" name="bar">
> 
>     <button>Submit</button>
> </form>
> ```

But to my surprise I missed reading the drawback Caleb pointed out:

> This will work in the meantime. But there are two things this lacks:
> 
> 1. This won't handle nested data (like `name="foo[a]"`)

Anyone had a workaround on handling **field name array syntax** like `name="details[ ]"`?
Also found these two articles which talk in depth about it:

- [Cleaning Up Form input with Transpose](https://adamwathan.me/2016/04/06/cleaning-up-form-input-with-transpose/)
- [A little trick for grouping input fields](https://mattstauffer.com/blog/a-little-trick-for-grouping-fields-in-an-html-form/)

**Comment by medioseureka** [comment] 2021-03-17 20:38
Is there any update on this? the current proposal is fine if one doesn't have a checkbox or hidden inputs, so, it will not work under many circumstances.

**Comment by lnfel** [comment] 2021-03-18 08:53
@medioseureka I came up with a solution from my previous comment [#313](https://github.com/livewire/livewire/issues/313#issuecomment-796512648):

after doing the `name="details[${index}]` thing, in your livewire component action:

```
// declaring details as an array so we can use php array methods later
public $details = [ ];

public function update($formData)
{
        // filter form data with field names that starts with details
        $filtered = array_filter($formData, function($key) {
	        return strpos($key, 'details') === 0;
        }, ARRAY_FILTER_USE_KEY);
        // note: ARRAY_FILTER_USE_KEY is a local php helper/method, pretty nifty
        
        //dd($formData, $filtered, $filteredDetailEdit);
        
        // create new instances of the model for each detail and insert them into
        foreach ($filtered as $key => $value) {
	        $this->details[ ] = new IntroSectionDetail([
		        //'intro_section_id' => $formData['id'],
		        'text' => $value
	        ]);
        }
        
        // check if we have data from our dynamic input fields before saving
        // since we transformed our details[] into new instances of the model we can now use ->saveMany() method
        if(sizeof($this->details)) {
	        $this->introSection->details()->saveMany($this->details);
	        $this->dispatchBrowserEvent('detail-saved');
        }
}
```

Hope this helps anyone.

**Comment by lnfel** [comment] 2021-03-19 04:04
I'm not quite satisfied with my previous workaround so here's another one, this time without using: 
`<form wire:submit.prevent="submit(Object.fromEntries(new FormData($event.target)))">`

still using `public $details = [ ];` in livewire component controller

on the laravel component template:

```
<x-input.group>
        <x-input.label label="Details"/>
        @foreach ($details + [count($details) => ''] as $index => $detail)
	        <div wire:key="{{ $loop->index }}">
		        <x-input.text wire:model="details.{{ $index }}" class="w-full transition ease-in-out-back duration-700 fade-in" name="details[{{$index}}]" placeholder="Add detail" autocomplete="off"/>
		        <x-input.error for="{{ 'details.'.$index }}" />
	        </div>
        @endforeach
</x-input.group>
```

This way we can have our **form** to accept `wire:submit.prevent="action"` and receive details as:
```
details: [
        0: "Sample input",
        1: "Another input",
],
```

in the livewire action method:

```
use Illuminate\Support\Facades\Validator;
...
protected $rules = [
        'details.*' => 'string',
];

public function store() {
        // run validation on dynamic input using validateOnly
        $validatedDetails = $this->validateOnly('details.*', ['details.*' => 'email']);
}

if ($this->validatedDetails) {
	// resetting reusing validatedDetails to hold array of model instances
	$this->validatedDetails = [];
        // since details is already validated we are safe to use its values now
	foreach ($this->details as $key => $value) {
		$this->validatedDetails[] = new IntroSectionDetail([
			'text' => $value
		]);
	}	
}
```
using `dd($this->validatedDetails, $this->details);` will now show us this:

![image](https://user-images.githubusercontent.com/47680867/111729625-6ed1e780-88aa-11eb-89a6-8dbf9dd6c0ae.png)

saving the model instances using saveMany():

```
// check if we got model instances from validatedDetails
// details is a relationship hence, `->details()` part
if(sizeof($this->validatedDetails)) {
	$this->introSection->details()->saveMany($this->details);
	$this->dispatchBrowserEvent('detail-saved');
}
```

Phew, diving deep in validation is quite fun actually.

**Comment by hayespdx** [comment] 2021-04-23 21:06
@calebporzio I would also love it if this feature was incorporated in a future version! I've got a form where the inputs are updated by events on a Google Map so have to wire:ignore those. I vote for Proposal B. Your ugly hack is working for me now - thanks for that.

**Comment by marufdevops** [comment] 2021-08-16 15:53
> I totally agree. This would be very helpful. I'll spit out some API ideas:
> 
> Ok, here's a way you could actually do this right now:
> 
> ```
> <form wire:submit.prevent="submit(Object.fromEntries(new FormData($event.target)))">
>     <input type="text" name="foo">
>     <input type="text" name="bar">
> 
>     <button>Submit</button>
> </form>
> ```
> 
> Then, in your component, here's the submit method:
> 
> ```
> public function submit($formData)
> {
>     dd($formData);
> }
> ```
> 
> After typing in "baz" and "bob" into the inputs and submitting, this will output:
> ![image](https://user-images.githubusercontent.com/3670578/66211446-1ee96b80-e68a-11e9-879b-b3cc26bed50c.png)
> 
> This will work in the meantime. But there are two things this lacks:
> 
> 1. This won't handle nested data (like `name="foo[a]"`)
> 2. This feels hacky and ugly
> 
> Here are a three proposals for different APIs to supports this:
> 
> ## Proposal A:
> Pass the form data directly to the method by default (if no other parameters are specified)
> 
> ### View
> ```
> <form wire:submit="submit">
> ```
> 
> ### Component
> ```
> public function submit($data)
> ```
> 
> ## Proposal B:
> Add a magic variable to get the form data and pass it in.
> 
> ### View
> ```
> <form wire:submit="submit($formData)">
> ```
> 
> ### Component
> ```
> public function submit($data)
> ```
> 
> ## Proposal C:
> A custom directive that's in charge of handling forms. There is extra potential here for custom behavior on the backend and frontend? Maybe there would be a convenient way to validate against this data, or use a form object or something.
> 
> ### View
> ```
> <form wire:form="foo">
> ```
> 
> ### Component
> ```
> public function onFooSubmit($data)
> ```
> 
> Currently, **B** is my favorite and could be implemented fairly easily. But obviously **C** has some serious potential. But maybe we wait until this idea is fleshed out further to move to something like **C**
> 
> Thoughts?

can we make this work on a form having checkbox group?

**Comment by andreasmatu** [comment] 2021-11-23 22:41
@shahvirag did you find a solution for multiple select inputs?

**Comment by mtownsend5512** [comment] 2022-06-15 13:28
Hey @calebporzio just wanted to drop a **+1** support for form data through a form. I just ran into this issue yesterday and had to work around it. Loved this style proposal:

``<form wire:submit="submit($formData)">``

**Comment by emreakay** [comment] 2022-11-03 08:23
is this feture implemented @calebporzio ?

**Comment by victorchat** [comment] 2022-12-27 13:49
The #3131 solution brakes does not work as expected when an array is used for grouping the input values:

`<input type="text" name="group[value]" value="1" />"`

The request does not do the grouping:

`
array:2 [▼ 
  "_method" => "post"
  "group[value]" => "1"
]
`

**Comment by dimitrijev** [comment] 2023-02-05 00:07
I think this will work for multiple selects and other inputs with structure like multilevel arrays

`<form wire:submit.prevent="submit(new URLSearchParams(new FormData($event.target)).toString())">`

And in submit method:
```
public function submit($formData)
    {
        parse_str($formData, $dataArray);
        dd($dataArray);
```

**Comment by Zephni** [comment] 2023-02-09 11:25
> I think this will work for multiple selects and other inputs with structure like multilevel arrays
> 
> `<form wire:submit.prevent="submit(new URLSearchParams(new FormData($event.target)).toString())">`
> 
> And in submit method:
> 
> ```
> public function submit($formData)
>     {
>         parse_str($formData, $dataArray);
>         dd($dataArray);
> ```

This is so perfect thank you. It even works with file inputs which is what I was having the main trouble with, but this sends and interprets all of the form data and you even get the image as an object.

Thanks again! :)

**Comment by Zephni** [comment] 2023-02-09 20:30
Oh whoops, in a sad turn of events it was just passing a string of "[object File]" lol, and I misinterpreted it as the actual image object. So I am now just converting the image to base64 and sending with the rest of the form data and then converting it back again.

Here's a little but verbose snippet that sets the value of an image input field to it's base64 equivalent, then you can use something like `file_get_contents($base64)` or use Intervention image to make an actual image out of it eg: `Image::make($base64)`.

```
document.getElementById('image-input').onchange = function (event) {
    if (event.target.files.length > 0)
    {
        // Get selected file from input
        var selectedFile = event.target.files[0];

        // Check is valid image type
        if (selectedFile.type.match('image/png|image/jpeg|image/jpg'))
        {
            // Read the file
            var reader = new FileReader();
            reader.readAsDataURL(selectedFile);

            // When file has been read, set the input value to the file result (base64)
            reader.onload = function (e) {
                document.querySelector('input[name="image"]').value = e.target.result;
            };
        }
    }
}
```

In the long run though, making some kind of `$formData` magic variable we can pass that holds all of the real form data in some serialised state or whatever would be mega mega handy!

**Comment by ya-cha** [comment] 2023-10-24 04:47
Just in case someone runs into this: In Laravel 3 some inputs like `select` and I think also Checkboxes and Radio Buttons are not submitted anymore. This happens because the feature `supportDisablingFormsDuringRequest.js` disables them temporary. You can prevent this behaviour by adding `wire:ignore` to your `form`.

https://livewire.laravel.com/docs/wire-ignore

**Comment by JohanDBothma** [comment] 2023-12-08 06:11
> Just in case someone runs into this: In Laravel 3 some inputs like `select` and I think also Checkboxes and Radio Buttons are not submitted anymore. This happens because the feature `supportDisablingFormsDuringRequest.js` disables them temporary. You can prevent this behaviour by adding `wire:ignore` to your `form`.
> 
> https://livewire.laravel.com/docs/wire-ignore

I did not think that I'd see a response on this for Livewire 3 but this solved the issue for me, thank you so much!

**Comment by gbalduzzi** [comment] 2024-01-19 11:25
Thank you @ya-cha , I was going crazy trying to understand why only the select in my form was not working.

In my opinion the `$formData` syntax would be perfect for small and simple form elements in complex components.

@calebporzio would you be interested in a pull request implementing this feature? I may try to get it working in the next days

**Comment by Kamoba** [comment] 2024-03-01 01:31
Data binding is the easiest way to get form data sent.
```
```
<input wire:model="name" />
```

**Comment by gbalduzzi** [comment] 2024-06-07 08:34
Just FYI for anyone reading this:  I tested this again recently with 3.4 and select elements are properly submitted now using:

```
<form wire:submit="submit(Object.fromEntries(new FormData($event.target)))">
```
