### ISSUE TITLE
Nested component fire javascript multiple times

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#2363] opened 2021-01-15 16:53 UTC
### Description
I have a "parent-child" situation, which I am trying to use Livewire for. My issue is that the Javascript on the child component is fired off `x` times (where `x` is the number of times the nested component has been toggled). 

See the below video that demonstrates it:

https://user-images.githubusercontent.com/7851696/104755266-8382e980-575a-11eb-9178-6aac7d1501e4.mov

### Exact steps to reproduce
Consider the two components Master and Child:

```php
//Master.php
class Master extends Component
{
    public $visible = false;
    public function render()
    {
        return view('livewire.master');
    }
}
```
And the view file:
```blade
<div>
    <div class="p-4">Master component
        <br /><br />
        <a wire:click="$toggle('visible')" class="font-semibold text-blue-600">Toggle child.</a>
        @if ($visible)
            <livewire:child />
        @endif
    </div>
</div>
```

The child component looks like this:

```php
//Child.php
class Child extends Component
{
    public function doSomething(){
        $this->dispatchBrowserEvent('childAction', ['message' => 'Called!']);
    }

    public function render()
    {
        return view('livewire.child');
    }
}
```
And the view file for the child component:

```blade
<div class="p-4 my-6 bg-gray-50">
    <a>Child component visible.</a>
    <br /><br />
    <a wire:click="doSomething" class="font-semibold text-green-600">Method on the child.</a>

    <script type="text/javascript">
        console.log("Child loaded.");
        window.addEventListener('childAction', event => {
            console.log(event.detail.message);
        });
    </script>
</div>
```
### Stripped-down, copy-pastable code snippets
See the above.

**Context**
 - Alpine version: 2.7.3
 - Livewire version: 2.3.6
 - Laravel version: 8.12
 - Browser: Chrome

**Comment by marispro** [comment] 2021-01-15 22:22
Can you try to move script code into <head>?

**Comment by oliverbj** [comment] 2021-01-16 09:32
I can only move the `<script>` from the child into the head by using `@push`, but that doesn't work either:

```
//child.blade.php
@push('scripts')
    <script type="text/javascript">
        console.log("Child loaded.");
        window.addEventListener('childAction', event => {
            console.log(event.detail.message);
        });
    </script>
@endpush
```

And in my app layout file:

```html
<head>
....
@stack('scripts')
</head>
```

The `@push` never happens. I cannot see script tags in the rendered HTML.

**Comment by marispro** [comment] 2021-01-16 11:51
it should not work through push in this case, can you try to move script in `<head>` without push?

**Comment by oliverbj** [comment] 2021-01-16 13:24
@marispro not quite sure how that would work, as I am interested in having component-specific javascript on the child element.

**Comment by marispro** [comment] 2021-01-16 13:32
@oliverbj This is not how it supposed to be used - because each new component makes duplicate of same code. It should have some instance id or something.

**Comment by oliverbj** [comment] 2021-01-16 13:35
Even if I only inject the child component *one* time, and then instead of removing it on the toggle method, just toggle the visibility, it still fires multiple times:

```php
//Master.php
protected function showChild()
    {
        if(!$this->task){
            $this->task = true;
        }

        $this->visible = true;
    }

    protected function closeChild()
    {
        $this->visible = false;
    }

    public function toggleChild()
    {
        $this->visible ? $this->closeChild() : $this->showChild();
    }
```
```blade
<!-- master.blade.php -->
@if ($task)
       <div class="@if(!$visible) hidden @endif">
                <livewire:test.child />
     </div>
@endif
```

Sorry if I am misunderstanding something, but I cannot wrap my head around why it will trigger the JavaScript on the child component `x` number of times, if the child component is only appended *one* time.

**Comment by jeffchown** [comment] 2021-01-18 13:51
@oliverbj It looks to me like, every time you toggle the child component, you are adding an additional event listener which will lead to the multiple JavaScript calls/fires.  One way to fix the issue might be to call `removeEventListener` when the child is toggled ‘off’.

**Comment by joshhanley** [comment] 2021-01-30 20:39
There is a known issue with morphdom causing some registered actions to double up (like click handlers and Alpine's x-init) in situations where they have been conditionally added to the screen as part of a subsequent request.

Have a look at issue #763.

There is a fix for this being worked on, so I'm going to close this for now, so we can keep following it in #763.

If that issue gets fixed and this one then still happens, we can reopen this and investigate it further.

Hope this helps!

**Comment by squishythejellyfish** [comment] 2021-01-30 20:39
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed** 2021-01-30 20:39 UTC
