### ISSUE TITLE
Text nodes can go missing on re-renders (resubmission of #1344 with reproducible example)

### ISSUE THREAD

**Issue by mpbarlow** [livewire/livewire#1737] opened 2020-10-01 20:59 UTC
### Description

The issue describing text nodes going missing when surrounded by identical-looking nodes (#1344), was closed due to not having a copy-paste-able example. Please find below a minimal component that replicates the problem.

I have also created [a repo with nothing but a fresh Laravel install and this component](https://github.com/mpbarlow/livewire-dom-bug-minimal-replication) if that's preferable—all you need to do is a `composer install` and copy a .env file.

### Stripped-down, copy-pastable code snippets

*Test.php*

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Test extends Component
{
    public $page = 1;

    public function toggle()
    {
        $this->page = $this->page === 1 ? 2 : 1;
    }

    public function render()
    {
        return view('livewire.test');
    }
}
```

*test.blade.php*

```
<div>
  <span>{{ $page }}</span> of <span>2</span>
  <div>
    <button wire:click="toggle">@if ($page === 1) Click me @else And once more @endif</button>
  </div>
</div>
```
The example I've used mimics pagination, as this seems to be the most common time you'll see this issue. However, it will happen with any text node surrounded by identical looking nodes (same tag, same classes, same content, etc.).

When first loading the component you should see "1 of 2" and a button. Click the button and that will change to "2 of 2". Click it once more and it will change to "12" instead of "1 of 2"—the " of " text node goes missing.

I have seen this issue discussed elsewhere and people usually recommend adding a `wire:key` directive to the elements surrounding the text. My concern is that this is a band-aid over the issue rather than a fix. I understand the use of keys in aiding element tracking and re-use in lists, but if the diffing algorithm can lose track of nodes that seems like a bug to me?

Please let me know if I can provide any more info or assistance!

**Context**
- Livewire version: <= 2.2
- Laravel version: all
- Browser: all

**Comment by austenc** [comment] 2020-10-16 23:41
Livewire seems to be having trouble with the DOM-diffing in this example. 

Noticed that changing the second line of the template to this will fix it:
```
<span>{{ $page }}</span> <span>of</span> <span>2</span>
```
(added an additional `<span>` tag around `of`)

Perhaps it can be fixed in Livewire, but I'm not familiar enough with the dark corners of the dom-diffing to determine if it's possible or not. The [troubleshooting page](https://laravel-livewire.com/docs/2.x/troubleshooting) of the docs describes the issue. 

Nice job on providing a simple reproduction!

**Comment by mpbarlow** [comment] 2020-10-21 15:30
I should have some time this week to take a look, I'll see if I can put a PR together with a fix. I'm no expert on this sort of thing, but I think I've found the right place in the code to start digging at least.

As you've shown, it's at least simple to work around when it does happen!

**Comment by squishythejellyfish** [comment] 2020-10-29 21:26
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed by squishythejellyfish** 2020-10-29 21:25 UTC
