### ISSUE TITLE
Refreshing form

### ISSUE THREAD

**Issue by aminireza-ir** [livewire/livewire#1616] opened 2020-09-16 12:39 UTC
There is a bug in Livewire with Turbolink.
When we open a form with <a> tag in a Project with Livewire and Turbolink the form will be refreshed (with wire:submit.prevent).
But if we try to open the form without <a> tag in the project and open it directly in Browser it will be solved.

**Comment by austenc** [comment] 2020-10-16 18:04
@aminireza-ir can you perhaps create an example repo so this can easily be reproduced?

**Comment by calebporzio** [comment] 2020-10-21 19:39
Closing this because there isn't enough info to assist. Please re-submit with source code and more info if it persists!

**Closed by calebporzio** 2020-10-21 19:39 UTC
Labels: Needs Better Reproducibility
