### ISSUE TITLE
Empting the view cache or having multiple webservers triggers $wire errors on frontend

### ISSUE THREAD

**Issue by jimmypuckett** [livewire/livewire#1977] opened 2020-11-06 00:55 UTC
### Description

If you have a livewire component that is loaded up on the client's browser & empty the `storage/framework/views` folder, then preform an action that triggers livewire on the client, then you will get the error "Cannot read property '$wire' of undefined when running in multiple webservers".

### Exact steps to reproduce

We have a site running on docker containers behind an ELB behind CloudFlare.  The site runs perfect until we scale up with multiple servers.  We have several other sites running with the exact same configuration but not using LiveWire, so I feel very comfortable about the infrastructure.

To reproduce without multiple servers

* have a component loaded up on a browser with a click event to trigger a div update
* empty the "storage/framework/views" folder
* back on the browser client the time to make a livewire update (usually takes a 2nd request)
* should see the $wire issue

This may be unique to having a `x-init` in the component?

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.1
- Laravel version: 7.29.1
- Alpine version: 2.73.1
- Browser: Chrome & Safari

**Comment by calebporzio** [comment] 2020-11-10 14:27
Hi there, because it's a lot of extra work to recreate this issue. Please make it easier by providing a stripped-down code snippet of a component that uses `$wire` and will demonstrate this issue.

Also, is there more information you can provide that might give people more clues without having to have a multi-server setup to recreate this.

Closing. Re-open with more info when you can. Thanks!

**Comment by squishythejellyfish** [comment] 2020-11-10 14:27
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed** 2020-11-10 14:27 UTC

**Comment by calebporzio** [comment] 2020-11-10 14:30
Actually this could probably reproduced on a single server by clearing the view cache.

Livewire uses the caching phase of views to store unique keys to nested components.

That's how the backend properly tracks which child components have already been rendered.

It makes sense that issues would arrise with nested components and clearing the view cache. It also makes sense that this issue manifests itself in problems with `$wire` because `$wire` looks for the closest parent component, and maybe it finds a mis-match.

Anyhow. Going to keep this closed until someone can provide a simple example that uses nested components and a single-server with clearing the storage/framework/views folder

Thanks!

**Comment by jimmypuckett** [comment] 2020-11-10 14:41
Yes, that was the part of "clearing" the "storage/framework/views" part was about--both make the issue.

I will work on a simple example for the simple example for deleting the views folder.

I would think that anyone on Vapor would be having same issue?

**Comment by jimmypuckett** [comment] 2020-11-10 15:51
@calebporzio I understand that this is currently an edge case, but as more & more people move towards serverless architecture, then this will become more the "normal".

I don't mind digging into a solution, which I think should be tied to using Laravel's built-in caching engine so that the drivers can handle these situations.

If we were to make a PR that goes that direction, would you be interested or does that go against your vision?
