### ISSUE TITLE
Nested component vanishes into thin air :-)

### ISSUE THREAD

**Issue by ducopro** [livewire/livewire#36] opened 2019-07-02 20:39 UTC
**Describe the bug**
A list component renders a table and every row contains a nested component. After refreshing the parent component all the nested components are not in the DOM any more.

**To Reproduce**
See the two components attached to this issue

If the subcomponent has a root html element other than `DIV`
```html
<p>
    <b>X</b>
</p>
```

The problem exists.

If we change the root element to `DIV` everyhthing seems to work OK.

**Expected behavior**
Of course we need the nested components rendered again ....

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class BugList extends Component
{
    public $data;

    public function render()
    {
        $this->data = [
            ['id' => 1, 'animal' => 'Cat'],
            ['id' => 2, 'animal' => 'Dog'],
            ['id' => 3, 'animal' => 'Horse'],
            ['id' => 4, 'animal' => 'Fly'],
            ['id' => 5, 'animal' => 'Turtle'],
        ];

        return view('livewire.bug-list');
    }
}
```
```html
<div>

    <button class="btn btn-primary mb-4" wire:click="$refresh">Refresh and see subcomponent vanish</button>

    <table class="table table-responsive-lg table-hover">

        <thead>
        <tr>
            <th>Id</th>
            <th>Animal</th>
            <th>Sub Component</th>
        </tr>
        </thead>

        <tbody>
        @foreach($data as $record)
            <tr>
                <td>
                    {{$record['id']}}
                </td>
                <td>
                    {{$record['animal']}}
                </td>
                <td>
                    @livewire('bug-sub', $record['id'], key($record['id']) )
                </td>
            </tr>
        @endforeach
        </tbody>

    </table>

</div>
```

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class BugSub extends Component
{
    public function render()
    {
        return view('livewire.bug-sub');
    }

    public function mount($id){

    }
}
```

### Bad template
```html
<p>
    <b>X</b>
</p>
```
### Good template
```html
<div>
    <b>X</b>
</div>
```

**Comment by mikaeljorhult** [comment] 2019-08-11 09:18
Are non-div root elements supported?

I ran in to this issue using the latest version when trying to build a table component with the individual rows as nested components. The first render works fine but when responding to a click event the component is rendered empty.

**Comment by calebporzio** [comment] 2019-08-12 12:34
I seem to be able to have a `table` root for a parent, and a `tr` root for children inside the parent.

I'm guessing your problem is not adding `key()`s to each child component. Here is code that works:

Parent:
```html
<table>
    <tr>
        <th>Name <input type="text" wire:model="search"></th>
        <th><a wire:click.prevent="$refresh">hey</a></th>
        <th>Twitter Handle</th>
        <th></th>
    </tr>
    @foreach ($contacts as $contact)
        @livewire('contact-info', $contact, key($contact->id))
    @endforeach
</table>
```

Child:
```
<tr>
    <td>{{ $name }}</td>
    <td>{{ $nickname }}</td>
    <td>{{ $twitter_handle }}</td>
    <td>{{ $notes }}</td>
</tr>
```

Like I said, I'm guessing the issue is you not adding something like `key($contact->id)` to your child directives.

Let me know if this solves the problem for you

**Comment by mikaeljorhult** [comment] 2019-08-12 18:56
That looks very close to the code I have that's not working. I have the key in there.

Parent:
```php
<table>
    <thead>
        <tr>
            <th>E-mail</th>
        </tr>
    </thead>

    <tbody>
        @foreach($users as $user)
            @livewire('user', $user, key($user->id))
        @endforeach
    </tbody>
</table>
```

Child:
```php
<tr>
    <td wire:click="edit">
        @if($isEditing === 1)
            <input type="email" name="email" value="{{ $email }}" />
        @else
            {{ $email }}
        @endif
    </td>
</tr>
```

**Comment by calebporzio** [comment] 2019-08-15 02:48
Hi @mikaeljorhult, I'm guessing the issue you're having has something to do with `<tr>`s inside `<table>`s being really finicky. There are lots of strict rules that browsers obey about rending tables and rows.

Do you feel able to investigate if this is the distinction (does it work if the TRs are and TABLEs are DIVs?)

Just looking for some help in finding the fix as I'm pretty stacked at the moment. Thanks!

**Comment by mikaeljorhult** [comment] 2019-08-15 12:14
Yes, everything works fine with DIV elements so it seems to indeed be the type of element that's causing it. I have a vague memory of Vue having some problems with or workarounds for tables as well.

I can put an hour or two into investigating the issue. Do you have any good place to start in the code base?

**Comment by calebporzio** [comment] 2019-08-15 17:45
I would start by analyzing the rendered DOM output in DevTools and make sure all the elements that are supposed to be there are there.

Then it will probably be a lot of you digging through the `component/index.js` file where all the DOM diffing/patching magic happens. It's a little crazy to wrap your head around, but just start dropping `debugger` statements around and you'll start to get the feel for how it works.

Thanks for being willing to pitch in!

**Comment by calebporzio** [comment] 2019-08-23 14:36
nice. Just an FYI on that `key(encrypt(...`, `encrypt()` is really slow - I'd avoid it if at all possible. I'm assuming you don't want to expose the user id or something? just base64_encode() it

**Comment by jrseliga** [comment] 2019-08-23 15:47
@calebporzio totally, I had to do it because Livewire was throwing a console error if it was just `key($user->id)`. 
```
livewire.js?id=a2c2e6c3df2dd31e7e08:1 Uncaught (in promise) TypeError: Cannot read property 'includes' of null
    at livewire.js?id=a2c2e6c3df2dd31e7e08:1
    at Array.filter (<anonymous>)
    at Object.componentsListeningForEvent (livewire.js?id=a2c2e6c3df2dd31e7e08:1)
    at Object.emit (livewire.js?id=a2c2e6c3df2dd31e7e08:1)
    at livewire.js?id=a2c2e6c3df2dd31e7e08:1
    at Array.forEach (<anonymous>)
    at e.value (livewire.js?id=a2c2e6c3df2dd31e7e08:1)
    at e.value (livewire.js?id=a2c2e6c3df2dd31e7e08:1)
    at e.value (livewire.js?id=a2c2e6c3df2dd31e7e08:1)
    at Object.driver.onMessage (livewire.js?id=a2c2e6c3df2dd31e7e08:1)
```

Not yet obvious the minimum conditions necessary to replicate it. But high level:
1. Livewire Component that executes / listen for an event triggering a Scout search
2. This Component's blade file chunks this array of results
3. Each item in chunk is iterated over rendering a nested Livewire Component

Except for the chunking, this issue seemed somewhat _similar_ to my experience, just curious if `encrypt()` "resolved" the issue.

**Comment by defenestrator** [comment] 2019-09-03 22:09
Has anyone considered or tried defining a custom html element or Web Component for the root elemwnt of livewire components? Something like `<livewire>`?
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

I will explore it if no one here has hit a dead end with it already.

**Comment by calebporzio** [comment] 2019-09-04 13:42
Sorry @defenestrator, what would the use of `<livewire>` web component be? Super interesting, just don't know what it would accomplish for us.

Also, @jrseliga - thanks for the extra info. It's too complex for me to reproduce. It'd be great if you could restate the problem and steps to reproduce as simply as possible (ideally not involving Echo), and then maybe I can dig in and help. I know it's not easy to do, but it would be a huge help to me. Thanks!

**Comment by oliverbj** [comment] 2019-09-11 13:39
@jrseliga did you figure out another way around your problem, than to use `encrypt()`? I am experiencing the same, where I cannot `$this->emit()` from my component, if I don't use `key(encrypt(..)` in the view. I get the same console error as you.

**Comment by calebporzio** [comment] 2019-10-24 11:35
@oliverbj, can you post easily copy and pastable components for me to reproduce the issue?

**Comment by jrseliga** [comment] 2019-11-04 18:57
@calebporzio maybe we could hop on a quick Zoom call for 5-10 minutes and I can show you the issue?

**Comment by jgile** [comment] 2020-02-17 23:28
any movement on this?  experiencing same issue.  nested components throw a console error unless I use encrypt() or Str::random().  I'm uncertain as to why a random string for the key works, but a short id or string does not.

**Comment by calebporzio** [comment] 2020-03-14 04:54
Agreed, this is odd.

I would love it if someone could post the most minimal possible code that allows me to reproduce this issue. Otherwise, I can't help on it.

**Comment by WBDC** [comment] 2020-03-20 00:09
> Hey @ducopro,
> 
> I guess Livewire expects the root element to be `<div>`, much like the root element in Vue needs to be called `<template>`.
> 
> Is there a use case where you specifically don't want the root element to be called `<div>`?

@morpheus7CS 
I had `li` tag as my child route tag and after changing it to `div` it fixed the problem. 
There is a bit of styling issue with it now, but I can fix that easily. 

Although it would be very nice if we can use any route tag as long as there is one tag. @calebporzio  maybe you can consider if this can be / will be implemented. 

Thank you

**Comment by calebporzio** [comment] 2020-03-20 00:45
I'm willing to look into it, but I will need simple, copy and pastable code

**Comment by Dimonka2** [comment] 2020-06-12 14:00
Is there any update on `table `> `tr` issue?
I tried to make a table component with tr and result is really weird. For some reason all attributes `wire:id ` and `wire:initial-data` are rendered in the first `tr` and all following `tr`'s are not recognzed as components.

The first row looks like:

```html
 <tr wire:initial-data="{&quot;id&quot;:&quot;MFNPWkJPtqBVdOS3SYkN&quot;,&quot;name&quot;:&quot;flatform.table-row&quot;,&quot;redirectTo&quot;:false,&quot;events&quot;:[],&quot;eventQueue&quot;:[],&quot;dispatchQueue&quot;:[],&quot;data&quot;:{&quot;_id&quot;:&quot;row_10_0&quot;},&quot;children&quot;:[],&quot;checksum&quot;:&quot;ae6f9c641258e0bcba0f67308d9f8fe267739980d49b3887f8fa9ca89b430f79&quot;}"
        wire:id="MFNPWkJPtqBVdOS3SYkN"
        wire:initial-data="{&quot;id&quot;:&quot;WxSxt6hMsn4RulpyLTyZ&quot;,&quot;name&quot;:&quot;flatform.table-row&quot;,&quot;redirectTo&quot;:false,&quot;events&quot;:[],&quot;eventQueue&quot;:[],&quot;dispatchQueue&quot;:[],&quot;data&quot;:{&quot;_id&quot;:&quot;row_9_0&quot;},&quot;children&quot;:[],&quot;checksum&quot;:&quot;3198bf4923884cafdf1836fc74e22c15f240e28ded297bba292da76b7fda0c09&quot;}"
        wire:id="WxSxt6hMsn4RulpyLTyZ"
        wire:initial-data="{&quot;id&quot;:&quot;ON57BmKr5l34MyWCXakN&quot;,&quot;name&quot;:&quot;flatform.table-row&quot;,&quot;redirectTo&quot;:false,&quot;events&quot;:[],&quot;eventQueue&quot;:[],&quot;dispatchQueue&quot;:[],&quot;data&quot;:{&quot;_id&quot;:&quot;row_8_0&quot;},&quot;children&quot;:[],&quot;checksum&quot;:&quot;a60ce9e2b31403bf74b589e04e6512fc2ff9334c1135e083e5050fb05f50f43a&quot;}"
        wire:id="ON57BmKr5l34MyWCXakN"
        wire:initial-data="{&quot;id&quot;:&quot;ZjFZThxJlxZiwpdfOrX4&quot;,&quot;name&quot;:&quot;flatform.table-row&quot;,&quot;redirectTo&quot;:false,&quot;events&quot;:[],&quot;eventQueue&quot;:[],&quot;dispatchQueue&quot;:[],&quot;data&quot;:{&quot;_id&quot;:&quot;row_7_0&quot;},&quot;children&quot;:[],&quot;checksum&quot;:&quot;3ae5baea0b1dbea2f6708de90b3ed2686430a2e6cf96b951f6e28c396ba91f03&quot;}"
        wire:id="ZjFZThxJlxZiwpdfOrX4"
        wire:initial-data="{&quot;id&quot;:&quot;G68wAE2whkg4cfNQpP3o&quot;,&quot;name&quot;:&quot;flatform.table-row&quot;,&quot;redirectTo&quot;:false,&quot;events&quot;:[],&quot;eventQueue&quot;:[],&quot;dispatchQueue&quot;:[],&quot;data&quot;:{&quot;_id&quot;:&quot;row_6_0&quot;},&quot;children&quot;:[],&quot;checksum&quot;:&quot;888d34e0679e178a4d223b75a1a5c75914fedcf503002d72a753ec5f9930763b&quot;}"
        wire:id="G68wAE2whkg4cfNQpP3o"
        wire:initial-data="{&quot;id&quot;:&quot;UbtXyWTaLi9dfwhD7vUe&quot;,&quot;name&quot;:&quot;flatform.table-row&quot;,&quot;redirectTo&quot;:false,&quot;events&quot;:[],&quot;eventQueue&quot;:[],&quot;dispatchQueue&quot;:[],&quot;data&quot;:{&quot;_id&quot;:&quot;row_5_0&quot;},&quot;children&quot;:[],&quot;checksum&quot;:&quot;7553b631552f1d0696874d72d3d04b44469f90b88190c2ed991f06f37d563b59&quot;}"
        wire:id="UbtXyWTaLi9dfwhD7vUe"
        wire:initial-data="{&quot;id&quot;:&quot;OiPxX2xRNMHA2cK7MHUI&quot;,&quot;name&quot;:&quot;flatform.table-row&quot;,&quot;redirectTo&quot;:false,&quot;events&quot;:[],&quot;eventQueue&quot;:[],&quot;dispatchQueue&quot;:[],&quot;data&quot;:{&quot;_id&quot;:&quot;row_4_0&quot;},&quot;children&quot;:[],&quot;checksum&quot;:&quot;e4b8a878c05515b95e2f9304b0b096bbc3c5bd68cb9cdfeaafe908051215c4b5&quot;}"
        wire:id="OiPxX2xRNMHA2cK7MHUI"
        wire:initial-data="{&quot;id&quot;:&quot;HUw0CSjMKLYaqGewbuXZ&quot;,&quot;name&quot;:&quot;flatform.table-row&quot;,&quot;redirectTo&quot;:false,&quot;events&quot;:[],&quot;eventQueue&quot;:[],&quot;dispatchQueue&quot;:[],&quot;data&quot;:{&quot;_id&quot;:&quot;row_3_0&quot;},&quot;children&quot;:[],&quot;checksum&quot;:&quot;76f5416f5fbcf55b6ef0a63d35586725d2a7628807f3be5440ca5224ec935eb7&quot;}"
        wire:id="HUw0CSjMKLYaqGewbuXZ"
        wire:initial-data="{&quot;id&quot;:&quot;eqrWlKFFpzG4SudLkWz4&quot;,&quot;name&quot;:&quot;flatform.table-row&quot;,&quot;redirectTo&quot;:false,&quot;events&quot;:[],&quot;eventQueue&quot;:[],&quot;dispatchQueue&quot;:[],&quot;data&quot;:{&quot;_id&quot;:&quot;row_2_0&quot;},&quot;children&quot;:[],&quot;checksum&quot;:&quot;f14f80a8b1f55d94626a8a19c1992005b078a110b582248b245ad32a29bd3f5a&quot;}"
        wire:id="eqrWlKFFpzG4SudLkWz4"
        wire:initial-data="{&quot;id&quot;:&quot;wYdqWGoQ7009MEOT6PbW&quot;,&quot;name&quot;:&quot;flatform.table-row&quot;,&quot;redirectTo&quot;:false,&quot;events&quot;:[],&quot;eventQueue&quot;:[],&quot;dispatchQueue&quot;:[],&quot;data&quot;:{&quot;_id&quot;:&quot;row_1_0&quot;},&quot;children&quot;:[],&quot;checksum&quot;:&quot;521f747115cfbb43bebf67e460ff34ee07ac44d95ff2938a6de0f5edf8fdf1f5&quot;}"
        wire:id="wYdqWGoQ7009MEOT6PbW">
        <td>...
```
Really strange.

**Comment by calebporzio** [comment] 2020-06-21 16:17
@Dimonka2 what does the raw HTML on page load look like for that first TR. I'm curious what get's outputed from the Livewire

**Comment by calebporzio** [comment] 2020-06-23 18:37
I'm going to close this issue as it contains many (seemingly) unrelated issues.

Feel free to re-submit a fresh issue with THOROUGH steps to reproduce (including stripped down, copy and pastable code)

Thanks!

**Closed by calebporzio** 2020-06-23 18:37 UTC

**Comment by Dimonka2** [comment] 2020-06-23 18:40
> @Dimonka2 what does the raw HTML on page load look like for that first TR. I'm curious what get's outputed from the Livewire

Good question. Actually I found that was my bug. I was giving over and over the same html to the livewire view, that is why id's were many times injected. But for some reason table still not rendered correctly. Last element does not getting `initial:data` after pressing on paginator.. The work around was kind of strange. 
If I render component manually like:
 
`$response = \Livewire\Livewire::mount('table-row', ['row' => $html, '_id' => $id]);`

then it renders correctly all the time.. Not sure what may cause it.

**Comment by Slowwie** [comment] 2020-08-08 09:53
My nested component vanishes also into air :-).

I have a parent component (trix editor) - It works exactly like in the sceencast. 

And I have a nested livewire component: 

`           <div>
                <livewire:select-language key="question-lang"/>
            </div>`

All works fine - but when I insert some text into the trix editor, the nested component disappears. 
I can prevent this behavior by writing wire:ignore onto the surrounding div of the nested component. 

But this can not be the solution right?

**Comment by muhammad-tanveerullah** [comment] 2021-03-27 03:11
Hi there, if someone is still facing issues with this, we can just do a simple fix until we have an actual fix in the livewire itself.

You just have to add and ID to the child component root tag. 

Parent Component:
<table>
   <thead></thead>
   <tbody>
        @foreach($users as $key=>$user)
            <livewire:user-info :user="$user :key="$user->id" />
        @endforeach
  </tbody>
<table>

Child Component:
<tr id="{{$user->id}}">  //Add this and you should see it starts working and you don't have to have div tag as root tag
   <td></td>
<tr>


Thanks!!
