### ISSUE TITLE
Wire:Poll Not Refreshing Nested Component

### ISSUE THREAD

**Issue by Chazza** [livewire/livewire#2670] opened 2021-03-25 22:37 UTC
### Description
When using nested components, `wire:poll` doesn't refresh the component.

### Exact steps to reproduce
1. Create a component, with a `wire:poll`.
2. Add a FOR loop, which adds another component.

### Stripped-down, copy-pastable code snippets

__Non Functional__
```php
<div class="mt-10 grid gap-4 sm:grid-cols-2 sm:gap-6 lg:grid-cols-3 lg:gap-8" wire:poll>
    @foreach($auctions as $auction)
        <livewire:auction-card :auction="$auction" :key="$auction->uuid" />
    @endforeach
</div>
```

__Functional__
```php
<div class="mt-10 grid gap-4 sm:grid-cols-2 sm:gap-6 lg:grid-cols-3 lg:gap-8" wire:poll>
    @foreach($auctions as $auction)
        <div :key="$auction->uuid">
            <h3 class="text-white">{{ $auction->item_name }}</h3>
            <h3 class="text-white">{{ $auction->time_left }}</h3>
        </div>
    @endforeach
</div>
```

**Context**
- Livewire version: Latest
- Laravel version: Latest
- Alpine version: Latest
- Browser: Tested on Chrome & Safari

**Comment by joshhanley** [comment] 2021-03-29 20:26
@Chazza once Livewire components are setup, they are completely isolated from each other. So wire:poll on the parent component won't touch the child components.

You either need to use events to communicate between the parent and child components, or you need to get creative with wire:key which makes Livewire think each child component is actually new component so it removes the old one and adds the new one with the new data.

Personally, I would recommend not using child Livewire components if they need to be refreshed every time the parent is, and instead just use blade components instead.

Hope this helps!

**Comment by Chazza** [comment] 2021-03-29 20:37
> @Chazza once Livewire components are setup, they are completely isolated from each other. So wire:poll on the parent component won't touch the child components.
> 
> You either need to use events to communicate between the parent and child components, or you need to get creative with wire:key which makes Livewire think each child component is actually new component so it removes the old one and adds the new one with the new data.
> 
> Personally, I would recommend not using child Livewire components if they need to be refreshed every time the parent is, and instead just use blade components instead.
> 
> Hope this helps!

Thanks Josh, currently using a unique key for the current time + the UUID of the item.

bur may have to consider not making it a component.

**Comment by joshhanley** [comment] 2021-03-29 20:45
@Chazza yep that's how I'd do it. Sometimes you need them to be child components so that's how I structure the keys so they refresh every time.

Only issue is, if the user has interacted with one of the child components, and the wire:poll happens, the child component will be wiped out so any changes from user interaction will be gone. But if it's just informational (not interactive) then should be fine.

Another option is to generate a unique key (using something like `uniqid()`) as a property on the parent component and use that in place of the time so instead you are using `$uniqueKey + UUID` what this allows is, if the unique key hasn't changed, then child components won't be wiped out (but it won't get any updates), but when you are ready for them to all be replaced, you just change the unique key to a new `uniqid()` and then they will all update.

But yeah I'm going to close this as it's not a bug that the child components aren't refreshed by the parent.

Hope this helps!

**Comment by squishythejellyfish** [comment] 2021-03-29 20:45
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed** 2021-03-29 20:45 UTC
