### ISSUE TITLE
Test Livewire inside a Package

### ISSUE THREAD

**Issue by jonassiewertsen** [livewire/livewire#813] opened 2020-04-13 19:23 UTC
I did set up Livewire inside a Laravel package, which does work great. The testing is throwing an error though. 

```php
ErrorException : Undefined index: dom

STACKTRACE
vendor/livewire/livewire/src/Testing/Concerns/MakesAssertions.php:30
```

There is a big chance, that my tests aren't set up correctly. I did try different things, but could not get it working.
```php
use Jonassiewertsen\Something\Http\Livewire\Shop;

dd(Livewire::test(Shop::class));
```

There is some output, but the content response is giving me `<title>Not Found</title>`

**To Reproduce**
1. Start building a Laravel package
2. Load the component inside my packageServiceProvider
```php
Livewire::component('something::shop', \Jonassiewertsen\Something\Http\Livewire\Shop::class);
```
3. Set up the views etc. and get it working in the browser.
4. Set up the PHPUnit Test0
```php
use Jonassiewertsen\Something\Http\Livewire\Shop;

Livewire::test(Shop::class)->assertSee('something');
```

5. Run the test to receive the error

**Additional context**
I am running Laravel 6

**Comment by calebporzio** [comment] 2020-06-22 18:51
The steps to reproduce this are too involved, and the need is not a high priority.

I'm going to close this for now.

Re-submit if you've looked into the problem deeper and have a suggestion. Thanks!

**Closed by calebporzio** 2020-06-22 18:51 UTC

**Comment by edgrosvenor** [comment] 2020-07-26 04:10
@lancepioch I test in Livewire in packages all the time without trouble and just ran into this for the first time. The problem isn't actually Livewire-related. You'd probably find any routes you try to test in this test suite would return a 404. The APP_URL value is wrong. Set that correctly and your tests should pass.
