### ISSUE TITLE
Site breaks after upgrade to 1.0.1

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#656] opened 2020-02-29 09:54 UTC
**Describe the bug**
I created a dashboard using livewire 0.7.4. I checked the upgrade guide and I wasn't using any of the features that changed in this update, so I upgraded, and all of my `select` elements broke.
I have public properties like `language_id` and the `select`s would return an integer to set these properties, but after the update they would return `array`s. So I had to downgrade.

Any ideas why this is happening?

**Comment by mokhosh** [comment] 2020-03-26 15:11
Doesn't anyone else have this problem? I should be getting a simple `string` right? But I'm getting an array like this:
```php
Array:1 [
  "value" => "option value"
]
```

**Comment by mokhosh** [comment] 2020-03-26 16:10
OK further head scratching has led me to this: The problem only arises when I use `Choices`. But the strange thing is, it doesn't happen if I downgrade livewire to 0.7.4.
What is it that makes this combo non compatible?

https://github.com/jshjohnson/Choices

**Comment by mokhosh** [comment] 2020-03-26 17:15
I'm fixing it with this tedious hack right now:
```php
public function updatingIcon($value)
{
    $this->icon = $value['value'];
}

public function updatedIcon($value)
{
    $this->icon = $value['value'];
}
```

**Comment by lancepioch** [comment] 2020-05-15 18:19
@mokhosh Is this still an issue with the latest version of Livewire?

**Comment by mokhosh** [comment] 2020-05-16 13:22
@lancepioch Yes, still there

**Comment by nuernbergerA** [comment] 2020-05-19 06:06
@mokhosh just guessing
could it be a multi-select thing where `Choices` treats an element always as multi-select and therefore sends an `array`?

If not can you share code and steps to reproduce?

**Comment by mblarsen** [comment] 2020-05-19 06:46
> If not can you share code and steps to reproduce?

@mokhosh You could provide an example in phpsandbox.io

**Comment by mokhosh** [comment] 2020-05-19 11:03
@nuernbergerA I think it is a problem with `Choices` but I don't know why it doesn't happen in `0.7.4`

```html
<div x-data x-init="new Choices($refs.select)">
  <select x-ref="select" wire:model="category_id">
    <option value="">Select an item</option>
    <option value="1">Item 1</option>
    <option value="2">Item 2</option>
  </select>
</div>

<script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js" defer></script>
```

```php
<?

use Livewire\Component;

class Something extends Component
{
  public $category_id;

  protected $rules = [
    'category_id' => 'required|integer',
  ];

  public function updated($field)
  {
    $this->validateOnly($field, $this->rules);
  }
  // Property [categories] does not exist on this collection instance.
```

I think this is enough to reproduce, tell me if it wasn't. Try this with `0.7.4` which is ok and with `1.1.0` which is not.

@mblarsen I tried it to make things easier, but it didn't let me do `php artisan make:livewire`.

**Comment by nuernbergerA** [comment] 2020-05-20 15:48
@mokhosh I followed your steps and couldn't reproduce an error.

I created a repo with a fork https://github.com/nuernbergerA/laravel-issues/compare/issue-656

I switched version and for me, it works fine

**Comment by mokhosh** [comment] 2020-05-22 10:21
@nuernbergerA Thanks for taking the time, things that I noticed in your project:
1. You don't have Alpine.js imported do you?
2. `choices.js` should be imported in `welcome.blade.php`, you can't put script tags inside livewire components.
3. You don't have `choices.css` (this one is on me i guess)

So this is `welcome.blade.php`

```php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Livewire Issues</title>
        @livewireStyles
        <link href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css"  rel="stylesheet">
    </head>
    <body>
        @livewire('something')
        @livewireScripts
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
        <script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js" defer></script>
    </body>
</html>
```

And you remove `choices.js` from inside the livewire view, and you will hopefully get the error.

**Comment by nuernbergerA** [comment] 2020-05-22 14:50
@mokhosh yea you are totally right
I was able to reproduce and found the [breaking change](https://github.com/livewire/livewire/blob/2799f093d6d5d1faeabffafef490f096b60d389a/js/node_initializer.js#L63)

**Comment by KeironLowe** [comment] 2020-06-12 06:41
I'm also having the same issue, using a multi-select dropdown and Choices. Livewire is only sending a single value to the server rather than all the selected options.

**Comment by KeironLowe** [comment] 2020-06-12 06:47
It looks like choices.js isn't setting the `selectedOptions` property on the select box. I'm not sure if that's used by Livewire, let me know if it is and I'll open a ticket on the Choices.js repo.

**Comment by calebporzio** [comment] 2020-06-24 14:29
It looks like Choices dispatches a "change" event (That Livewire is listening to with wire:model) that looks like this:
![image](https://user-images.githubusercontent.com/3670578/85574259-9be7b700-b604-11ea-9cfd-435016019576.png)

Notice that this change event has a .detail property with a value of `{value: 1}`

Livewire's intended behavior is:
* If it's a native "change" event, then use the target's `.value` property
* If it's a "change" event of type: CustomEvent, then use the event's `.detail` property

So it makes sense that it's behaving this way.

There are a number of workarounds for integrating with Choices properly, but I haven't really dug deeply myself.

Closing this issue for now, others are welcome to post tips for integrating, and eventually I hope to do a tutorial on it.

Thanks!

**Closed by calebporzio** 2020-06-24 14:29 UTC
