### ISSUE TITLE
Adding/removing classes causes input contents to disappear

### ISSUE THREAD

**Issue by marksalmon** [livewire/livewire#146] opened 2019-08-07 22:38 UTC
**Describe the bug**

I have a problem when I dynamically add/remove css classes to an input or textarea component, for example to display dirty/saved state. 

If I click or tab into a textarea/input with a dynamically added class *from* another input that triggers a  ```change``` event contents of the styled input/textarea vanish.

The value remains present in the data attribute of the livewire component, and if I emit another change event in the form component again, the value comes back on the next livewire refresh

It happens whether the css classes are modified in the blade template like: 

```php
<input class="... {{ $saved ? 'border-green-500' : ''}}">
```

or in the javascript like:

```js
window.livewire.on('saved', function(e) {
    document.getElementsByName(e)[0].add('border-green-500')
})
```

**To Reproduce**
1. Build a livewire component form with at least 2 properties lazy wired to textareas
```php
class DisappearingValue extends Component
{
    public $foo;
    public $bar;

    public function mount()
    {
        $this->foo = 'foo';
        $this->bar = 'bar';
    }

    public function render()
    {
        return view('livewire.disappearing-value');
    }
}
```

```html
<div>
    <textarea id="foo" wire:model.lazy="foo" cols="30" rows="10"></textarea>
    <textarea id="bar" wire:model.lazy="bar" cols="30" rows="10"></textarea>
</div>
```

2. Use the dev console to apply a class to one of the textareas
```js
document.getElementById('foo').classList.add('bg-pink-300')
```

3. Edit the contents of the other, not-styled, textarea

4. Click directly into the styled textarea

5. See error

**Expected behaviour**
I would expect nothing to happen

**Screenshots**

![Vanishing](https://user-images.githubusercontent.com/7000886/62660546-38aa5300-b966-11e9-93a6-a79d6a62896d.gif)

**Desktop (please complete the following information):**
 - Version 75.0.3770.142 (Official Build) (64-bit)

**Additional context**
This is not a big deal. I can work around this by using styling classes on a wrapper div around the actual input element, just seems strange.

**Comment by calebporzio** [comment] 2019-08-08 16:41
Hey @marksalmon,

This is actually desired behavior. If you change the HTML with javascript (in the case of your .classList.add), then when Livewire updates, it will get different DOM from the backend and wipe out your changes.

If you MUST add classes via JavaScript and don't want Livewire to wipe them, you can add a `wire:ignore` attribute to the element you are adding classes to.

Here is your template tweaked to not wipe the pink background:

```html
<div>
    <textarea id="foo" wire:model.lazy="foo" cols="30" rows="10" wire:ignore></textarea>
    <textarea id="bar" wire:model.lazy="bar" cols="30" rows="10"></textarea>
</div>

```

You also mentioned that this is still not working with dynamically added classes from Blade? Can you provide the code for the component class and template, so I can replicate this behavior on my end? Thanks!

**Comment by marksalmon** [comment] 2019-08-09 09:15
Thanks @calebporzio,

I didn't explain myself very well. I understand why the **class** is not there when livewire regenerates the DOM, and this is indeed my desired behaviour in this case.

The issue is that the **value** of the input/textarea disappears, although is still correct in the livewire data attribute and returns when the dom is refreshed again. (in the above GIF when I click into the pink textarea the word 'world' disappears, without any other keystrokes or mouse actions.) The risk is that if the user 

This issue occurs whether the class is added by js or livewire.

Here is the example php code:

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class DisappearingValue extends Component
{
    public $foo;
    public $bar;
    public $saved;

    public function mount()
    {
        $this->foo = 'foo';
        $this->bar = 'bar';
    }

    public function updated($name, $value)
    {
        $this->saved = $name;
    }

    public function render()
    {
        return view('livewire.disappearing-value');
    }
}
```

```php
<div>
    <textarea wire:model.lazy.dirty="foo" class="m-4 border rounded {{ $saved === 'bar' ? 'border-2 border-red-500' : 'border-teal-500' }}"></textarea>
    <textarea wire:model.lazy.dirty="bar" class="m-4 border rounded {{ $saved === 'bar' ? 'border-2 border-red-500' : 'border-teal-500' }}"></textarea>
</div>
```

I have confirmed this in a fresh laravel app: https://github.com/marksalmon/amianidiot
to reproduce:

1. Type into the first textarea. 
2. Tab or click into the second textarea. This will cause the 'change' event of the first textarea and the border class will change.
3. Type into the second textarea.
4. Click back into the first textarea, which will cause the change event from the second textarea and wipe the value from the first.

**Comment by WBDC** [comment] 2020-02-04 20:23
Hi, 
I have the same issue here. 

`<div class="form-group">
                            <label for="priority" class="col-md-4 control-label">Priority</label>

                            <div class="col-md-6">
                                <select id="priority" type="" class="form-control {{ $errors->has('priority') ? ' is-invalid' : '' }}" name="priority" wire:model="priority">
                                    <option value="">Select Priority</option>
                                    <option value="low">Low</option>
                                    <option value="medium">Medium</option>
                                    <option value="high">High</option>
                                </select>

                                @if ($errors->has('priority'))
                                    <span class="invalid-feedback" role="alert" >
                                        <strong>{{ $errors->first('priority') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>`

I don't even need to click in/out from the textboxes (in my case I have 1 textarea in this form). Som charaters are disappearing. If I type fast and the minimum required character count doesn't cause calidation error, then the characters are intact. 

I think its because dynamically adding the error message perhaps. 
---
Edit: I've added the error message placeholder as static and still doing it. 


Thanks

**Comment by calebporzio** [comment] 2020-03-14 16:28
Thanks for that amazing repo to reproduce this issue @marksalmon - will be fixed in the next release.

**Closed** 2020-03-14 16:28 UTC
Labels: Type: Bug
