### ISSUE TITLE
Redirect to same URL with a fragment

### ISSUE THREAD

**Issue by dsazup** [livewire/livewire#891] opened 2020-04-28 20:23 UTC
**Describe the bug**
I am not exactly sure if this is a bug, but it is not the behavior I would expect. Let's say I am on `/account#billing` and I click on an action which does `return redirect()->to('account#billing')` - it does nothing. It does not redirect me. I believe this is because `window.location.href` does not think the location has changed.

**Expected behavior**
A full page reload

**To Reproduce**
1. Make sure you are on a URL with #hashtag such as `/account#billing`
2. Click on a button that fires an action, which returns redirect to `/account#billing`
3. Nothing happens

**Comment by lancepioch** [comment] 2020-04-28 23:36
Thanks, this is a duplicate of #289

**Closed by lancepioch** 2020-04-28 23:36 UTC
