### ISSUE TITLE
Loading target for action with argument

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#1965] opened 2020-11-03 20:52 UTC
### Description
I have a loop within which there are buttons that trigger an action and have loading states. So:
```php
@foreach($accounts as $account)
    <button wire:click="edit({{ $account->id }})">
        <x-icon.pencil wire:loading.remove wire:target="edit"/>
        <x-icon.spinner wire:loading wire:target="edit"/>
    </button>
@endforeach
```
But when I click on one, all of them get the loading state. I used to do this in version one:
```php
@foreach($accounts as $account)
    <button wire:click="edit({{ $account->id }})">
        <x-icon.pencil wire:loading.remove wire:target="edit({{ $account->id }})"/>
        <x-icon.spinner wire:loading wire:target="edit({{ $account->id }})"/>
    </button>
@endforeach
```
But that doesn't work in v2.

**Comment by austenc** [comment] 2020-11-05 16:00
Hey @mokhosh this is on the roadmap, and is a duplicate of https://github.com/livewire/livewire/issues/1780 👍

**Comment by mokhosh** [comment] 2020-11-05 16:31
As the great @calebporzio once said on that issue:
> Yep! Good to know there's more demand for it thought.

😄
Thanks @austenc

**Comment by squishythejellyfish** [comment] 2020-12-01 15:18
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment] 2020-12-01 15:18
On the roadmap.

**Closed by squishythejellyfish** 2020-12-01 15:18 UTC

**Comment by ejulfaey** [comment] 2021-05-26 20:08
Does is support with multiple target? Below code is not working.


                                                                                                                                                                                       
        @foreach($cars as $car)                                                                                                                                                                                  
        <div wire:loading.flex wire:target="updateStatus('add', '1'), updateStatus('remove', '1')" class="justify-content-center p-2">
            <div class="spinner spinner-success"></div>
        </div>
        <div wire:loading.remove wire:target="updateStatus('add', '1'), updateStatus('remove', '1')">
            <button wire:click="updateStatus('add', 1)" class="btn btn-icon btn-sm btn-outline-danger">
                <i class="uil uil-multiply"></i>
            </button>
            <button wire:click="updateStatus('remove', 1)" class="btn btn-icon btn-sm btn-outline-danger">
                <i class="uil uil-multiply"></i>
            </button>
        </div>
        @endforeach

**Comment by argonzalez2016** [comment] 2021-09-12 17:51
> Does is support with multiple target? Below code is not working.
> 
> ```
>     @foreach($cars as $car)                                                                                                                                                                                  
>     <div wire:loading.flex wire:target="updateStatus('add', '1'), updateStatus('remove', '1')" class="justify-content-center p-2">
>         <div class="spinner spinner-success"></div>
>     </div>
>     <div wire:loading.remove wire:target="updateStatus('add', '1'), updateStatus('remove', '1')">
>         <button wire:click="updateStatus('add', 1)" class="btn btn-icon btn-sm btn-outline-danger">
>             <i class="uil uil-multiply"></i>
>         </button>
>         <button wire:click="updateStatus('remove', 1)" class="btn btn-icon btn-sm btn-outline-danger">
>             <i class="uil uil-multiply"></i>
>         </button>
>     </div>
>     @endforeach
> ```

I am having the same issue. If I have any actions with a parameter, none of the other actions work with wire:target.
