### ISSUE TITLE
@v2 Component Pagination causes 404 error

### ISSUE THREAD

**Issue by JustSteveKing** [livewire/livewire#1482] opened 2020-09-07 13:10 UTC
### Description

Using Laravel 7.24 and Livewire 2.0 after following the upgrade guide, Pagination links now open a modal window with a 404 error when hitting the route: `/livewire/message/`

### Steps to reproduce

Upgrade following the documented approach on the Livewire website, do not upgrade anything else.  Click on a pagination link to go to the next page. You should see a modal window pop up that contains the standard 404 error page for Laravel. You will also notice that the component endpoint is no longer called, instead livewire/message is called which causes the 404 itself.

**Context**
- Livewire version: 2.0
- Laravel version: 7.24
- Browser: Chrome

**Comment by JustSteveKing** [comment] 2020-09-07 13:14
This is my own fault 🤦 kinda

A step that needs adding to the upgrade guide is to also ensure you republish livewire assets:

```bash
$ php artisan livewire:publish
```

This has solved my problem. I will leave this for @calebporzio to close when ready

**Comment by JustSteveKing** [comment] 2020-09-07 13:17
I have craeted a PR in the docs to add this step now: https://github.com/livewire/docs/pull/219

**Comment by calebporzio** [comment] 2020-09-07 16:33
Thanks for the solution. I added it to the upgrade guide.

**Comment by coolsam726** [comment] 2020-09-10 22:25
> ### Description
> 
> Using Laravel 7.24 and Livewire 2.0 after following the upgrade guide, Pagination links now open a modal window with a 404 error when hitting the route: `/livewire/message/`
> ### Steps to reproduce
> 
> Upgrade following the documented approach on the Livewire website, do not upgrade anything else. Click on a pagination link to go to the next page. You should see a modal window pop up that contains the standard 404 error page for Laravel. You will also notice that the component endpoint is no longer called, instead livewire/message is called which causes the 404 itself.
> 
> **Context**
> 
>     * Livewire version: 2.0
> 
>     * Laravel version: 7.24
> 
>     * Browser: Chrome

The issue is still persistent on my end, but ONLY when I am serving my project from a sub-path of the root domain.

**Comment by coolsam726** [comment] 2020-09-11 09:59
This issue is linked to   #1535

**Comment by calebporzio** [comment] 2020-09-11 23:14
Closing this as duplicate, thanks!

**Closed by calebporzio** 2020-09-11 23:14 UTC
