### ISSUE TITLE
 Unexpected token > in JSON at position 1239

### ISSUE THREAD

**Issue by ousid** [livewire/livewire#1310] opened 2020-07-24 10:33 UTC
### Description

After deploying my app into a hosted server I got this issue when trying to submit a form and it works just fine in the local environment  

![livewire issue](https://user-images.githubusercontent.com/21012933/88382954-71bf1b80-cda1-11ea-9469-7e2dd69cb50c.png)

 

### Steps to reproduce

```php
    public function send()
    {
        $this->validate([
            'form.name'  => 'required|string|min:2|max:30',
            'form.email' => 'required|email|max:200',
            'form.phone_number'  => 'sometimes',
            'form.title' => 'required|string',
            'form.body'  => 'required|string|min:10',
        ], [], [
            'form.name'  => __('Name'),
            'form.email' => __('Email'),
            'form.phone_number'  => __('Phone Number'),
            'form.title' => __('Reason'),
            'form.body'  => __('Message'),

        ]);

        AppContactUs::create($this->form);


        $this->form['name'] = '';
        $this->form['email'] = '';
        $this->form['phone_number'] = '';
        $this->form['title'] = '';
        $this->form['body'] = '';

        session()->flash('success', __('Shiny Alert"'));
  }

```
**Context**
- Livewire version: 1.1
- Laravel version: ^7.0
- Browser: Chrome, Firefox

**Comment by tnylea** [comment] 2020-08-10 03:30
@ousid 

Same thing on my end. Did you find a possible solution for this?

Everything works fine on my local, but when I deploy to my server I'm also getting this same error. I'll be doing some more testing to try and figure out the root of the cause :)

I'm on Laravel ^7.0 and Livewire 1.3.2, Browser: Chrome, Firefox

**Comment by austenc** [comment] 2020-10-15 21:43
@ousid @tnylea 

Could you provide more information about your server environment? 

- PHP Version
- Livewire version (if changed now)
- Anything else that might be out of the ordinary with how you're hosting the production environment? (proxies, docker, etc...)

**Comment by sprklinginfo** [comment] 2020-10-16 00:47
I got the same issue when handling the checkout form submit in my livewire component:
 'index.js:50 Uncaught (in promise) SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at index.js:50

public function checkoutFormSubmit()
    {
        if (auth()->user()) {
            $this->rules['billing_email'] = 'required|email';
            $this->billing_email = auth()->user()->email;
        }

        $this->validate();

        $checkout = new CheckoutController;
        $checkout->attemptPay(request()->all());
    }
The CheckoutController will call the Omnipay PayPal gateway. 

PHP version: 7.3.18
Livewire version: 2.2.9
I am still on my local development machine which uses docker.

**Comment by calebporzio** [comment] 2020-10-16 16:45
There is insufficient info to reproduce this issue. Closing for now.

Please re-submit with copy-and-pastable code that has been trimmed down to be the minimum amount of code necessary to reproduce the problem.

Thanks!

**Closed by calebporzio** 2020-10-16 16:45 UTC

**Comment by betoflakes** [comment] 2021-03-09 07:21
I have the same issue.
