### ISSUE TITLE
Cannot read property 'data' of null

### ISSUE THREAD

**Issue by rumrhky** [livewire/livewire#798] opened 2020-04-09 08:30 UTC
**TypeError: Cannot read property 'data' of null**
When wrapping child component with multiple div ( more than one ) livewire event fails or get error.

my `ComponentA`
```
public $listeners = ['trigger' => '$refresh'];

public function render()
{
    return view('livewire.component-a');
}
```
`ComponentA` view

```
<div>
    this is test component A {{ now() }}

    <div>
        <div>
            <livewire:component-b/>
        </div>
    </div>
</div>
```

`ComponentB` view 

```
<div>
    <button class="px-4 py-2 text-sm bg-green-200 text-green-700 rounded"
            wire:click.prevent="$emit('trigger')"
    >
        Emit event
    </button>
</div>
```

when i change my `ComponentA` view as below code works fine
```
<div>
    this is test component A {{ now() }}

    <div>
           <livewire:component-b/>
    </div>
</div>
```

but when i wrap `ComponentB` inside `ComponentA` with multiple div get error as below.

![image](https://user-images.githubusercontent.com/18545622/78873442-9c8f9900-7a6a-11ea-83cc-ccee180153ed.png)

 - Browser Chrome

**Comment by devoided** [comment] 2020-04-15 14:32
This is linked to this issue #659 https://github.com/livewire/livewire/issues/659

**Comment by calebporzio** [comment] 2020-06-28 13:56
I just tested this exact component locally and it works perfectly.

Try again, and re-submit if it still fails for you in the latest version of Livewire

**Comment by farhanianz** [comment] 2020-08-16 07:12
@calebporzio **The issue exists if re-rendered after listening to an event.**

Livewire: v1.3.2
AlpineJS: 2.5.0
AlpineJS Turboilnks Adapter: v0.1.0 (w/ or w/o, doesn't matter, gives the same error)
Turbolinks: doesn't matter, issue is there w/ or w/o it
Laravel: v7.x
PHP: 7.3.x

```blade
{{-- It is itself a livewire component, let's say: <livewire:show-post :id="1" key="post-1" /> --}}

<livewire:add-comment-form post="1" :key='post-1' />

@foreeach ($comments as $comment)
    <livewire:show-comment
        :key="'comment-'.$comment->id"
        :data="$post" />
@endforeach
```

comment-form.blade.php

```blade
<form wire:submit.prevent="saveMe">
<input type="text" wire:model="comment" />
<button>Save</d>
```

CommentForm.php

```php
public function saveMe(){ 
    // saved...
   // $this->emit('refresh-it-for-loading-new-comment');
]
```

show-comment,blade.php
```blade
<div>
    <p>{{ $comment->content }}</p>
    <livewire:another-important-component :key="'comment-important-component-'.$comment->id"/>
</div>
```

another-important-component.blade.php => eg: for adding/showing vote, some basic stuff

The issue occurs after the first re-rendering ($refresh). The last comment is shown without page reload, then console.log gives the error.
```javascript
index.js:23 Uncaught (in promise) TypeError: Cannot read property 'data' of null
    at new Component (index.js:23)
    at onNodeAdded (index.js:383)
    at callHook (morphdom.js:35)
    at handleNodeAdded (morphdom.js:140)
    at handleNodeAdded (morphdom.js:164)
    at handleNodeAdded (morphdom.js:164)
    at handleNodeAdded (morphdom.js:164)
    at handleNodeAdded (morphdom.js:164)
    at morphdom.js:407
    at morphEl (morphdom.js:219)
Component @ index.js:23
onNodeAdded @ index.js:383
callHook @ morphdom.js:35
handleNodeAdded @ morphdom.js:140
handleNodeAdded @ morphdom.js:164
handleNodeAdded @ morphdom.js:164
handleNodeAdded @ morphdom.js:164
handleNodeAdded @ morphdom.js:164
(anonymous) @ morphdom.js:407
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:463
value @ index.js:272
value @ index.js:246
value @ index.js:182
value @ index.js:158
value @ index.js:30
Connection.driver.onMessage @ index.js:9
(anonymous) @ http.js:33
Promise.then (async)
(anonymous) @ http.js:28
Promise.then (async)
sendMessage @ http.js:26
value @ index.js:43
value @ index.js:142
later @ debounce.js:50
setTimeout (async)
(anonymous) @ debounce.js:54
value @ index.js:131
(anonymous) @ Store.js:55
emit @ Store.js:54
(anonymous) @ index.js:199
value @ index.js:189
value @ index.js:158
value @ index.js:30
Connection.driver.onMessage @ index.js:9
(anonymous) @ http.js:33
Promise.then (async)
(anonymous) @ http.js:28
Promise.then (async)
sendMessage @ http.js:26
value @ index.js:43
value @ index.js:142
later @ debounce.js:50
setTimeout (async)
(anonymous) @ debounce.js:54
value @ index.js:131
(anonymous) @ node_initializer.js:233
value @ index.js:469
(anonymous) @ node_initializer.js:191
```

Removing the another-important-component, works perfectly. However, each livewire component is also alpine js component. The codes are just a pseudo-replacement of my original code just to demonstrate what am I doing. What's the fix?

Last one, Should I avoid nesting too much & depend on events? What is the proper way of doing such thing?
1. Create voting livewire component for each comment by livewire component (that issue occurs)
2. Create blade component & emit events then listen to it.
3. Other (what's it then?)

**Comment by asantibanez** [comment] 2020-08-16 14:55
Hey @farhanianz !

Could you wrap the foreach loop in a div and test it out again?

```
<livewire:add-comment-form post="1" key='post-1' />

<div>
@foreeach ($comments as $comment)
    <livewire:show-comment
        :key="'comment-'.$comment->id"
        :data="$post" />
@endforeach
</div>
```

**Comment by farhanianz** [comment] 2020-08-17 04:50
@asantibanez, I made sure everything is properly wrapped inside DIV in my real project, though didn't wrote here earlier. Same issue. It's making me finish the project not sooner. Need a fix soon, been doing & enjoying with livewire so far.

Also it would take time to convert it to vuejs app now, so a fix is eagarly needed. I've seen many comments regarding the same issue before. I'm willing to help in debugging.

**Comment by farhanianz** [comment] 2020-08-17 05:01
However, that is a bit nested.

```blade
<div>
    @foreach(---)  {
        $comment....
        <div>
            <livewire:voting key="unique"/>
        </div>
        if($comment->hasReplies()) {
            @foreach(----) {
                $reply....
                <div>
                    <livewire:voting key="uniqueToo" />
                </div>
          }
      }
</div>
```

And I'm posting the comment through livewire component, emiting event then re-rendering. 
That's where it's not getting. First comment is rendered then that error is shown. No further comment is being rendered though these are being saved in the DB. Removing the voting component completely solves the re-rendering issue.

**Comment by rappasoft** [comment] 2020-09-19 02:48
So I just came across the same issue. I had so many components rendering in so many loops I couldn't see it right away. Turns out my unique keys were not as unique as I thought on one component. I added a Str::random() to the end just to test, and it worked after that.

Not sure if yours will be the same solution, but that specific instance is what threw this error for me.

**Comment by marchampson** [comment] 2020-09-20 15:26
Definitely the key for me. I have a number of nested components and placing a key on the component call as described in the docs fixed it straight away: 
`<livewire:user-profile-one :user="$user" :key="'user-profile-one-'.$user->id">`

https://laravel-livewire.com/docs/2.x/nesting-components

**Comment by erikacamilleri** [comment] 2020-09-25 08:53
I am experiencing this issue as well and I obeyed the docs to the letter. I even tried @rappasoft suggestion. However I am experiencing this in a scenario which is not documented about in detail (at least that is my impression anyway). The rendering of nested components with the unique keys are being determined by a "filter" in the parent component. 

`<div class="mt-5 grid gap-5 max-w-lg mx-auto lg:grid-cols-3 lg:max-w-none">
            @foreach($drivers as $driver)
                <div wire:key="{{$loop->index}}">
                    {{ 'shipments-driver-day-planner-livewire-' . $driver['id']  }}
                    <livewire:store.shipments-driver-day-planner-livewire :driver="$driver['id']"
                                                                          :date="$date"
                                                                          :key="'shipments-driver-day-planner-livewire-' . $driver['id'] "></livewire:store.shipments-driver-day-planner-livewire>
                </div>
            @endforeach
        </div>`

When a filter value changes, it could be that the list of `$drivers` changed and the DOM eventually breaks.

**Comment by mitchjam** [comment] 2020-10-24 15:56
@erikacamilleri I wonder if your `wire:key="{{ $loop->index }}"` might be causing some issue. I haven't tested but that seems like it could maybe cause some weird issues.

**Comment by mitchjam** [comment] 2020-10-24 16:04
None of these descriptions are easy to reproduce. 

@austenc @calebporzio Maybe close this until someone gives proper reproducible steps.

**Comment by austenc** [comment] 2020-10-24 16:39
Thanks @mitchjam.

This does seem like a case of keys that aren't unique, which is eventually causing a DOM-diffing issue. If someone wants to share a public repository where this issue can be reproduced, I'd be happy to take a look at it.

**Comment by squishythejellyfish** [comment] 2020-10-29 21:24
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed by squishythejellyfish** 2020-10-29 21:24 UTC
