### ISSUE TITLE
Eager Loading Relationships

### ISSUE THREAD

**Issue by ChrisSantiago82** [livewire/livewire#2010] opened 2020-11-11 10:25 UTC
I'm not sure if this is a bug or just a missing feature or maybe I'm just doing something wrong. The idea is that I want to eager load a relationship to resolve the n + 1 problem.

In the mount method I have a query where I load the relationship with the "with" method. If I make a "dd", the relationship is there and loaded:
`$query = OfferFile::select();

$query->where('offer_id', '=', $this->offer_id);

$query->with('File');

this->offerFiles = $query->get();`

![image](https://user-images.githubusercontent.com/43000085/98798685-8c66e000-23e4-11eb-8aec-9608f01302d4.png)

But then in the Laravel Debug bar I still have all the queries running for each relationship one by one when it's rendered:
![image](https://user-images.githubusercontent.com/43000085/98799114-1151f980-23e5-11eb-90a2-db259957c209.png)

Then when I go back the Livewire Class for example with a button click, the relationship is missing. That means the relationship doesn't survive the trip to the blade?
![image](https://user-images.githubusercontent.com/43000085/98799215-35add600-23e5-11eb-9b62-4b3a5eaa82b9.png)

Is that a bug? Or just not supported by Livewire? Or how is the recommended way to solve the n + 1 problem?

**Context**
- Livewire version: 2.2.9
- Laravel version: 8.9.0
- Browser: Chrome

**Comment by joshhanley** [comment] 2020-11-13 01:06
If you are getting multiple queries running on the first render, then that suggests your eager loading isn't working correctly. I'd be double checking how many queries have run when you dd the results and see if it is the same.

But after a request has happened, they won't be loaded as Livewire doesn't transmit all of the collection data between the front end and the back end, only model ids, and then it hydrates the models from the database.

You could make that happen each time by using a hydrate hook which calls `$this->offerFiles->load('file);`.See this https://laravel-livewire.com/docs/2.x/lifecycle-hooks

Hope this helps!

**Comment by ChrisSantiago82** [comment] 2020-11-13 09:14
Hello Josh,

Thank you very much for your input. This was very helpful. it makes sense that the relation ships wouldn't be send for an back.

I don't see it as an option to use the livecyles hooks because then those queries would always run. For example every time when something changes on an input field.

But the problem was somewhere else and to me this looks like a bug. I'm loading those data with the relationship and then in the Lifewire blade I make a foreach with those data.
And then below that I have an element where I use a "wire:init" to italicize a file dropdown field after the page is loaded.
When I remove the wirte:init then I don't have that problem anymore or if I put the "$this->offerFiles->load('file);" into the init function it's also does it correctly.
That means if I use a "wire:init", it doesn't do the rendering on the first run, it makes it on the second run and then the relationship is missing. But to clarify, the foreach is not inside the "wire:init", that is somewhere else on the page.
There is a problem with "wire:init" and eager loading the relationships. To me it's okay to load the relationship inside the "wire:init". But I think it should be mentioned in the docs.
Are there any thoughts on this?

**Comment by austenc** [comment] 2020-11-17 01:05
@ChrisSantiago82 perhaps you can provide a repository so we could check it out and easily reproduce your issue?

**Comment by ChrisSantiago82** [comment] 2020-11-17 10:17
@austenc thank you very much for your answer. I have created a repository for this issue.

You will find it under:
ChrisSantiago82/Livewire-Test
https://github.com/ChrisSantiago82/Livewire-Test

It comes with a database migration. The migration creates a table book and bookchapter. It also fills the tables with data. 100 books and each book has 10 chapters.
The laravel debug bar is also installed.
I have created a livewire component that loads all the books and the relationship bookchapter in the mount method.
There is also a ini function. If the page is open with the ini, then there are 101 queries that run. If you remove the init, then there are 2 queries that run.

**Comment by calebporzio** [comment] 2020-11-18 16:33
I think the issue is that Livewire will only preserve eager loaded relationships when the property is a SINGLE model, NOT a COLLECTION of models.

If more people express a need for this, we can consider adding support, but off the top of my head, it wouldn't be trivial because we use Laravel's system for serializing models and model collections and we would have to override behavior inside of there.

Not impossible, but going to wait for more pressure from the community for it (or a clean PR of course)

**Comment by squishythejellyfish** [comment] 2020-11-18 16:33
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by ChrisSantiago82** [comment] 2020-11-18 16:40
But the interesting part is that without the init that there is no problem that livewire doesn't preserve the eager loading. It seems if there is a init, that the first load isn't finished and because of that it has to make the queries the second time.

Could we at least consider to write it to the docs that if you use the init functionality the eager loading won't work? Or that then the people should load the relationship in the init method as well?
I could imagine that many people have this issue but don't even notice it.

**Comment by bapidey678** [comment] 2020-12-11 17:49
Pressure

**Comment by bapidey678** [comment] 2020-12-11 17:56
REOPEN

**Comment by bapidey678** [comment] 2020-12-11 18:08
$createdComment = Comment::create(['body' => $this->newComment, 'user_id' => 1]);
$this->comments->push($createdComment->latest()->first());

Getting select * from `users` where `users`.`id` = 1 limit 1   for each iteration.

This might be solved by setting protected $with = ['user']; on Comment model.

**Comment by jartaud** [comment] 2020-12-12 07:13
```
// Component

public User $user;
public array $specialities = [];
public array $removeSpecialities = [];

public function mount(string $uuid)
 {
      ...

      **(A)**

      $this->user = User::whereTenantId($this->tenant->id)
            ->with(['doctorSpecialities'])
            ->whereUuid($uuid)->firstOrFail();

     $this->specialities = $this->user->doctorSpecialities
            ->map(fn ($item, $key) => ['id' => $item->id, 'speciality_id' => $item->speciality_id])
            ->toArray();
      ...
}
```
```
public function render()
 {
      return view('livewire.view);
 }
```

```
 public function addSpeciality()
 {
      $this->specialities[] = ['id' => '', 'speciality_id' => ''];
 }
```
 
```
public function removeSpeciality($index, $dbValue = '')
{
        unset($this->specialities[$index]);

        if ($dbValue) {
            $this->removeSpecialities[] = $dbValue;
        }
 }
```

![Screenshot from 2020-12-12 01-57-45](https://user-images.githubusercontent.com/266818/101977731-bac31f80-3c1d-11eb-94d1-a6e55ec3c7a2.png)

Every time I click on +Add or remove, it fetches for the User and doctorSpecialities **(A)**. I am doing something wrong or that's the correct behavior?

**Comment by joshhanley** [comment] 2020-12-12 21:11
@jartaud that would be the correct behaviour, as Livewire has to process any properties each time a request happens. There are things you can do to change that though.

But I don't think that is related to Eager Loaded Relationships (which is what this issue is about). Can I suggest opening up a discussion with your question https://github.com/livewire/livewire/discussions/new

Thanks!

**Comment by jartaud** [comment] 2020-12-13 06:10
Thanks @joshhanley

**Comment by joshhanley** [comment] 2020-12-26 06:29
Livewire uses Laravel's queue serialisation and restore methods to send model and collection data back and forth.

On the original PR to Laravel that added the support to restore relations to single models, it was noted to add support to eloquent collections at a later date, but it seems that never happened.

I have PR'd the fix laravel/framework#35720 that, if merged, will fix this n+1 problem. I've run into it quite a few times and have to work around it each time.

Hope this helps!

**Comment by CoffeeKing68** [comment] 2021-01-20 14:14
Hi All!

Is there a solution for this right now, or do we have to wait until the fix is implemented on laravel\framework?
I am on Laravel 7 right now, but I could upgrade.
I think converting the collection to array would work but I would like to avoid that if possible.

Thanks

**Comment by joshhanley** [comment] 2021-01-20 23:20
@CoffeeKing68 sadly, that PR was closed for Laravel 8, so it's something that will probably have to wait for Laravel 9 to be supported in the Laravel core.

We've been talking about adding this short term into Livewire but it requires some testing to ensure it doesn't cause issues if it then does get added to Laravel 9.

But you can work around it at the moment using hydrate hooks. Imaging you have an eloquent collection of posts saved in a property called `$posts` with comments eager loaded, but when the next request comes through, the comments aren't eager loaded. You could create a method called hydratePosts and load the relationship in there like the below, that way you don't run into the n+1 problem when iterating through in the views.

Hope this helps!

```php
public function hydratePosts() {
    $this->posts->load('comments');
}
```

**Comment by joshhanley** [comment] 2021-01-21 02:11
I've submitted a PR to fix this by loading eloquent collection relations on hydration. Check out PR #2386

**Comment by squishythejellyfish** [comment] 2021-02-23 16:49
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed by squishythejellyfish** 2021-02-23 16:49 UTC

**Comment by ChrisSantiago82** [comment] 2021-02-23 17:16
Thanks @joshhanley . Looks very nice. You made my day

**Comment by joshhanley** [comment] 2021-02-23 19:55
No worries! 🙂

**Comment by kirkbushell** [comment] 2024-02-18 08:41
It definitely needs to be supported - if you have any form of constraint on the eager loaded relationship, those are lost. To me it seems that Livewire should provide some sort of cache mechanism to do this better. Seems to have been lost in Livewire 3?
