### ISSUE TITLE
Error: Method Livewire\Redirector::with does not exist.

### ISSUE THREAD

**Issue by sprklinginfo** [livewire/livewire#1801] opened 2020-10-12 03:30 UTC
### Description

I have a livewire form component. After it validates all data, I use the following line to redirect to anther route:

return redirect()->route('checkout.store')->with(['data' => $request->all()]);

then I got the following error:

BadMethodCallException
Method Livewire\Redirector::with does not exist.

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.2.9
- Laravel version: v7.28.4
- Browser: [e.g. Chrome, Safari]

**Comment by zepfietje** [comment] 2020-10-12 09:28
@sprklinginfo please search existing issues before opening new ones. This is a duplicate of https://github.com/livewire/livewire/issues/841. Please close it.

**Closed** 2020-10-12 14:49 UTC
