### ISSUE TITLE
Custom Class inside component becames null

### ISSUE THREAD

**Issue by alexandermariduena** [livewire/livewire#1340] opened 2020-07-30 02:03 UTC
### Description
Im trying to use a custom class inside a component:
```php
protected $sample;

public function mount() {
    $this->sample = new Test();
}
```
But when a want to call this class from another method the class is null:
```php
public function test() {
   dd($this->sample);
}
```
What im missing here?

### Steps to reproduce
I have a playground to reproduce the issue: 
https://laravelplayground.com/#/snippets/2204e7d6-9f9f-44d0-8238-88d7ca1ab58c

**Context**
- Livewire version: 1.3
- Laravel version: 7.0

**Comment by dustinfabre** [comment] 2020-07-30 18:09
use computed property instead, protected properties does not persist. also if you make it public it wont work also. public properties must be javascript friendly

**Comment by ajmariduena** [comment] 2020-07-30 19:33
But that does not means that the instance of the class will be persisted right?, check the following playground:

https://laravelplayground.com/#/snippets/09e02a4c-cb05-4225-bf65-8ca0a8d70758

Steps to reproduce:
1. Click on add button to add an item to the `Test` class property
2. CLick on test to retrieve the `Test` class instance
3. The `Test` class is now empty 

I think maybe this is not supported or im doing something wrong.

Thanks for you help.

**Comment by ousid** [comment] 2020-07-31 00:25
what do you want to do exactly cause this makes no sense anyway.

if we knew the reason may help you with your issue.

**Comment by ajmariduena** [comment] 2020-07-31 01:58
Ok,

I have a `Cart` class that do some operators like add, delete, calculate taxes etc that i want to use on my livewire component, i made a naive example of my use case:

https://laravelplayground.com/#/snippets/2f4c5c83-d383-4305-8e60-5d0cca734f19

In my mind this helps me to have a cleaner component.

**Comment by ousid** [comment] 2020-07-31 23:26
In this case, you can use for example a `trait` and implement on the `Cart` model or you can use these methods directly in the model itself without additional class or event you can use this simple math inside the livewire components either 

you have a lot of ways to do it and always chose the easiest one and the refactor cames after.

```php
<?php

use Livewire\Component;

class LivewireComponent extends Component
{
   public $items = [];

    public function getCartProperty()
    {
        return new Cart();
    }

    public function getCart() {
        dd($this->cart);
    }

    public function getCartCount() {
        __return count($this->items);__
    }

    public function addToCart() {
        __$this->items[] = rand(1,300);
    }
  
    public function render()
    {
        return view('livewire-component');
    }
}
```

**Comment by ajmariduena** [comment] 2020-07-31 23:28
That's true @ousid thanks for your help i will use a trait.

**Comment by ousid** [comment] 2020-07-31 23:29
Happy to help @ajmariduena

**Comment by jimpeters** [comment] 2020-09-14 03:23
@alexandermariduena  Can you close this issue?  The button should be next to the comment button at the bottom for you.

<img width="850" alt="Screen Shot 2020-09-13 at 11 21 04 PM" src="https://user-images.githubusercontent.com/1263441/93040447-0b73ae00-f618-11ea-9636-43359e2b140c.png">

**Comment by nuernbergerA** [comment] 2020-09-14 10:49
I'm going to close this for now. @alexandermariduena if you still have this issue feel free to re-open.

**Closed by nuernbergerA** 2020-09-14 10:49 UTC
