### ISSUE TITLE
@entangle doesn't always update boolean in form

### ISSUE THREAD

**Issue by cutigersfan** [livewire/livewire#1964] opened 2020-11-03 18:45 UTC
### Description
Sometimes a boolean in the livewire view isn't updated with @entangle variable. See the below playground and click the 'click me' button. Click the "click me" button and you'll see the alpine variable updates as expected. Cycle through a few clicks on the 'click me' button and then submit to server and you'll see that very easily the correct state isn't sent.

Interestingly, if you remove defer from the form all works well.

### Exact steps to reproduce
See playground: https://laravelplayground.com/#/snippets/1d1444c0-d96d-4f9b-9325-efca8c9d438a

**Context**
- Livewire version: latest on playground
- Laravel version: latest on playground
- Alpine version: latest on playground
- Browser: Safari & Chrome both

**Comment by joshhanley** [comment] 2020-11-03 19:41
@cutigersfan there was a bug with entangle.defer that has been fixed and will be released with the next version of Livewire.

I would recommend closing this until then and if the issue is still present after that, then reopen it.

Hope this helps!

**Comment by squishythejellyfish** [comment] 2020-11-09 21:51
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed by squishythejellyfish** 2020-11-09 21:51 UTC

**Comment by cutigersfan** [comment] 2020-11-27 02:30
> 👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.
> 
> I see this issue has been closed.
> 
> Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.
> 
> If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.
> 
> Re-opening actually helps us track which issues are a priority.
> 
> Reply "REOPEN" to this comment and we'll happily re-open it for you!
> 
> (More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

REOPEN

This issue still exists. See playground: https://laravelplayground.com/#/snippets/763cbd72-b51c-4e81-863d-dc266d17b249

Click 'Click Me' button and see on show. Next click 'Submit' and see that transferred to the server. PERFECT! Now click 'Click Me' once again to see on hide. Click 'Submit' and expect false to be transferred to server, but it's not. Still shows 'true'.

**Comment by joshhanley** [comment] 2020-12-01 20:46
@cutigersfan 2.3.4 has just been released with a fix for this.
