### ISSUE TITLE
password field

### ISSUE THREAD

**Issue by carlituxman** [livewire/livewire#1937] opened 2020-10-30 18:07 UTC
### Description

I have a password field in the model, for example Users with a password rule.

### Exact steps to reproduce

In a edit/update view the field is cleared after typing some char

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.12.3
- Alpine version: 2.7.0
- Browser: Chrome

**Comment by calebporzio** [comment] 2020-10-30 18:08
Closing this. Poor title and no copy/pastable code with steps to reproduce.

**Comment by squishythejellyfish** [comment] 2020-10-30 18:08
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed** 2020-10-30 18:08 UTC

**Comment by carlituxman** [comment] 2020-10-30 18:15
REOPEN

I update the information

**Comment by carlituxman** [comment] 2020-10-30 18:16
> 👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.
> 
> I see this issue has been closed.
> 
> Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.
> 
> If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.
> 
> Re-opening actually helps us track which issues are a priority.
> 
> Reply "REOPEN" to this comment and we'll happily re-open it for you!
> 
> (More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

REOPEN

**Comment by sanderdewijs** [comment] 2021-03-10 13:50
@carlituxman I ran into the same issue. The cause was that by default the password property of the User model is hidden. Which is actually a good thing in terms of security.

One way to go about this is to create a property $password on the LiveWire component. Then in your form don't bind user.password, but just do 
```
<input type="password" wire:model="password" id="password" :placeholder="Password" />
```
When saving the User model, you add the password property and Hash the password value

```
public function createUser() {
    $this->validate();
        
    $this->user->password = Hash::make($this->password);
    $this->user->save();
}
```

This is better for both creating a new user, and in case of an existing user, you don't want to echo out the hashed password which is stored in the database in the input field.
