### ISSUE TITLE
Datatable pagination links do not work

### ISSUE THREAD

**Issue by mscott83** [livewire/livewire#1775] opened 2020-10-07 18:48 UTC
### Description
I'm following the basic steps in Caleb's Laracasts example for implementing datatables in a Livewire component. However, when I implement pagination, the page links do not work. I click on them, get the 'Waiting for website.test...' message at the bottom of Chrome, but nothing happens - the table stays on page 1. The weird thing is, if I look at the page source it will show the results for the page that I've selected, but what is displayed on screen is still page 1. It's really very strange. I'm not really sure how to even begin troubleshooting this.

### Exact steps to reproduce
Create a component along the lines of the snippets below:

### Stripped-down, copy-pastable code snippets
Blade:
```
<div class="w-full">

  <livewire:datatable title="Airport"
                      model="App\Models\Airport"
                      columns="airport_name, area, location" />
</div>
```
app/Http/Livewire/Datatable.php
```
namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithPagination;

class Datatable extends Component
{
    use WithPagination;

    public $title;
    public $model;;
    public $columns;
      
    public function mount($model = null)
    {
        $this->model = $model;
        $this->include = explode(", ", $this->columns);
    }

    public function render()
    {
        return view('livewire.datatable', [
            'results' => $this->model::orderBy('airport_name')->paginate(15)
            ]);
    }
}
```
Component:
```
<div>
    <div class="px-6 py-2 text-sm">
    <table id="table" class="" cellspacing="0" width=100%>
        <thead>
            <tr class="text-sm font-bold border-b-4">
                @foreach ($include as $header)
                <th class="p-1 text-gray-900 uppercase tracking-wide" scope="col">{{$header}}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach ($results as $result)
            <tr>
                @foreach ($include as $header)
                <td class="pt-3 px-2 text-sm border-r-2">{{ $result->$header }}</td>
                @endforeach
            </tr>
            @endforeach
        </tbody>
    </table>
    </div>

    <div class="pt-4 px-6">
        <div class="col">
            {{ $results->links() }}
        </div>
    </div>
</div>
```
Live example (slightly older Livewire/Laravel versions, but the same behaviour: [Sentais](https://pe-pre-prod.uksouth.cloudapp.azure.com/units/ijaaf/sentai)
**Context**
- Livewire version: 2.2.9
- Laravel version: 8.4.0
- Browser: happens in Chrome and Internet Explorer

**Comment by Testings-port** [comment] 2020-10-13 13:48
try moving your 
    <div class="pt-4 px-6">
        <div class="col">
            {{ $results->links() }}
        </div>
    </div>

below </table> i mean, don't put it outside the main data div

**Comment by mscott83** [comment] 2020-10-13 14:28
I moved {{ $results->links() }} to be the very last line before my closing </div>

It made no difference, the links still do not work.

**Comment by booni3** [comment] 2020-10-15 13:04
I had a similar issue to this... my fix was to surround the main divs with another set of divs. Double div your component!

I have no idea why this is happening, but it started after upgrade to v2.

```blade
<div>
<div>

{{-- table and links --}}

</div>
</div>
```
Interested to hear if this works for you too as I would love to know why this is needed.

**Comment by mscott83** [comment] 2020-10-15 20:55
No, adding an additional div layer didn't work either. I tried a few other variations on that theme, such as putting the links inside the same div as the table, in its own div, and a few others, and there was no difference - paginations links still didn't work.

In the meantime I've re-created the table as a normal blade component but it sure would be nice to be able to use some of the dynamism of Livewire.

**Comment by austenc** [comment] 2020-10-17 16:48
@mscott83 I just tried your example and after fixing a couple bugs in your component snippet, the pagination links seemed to work okay. 

The bugs were: 
- Two semicolons on the line `public $model;;`.
- `public $columns` was defined but never used in the component view. There was also no `$columns` variable in the `mount` method. 

Try this component out and see if it fixes your issue. If it doesn't, please provide more info so we can reproduce this.
```
class DataTable extends Component
{
    use WithPagination;
    
    public $model;
    public $columns;

    public function mount($model, $columns)
    {
        $this->model = $model;
        $this->columns = explode(", ", $columns);
    }

    public function render()
    {
        return view('livewire.datatable', [
            'results' => $this->model::paginate(15)
        ]);
    }
}
```

**Comment by mscott83** [comment] 2020-10-17 19:35
Thanks for the suggestions. I've copied your code pretty much exactly and it still doesn't work. If I click the link for page 2, the screen refreshes but I still only see the results for page 1.

Is there any way this could be due to views being cached somehow? Having said that `php artisan optimise` failed to fix this too.

**Comment by austenc** [comment] 2020-10-17 19:55
You can try `php artisan view:clear` -- that may be one potential cause. 

Can you paste in your full component class and view (exactly as it is) please?

**Comment by Testings-port** [comment] 2020-10-17 20:37
are you disposed to do something like stream in discord. or teamviewer to try help you out?. is very wired what you have right there

**Comment by mscott83** [comment] 2020-10-18 12:01
Okay, my code exactly as it currently is.

Blade:
```
<div class="w-full">

  <livewire:airbase.datatable title="Airbases"
                      model="App\Models\Airbase"
                      columns="basename, area, location" />

</div>
```
app/Http/Livewire/Airbase/Datatable.php:
```
<?php

namespace App\Http\Livewire\Airbase;

use Livewire\Component;
use Livewire\WithPagination;

class Datatable extends Component
{
    use WithPagination;

    public $title;
    public $model;
    public $columns;
    
    public function mount($model, $columns)
    {
        $this->model = $model;

        $this->columns = explode(", ", $columns);
    }

    public function render()
    {
        return view('livewire.airbase.datatable', [
            'results' => $this->model::paginate(15)
            ]);
    }
}
```
Component:
```
<div>
    <div class="px-6 flex justify-between items-center">
        <h1 class="text-gray-700 font-bold text-2xl uppercase">{{ $title }}</h1>
    </div>

    <div class="px-6 py-2 text-sm">
    <table id="table" class="" cellspacing="0" width=100%>
        <thead>
            <tr class="text-sm font-bold border-b-4">
                @foreach ($columns as $header)
                <th class="p-1 text-gray-900 uppercase tracking-wide" scope="col">{{$header}}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach ($results as $result)
            <tr>
                @foreach ($columns as $header)
                <td class="pt-3 px-2 text-sm border-r-2">{{ $result->$header }}</td>
                @endforeach
            </tr>
            @endforeach
        </tbody>
    </table>
    {{ $results->links() }}
    </div>
</div>
```

In response to @Testings-port , I am using the default Livewire pagination as far as I know. I have no Javascript errors in the console. Happy to have a remote session so you can see this live, subject to availability.

I've even tried a variant of this component where the Model name is not dynamic and is instead hardcoded, and I get the same behaviour.

**Comment by calebporzio** [comment] 2020-10-21 19:48
Closing this because others have been unable to reproduce.

Please re-submit when something more reproducible comes out of this.

**Closed by calebporzio** 2020-10-21 19:48 UTC
