### ISSUE TITLE
I figured out why autofill doesn't work - Caleb please read

### ISSUE THREAD

**Issue by redbastie** [livewire/livewire#1661] opened 2020-09-22 05:01 UTC
Safari autofill is not working in the most recent version of Livewire. I did a bunch of digging and I figured out why.

If you look at the compiled livewire.js, this code in particular causes the issue:

	value = 
		e instanceof CustomEvent && 
			void 0 !== e.detail && 
			void 0 === window.document.documentMode 
			? e.detail 
			: DOM.valueFromInput(el, component);

I have done some refactoring to make this more readable.

Now, when I look at the Livewire node_initializer.js, I find this:

    value =
        e instanceof CustomEvent &&
            typeof e.detail != 'undefined' &&
            typeof window.document.documentMode == 'undefined'
            ? e.detail
            : DOM.valueFromInput(el, component)

Notice the difference between this:

	void 0 !== e.detail && 
	void 0 === window.document.documentMode 

And this:

    typeof e.detail != 'undefined' &&
    typeof window.document.documentMode == 'undefined'

When I replaced the `void 0` code with the code found in the `node_initializer`, Safari autofill worked flawlessly and Livewire picked up the models without issue.

To stop this I believe you can set the `@babel/preset-env` modules to `false` so that the code is built properly in the next version. Related SO post here: https://stackoverflow.com/questions/55133167/how-to-tell-babeljs-not-to-override-this

**Comment by amcsi** [comment] 2020-09-22 08:22
Do we know why by the way? Because AFAIK those two you showed should practically be equivalents.

**Comment by redbastie** [comment] 2020-09-22 08:40
Because of the way safari handles the scripts. undefined is primitive whereas void is an operator, and safari doesn't like it. If you just stop the compiler from replacing undefined in the code the issue will be resolved.

**Comment by glaesser** [comment] 2020-09-22 09:41
Does this fix the issue on safari iOS as well (using autofill passwords in safari mobile)?

**Comment by redbastie** [comment] 2020-09-22 17:08
> Does this fix the issue on safari iOS as well (using autofill passwords in safari mobile)?

Yes.

**Comment by jimpeters** [comment] 2020-09-25 01:13
Thanks for your work on this @redbastie !

**Comment by redbastie** [comment] 2020-09-25 02:27
So I tried updating the babel config file, setting `modules` to false. I re-built livewire and `void 0` is still in the final build.

I fucking hate javascript.

**Comment by redbastie** [comment] 2020-09-25 03:55
This PR fixes it: https://github.com/livewire/livewire/pull/1688/commits/de1293f59c15512f24545685872c1dbd27a29997

**Comment by redbastie** [comment] 2020-09-25 19:01
PR that fixes the bug with IE11 support: https://github.com/livewire/livewire/pulls

**Comment by redbastie** [comment] 2020-09-25 19:01
PR that fixes the bug with IE11 support: https://github.com/livewire/livewire/pull/1696

**Comment by calebporzio** [comment] 2020-09-29 15:08
Safari autofill should be fixed in 2.2.8

Please run `php artisan view:clear`, update Livewire, and report here if the problem is fixed, otherwise, re-submit please.

Thanks everyone!

**Closed by calebporzio** 2020-09-29 15:08 UTC
