### ISSUE TITLE
Undefined index: value

### ISSUE THREAD

**Issue by giorgiopogliani** [livewire/livewire#1678] opened 2020-09-23 17:37 UTC
### Description
This is the code where the error comes from. Probably, I am missing something but with an if containing `array_key_exists` it works as it should. Maybe there is some double call? I have no idea.

```
...
$data = $update['payload'];
$unHydratedInstance->syncInput($data['name'], $data['value'])
...
```

### Exact steps to reproduce

The following blade templates plus a normal livewire component with a `$foo` property

```
@push('styles')
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
@endpush

@push('scripts')
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
@endpush

<div class="mt-2 bg-white" wire:ignore>
    <div
        x-data="{}"
        x-init="
            quill = new Quill($el, {theme: 'snow'})
            quill.on('text-change', function () {
                $dispatch('input', quill.root.innerHTML);
            });
        "
        wire:model="foo"
    >
        {!! $foo !!}
    </div>
</div>
```

**Context**
- Livewire version: 2.2.6
- Laravel version: 8.6.0
- Browser: Chrome, Safari

**Comment by dennisvandalen** [comment] 2020-09-24 15:50
I'm running into the same thing.

```json
   "updates":[
      {
         "type":"syncInput",
         "payload":{
            "name":"short_description",
            "value":"<p>D</p>"
         }
      },
      {
         "type":"syncInput",
         "payload":{
            "name":"short_description"
         }
      }
   ]
```

**Comment by giorgiopogliani** [comment] 2020-09-25 18:42
It looks like the `keydown` event (I think) setuped by quilljs triggers the wire:model of livewire.   

As workaround I removed the wire:model and I'm setting the property using `@this.set('foo', text)` and it's working for now.

It would be cool to stop that empty update though.

**Comment by glaesser** [comment] 2020-09-30 02:50
v2.2.8 now throwing this error constantly when dynamically showing/hiding (updating) page elements. Worked perfectly on v2.2.7 and below for me.

**Comment by calebporzio** [comment] 2020-09-30 18:06
@glaesser  - thank you for catching that regression. I just fixed it and tagged it in v2.2.9

@giorgiopogliani - this issue is caused because the package you are using is firing an input event on the div with the value in the .data property. That is specific to that package. Even if Livewire didn't through the undefined index error you would still hit bad behavior.

You need to prevent that event from hitting wire:model by either listening for something else, or preventing default on it before it reaches wire:model. THEN, use your `$dispatch('input')` like you are.

Closing this as it's related to the way Quill behaves.

Here's a screenshot of the event you'd need to prevent:

![image](https://user-images.githubusercontent.com/3670578/94722970-0c9a2000-0326-11eb-96c6-7ac705c64787.png)
(Notice: "data: d")

**Closed by calebporzio** 2020-09-30 18:06 UTC

**Comment by reefki** [comment] 2020-11-02 16:40
I got into the same issue, I ended up by creating a hidden input to store the value and attach the `wire:model` and listen to the `text-change` or `editor-change` event on the Quill instance then fire `input` event on the input element to sync model's value.

```
function quillEditor(data) {
    return {
        instance: null,
        init() {
            this.$nextTick(() => {
                this.instance = new Quill(this.$refs.editor, {
                    theme: 'snow'
                });

                this.instance.on('text-change', () => {
                    this.$refs.input.dispatchEvent(new CustomEvent('input', {
                        detail: this.instance.root.innerHTML
                    }));
                })
            })
        },
        ...data
    }
}
```

```
<div x-data="quillEditor({})" x-init="init()">
    <input type="hidden" x-ref="input" class="w-full" wire:model="description">
    
    <div wire:ignore>
        <div x-ref="editor">{!! $description !!}</div>
    </div>
</div>
```

**Comment by ayoub-bousetta** [comment] 2020-12-16 23:21
worked for me like that, the only problem is that you can't use model.defer
```
` <div 
          x-data
           x-ref="quillfilling"

           wire:model.defer="Product.filling"
           
           x-init="
             filling = new Quill($refs.quillfilling, { modules: {
            // formula: true,
            // syntax: true,
            toolbar: '.toolbar-container-quillfilling'
          },theme: 'snow'});
           
          filling.on('text-change', function () {
            justHtmltest_filling = filling.root.innerHTML;
            
@this.set('Product.filling', justHtmltest_filling)
         
             
           });
           "
         
      >
      {!! $Product['filling'] !!}
      `</div>``
```

**Comment by mundix** [comment] 2021-01-19 12:24
when i updating, my description doesn't render,  this is my code , what would i do in this case ?  or this is a normal behavior ? 


<div class="editor StoryQuillEditorEdit" id="StoryQuillEditorEdit"
                             x-data = '{}'
                             x-ref='StoryQuillEditorEdit'
                             x-init="
                                 QuillStoryQuillEditorEdit = new Quill($refs.StoryQuillEditorEdit, {
                                  modules: {
                                    toolbar: [
                                      ['bold', 'italic', 'underline', 'link']
                                    ]
                                  },
                                  placeholder: 'Tell us something...',
                                  theme: 'snow'
                                });
                                 QuillStoryQuillEditorEdit.on('text-change', function () {
                                   @this.set('content', QuillStoryQuillEditorEdit.root.innerHTML)
                                 });"
                            >
                            {!! $content !!}
                        </div>

**Comment by jeroenvanrensen** [comment] 2021-02-22 14:42
> 
> 
> It looks like the `keydown` event (I think) setuped by quilljs triggers the wire:model of livewire.
> 
> As workaround I removed the wire:model and I'm setting the property using `@this.set('foo', text)` and it's working for now.
> 
> It would be cool to stop that empty update though.

@giorgiopogliani can you please show your full work-around? I'm currently having the same issue.

**Comment by giorgiopogliani** [comment] 2021-02-22 14:53
@jeroenvanrensen This was my component but I am not sure if it's still working.

```blade
<div> 
  @php
      $id = uniqid()
  @endphp

  <script>
      window.addEventListener('DOMContentLoaded', (event) => {
          var editor{{$id}} = new Quill(document.querySelector('#editor-{{$id}}'), {
              theme: 'snow',
              modules: {
                  toolbar: [
                      ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
                      [{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'list': 'check' }],
                      ['link'],
                      ['code-block', 'blockquote'],
                      ['clean']
                  ],
              }
          });

          let content = (function () {
              try {
                    return JSON.parse('@php echo addslashes($value) @endphp');
              } catch (e) {
                  return {};
              }
          })();

          editor{{$id}}.setContents(content);

          editor{{$id}}.on('text-change', function (){
              @this.set('{{$name}}', JSON.stringify(editor{{$id}}.getContents()));
          })
      });
  </script>

  <div class="mt-2 bg-white" wire:ignore>
      <div id="editor-{{$id}}"></div>
  </div>
</div>

```

**Comment by jeroenvanrensen** [comment] 2021-02-22 15:21
@giorgiopogliani thanks!

**Comment by jeroenvanrensen** [comment] 2021-02-22 15:25
I finally solved it... I was using nested alpine js components, which does not work of course... I merged them and it's working again!

**Comment by nazrul-dev** [comment] 2021-06-15 04:41
component =====

<div>

    <div class="mt-2 bg-white" wire:ignore>
        <div {{ $attributes }} x-data x-ref="quillEditor" x-init="
               quill = new Quill($refs.quillEditor, {theme: 'snow'});
               quill.on('text-change', function () {
                 @this.set('content', quill.root.innerHTML);
               });
             ">
            {!! $slot !!}
        </div>
    </div>
</div>


view ====
   <x-text-editor wire:model.lazy="content"> {!!$content!!}</x-text-editor>

**Comment by nazrul-dev** [comment] 2021-06-15 04:44
<div>
    <div class="mt-2 bg-white" wire:ignore>
        <div {{ $attributes }} x-data x-ref="quillEditor" x-init="
               quill = new Quill($refs.quillEditor, {theme: 'snow'});
               quill.on('text-change', function () {
                 @this.set('content', quill.root.innerHTML);
               });
             ">
    slot
        </div>
    </div>
</div>

<x-text-editor wire:model.lazy="content"> slot  </x-text-editor>

**Comment by wpjscc** [comment] 2021-07-16 11:46
quill.on('text-change', function () {
              setTimeout(() => {
                      $dispatch('input', quill.root.innerHTML);
              },0);  
 });

this seems work for me

**Comment by estelleal** [comment] 2021-09-25 12:33
I got the same problem...
