### ISSUE TITLE
flash data goes away on polling

### ISSUE THREAD

**Issue by NoxxieNl** [livewire/livewire#233] opened 2019-09-03 12:29 UTC
**Describe the bug**
I have a livewire component that polls for new data every second. This is done globally on every page to show incoming new notifications. However when I am on page and I call the `destroy` method on a controller resource with flash data (eg : `return redirect()->route(...)->with('success', ...');) the flash data is sometimes not not shown (as it is not there)

**To Reproduce**
1. Create a controller that returns flash data
2. Create a livewire component that polls every x seconds / milliseconds
3. execute the controller a couple of times sometimes the flash data wont be presnet

**Expected behavior**
Keeping the flash data intact, looks like that the flash data is being removed because the livewire component refreshes and the flash data is stored inside that livewire call instead of the actual request I want the flash data to be shown in.

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by lancepioch** [comment] 2019-12-18 16:47
Because of the way Laravel works, this might need to be implemented/fixed as a custom Livewire solution (eg. $this->flash)

**Comment by calebporzio** [comment] 2020-03-14 16:46
Closing this issue until code is provided to reproduce the issue

**Closed by calebporzio** 2020-03-14 16:46 UTC
Labels: Type: Bug

**Comment by RomkaLTU** [comment] 2021-01-22 03:33
Do not use session data inside polling. Use store, public $someMessage;
