### ISSUE TITLE
Cannot read property 'getAttributeNames' of null

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#636] opened 2020-02-25 09:35 UTC
**Describe the bug**
I know that this bug has been reported a few times, but the "fixes" already suggested doesn't seem to work.

I have a global modal Livewire component and everytime I open the modal, I get the following error:

> Cannot read property 'getAttributeNames' of null

**To Reproduce**
I have a simple `modal.php` Livewire component, that looks like this:

```php
class Modal extends Component
{

    public $isOpen = false;
    public $viewName = null;
    public $id = null;

    protected $listeners = ['showModal' => 'open', 'closeModal' => 'close'];

    public function open($viewName, $id)
    {
        $this->isOpen = true;

        $this->viewName = $viewName;
        $this->id = $id;
    }

    public function close()
    {
        $this->isOpen = false;
    }

    public function render()
    {
        return view('livewire.components.modal');
    }
}
```

The HTML for the modal, looks like this:

```html
<div>
    @if($isOpen)
        <div wire:transition.fade>

            <div class="modal fixed w-full h-full top-0 left-0 flex items-center justify-center">
                <div class="modal-overlay absolute w-full h-full bg-gray-900 opacity-50" wire:click="close"></div>
                <div
                    class="modal-container bg-white w-5/6 md:max-w-2xl mx-auto rounded shadow-lg z-50 overflow-y-auto">
                    <div
                        class="modal-close absolute top-0 right-0 cursor-pointer flex flex-col items-center mt-4 mr-4 text-white text-sm z-50"
                        wire:click="close">
                    </div>

                    <div class="modal-content py-4 text-left px-6">

                        <!--Body-->
                        @livewire($viewName, $id)

                    </div>
                </div>
            </div>
        </div>

    @endif
</div>
```
I include the Livewire modal component at the bottom of my `app.blade.php` file:

```html
<!-- Scripts -->
<script src="{{ mix('js/app.js') }}"></script>

@livewire('components.modal')
@livewireAssets
@stack('scripts')

</body>
</html>
```
And then finally, I simple trigger it from my HTML:

```html
<div wire:key="{{$model->id}}">
<a wire:click="showModal('consols.edit-consol', {{$model->id}})"
   class="cursor-pointer">@svg('edit-pencil', 'w-4 h-4 inline-block fill-current')</a>
</div>
```

As soon as the modal appear, I get the following error in my console:

> Uncaught (in promise) TypeError: Cannot read property 'getAttributeNames' of null

**Comment by ducopro** [comment] 2020-02-26 10:55
Looking at your code (the code that triggers the opening of the modal) i think you try to emit an event called showModal is that correct?

From what i see you are calling a method on a component called showModal. Or is that correct and you did not share that code? Are you emitting the event from the other component.

Anyway.. you could try changing your code like this:

```html
<div wire:key="{{$model->id}}">
<a wire:click="$emit( 'showModal' , 'consols.edit-consol', {{$model->id}} )"
   class="cursor-pointer">@svg('edit-pencil', 'w-4 h-4 inline-block fill-current')</a>
</div>
```

**Comment by oliverbj** [comment] 2020-03-06 13:03
> Looking at your code (the code that triggers the opening of the modal) i think you try to emit an event called showModal is that correct?
> 
> From what i see you are calling a method on a component called showModal. Or is that correct and you did not share that code? Are you emitting the event from the other component?
> 
> Anyway... you could try changing your code like this:
> 
> ```
> <div wire:key="{{$model->id}}">
> <a wire:click="$emit( 'showModal' , 'consols.edit-consol', {{$model->id}} )"
>    class="cursor-pointer">@svg('edit-pencil', 'w-4 h-4 inline-block fill-current')</a>
> </div>
> ```

I actually did not share the code for `showModal`. I have a simple trait called `LivewireModalable.php`, which have this function:

```php
public function showModal($modalView, $modalId)
{
   $this->emit('showModal', $modalView, $modalId);
}
```

So when I click on the anchor link like below:

```html
<a wire:click="showModal('consols.edit-consol', {{$model->id}})"> Open Modal </a>
```

It will emit the modal.

Changing it to emit directly from the anchor link like you suggested, unfortunately, did not help :(

**Comment by calebporzio** [comment] 2020-06-24 11:56
Closing because I cannot reproduce.

If the problem still persists, please provide an entirely copy and pastable example and resubmit

**Closed by calebporzio** 2020-06-24 11:56 UTC
