### ISSUE TITLE
request()->is() not working on Livewire updates

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#268] opened 2019-09-15 15:04 UTC
**Describe the bug**
I have a simple menu, where I check the current URL, to know which menu item to mark as "active":

```html
<ul>
   <li class="@if(request()->is("fields/$field->id")) active @endif">Field #1</li>
</ul>
```

So basically, if I visit `www.example.com/fields/1`, then the menu with the `$field->id` of 1, will get the class `active`. This does work on page load.

However, as soon as I fire off a Livewire method, for example (anywhere else on the page):

```
<a wire:click="sendEmail">Contact Us</a>
```

Then the `request()` URL changes.

**To Reproduce**
In my Blade view, I have placed below:

```php
  {{request()->path()}}
```
When visiting www.example.com/fields/1, this is the output:
```
fields/1
```

However, when I then click on the `wire:click="sendEmail"`, the `path()` changes to:

```
livewire/message
```

**Expected behavior**
I was expecting to still be able to use Laravels `request()` method - however, for some reason, the path changes (guess it is because of the AJAX request?)

**Comment by ruerdev** [comment] 2019-09-16 11:38
I am experiencing a similar issue when redirecting from a component. When I call:
`return redirect()->refresh();`

I get redirected back to:
`livewire/message/filters-component`
Where filters-component is the component I am redirecting from.

**Comment by oliverbj** [comment] 2019-09-16 11:41
@ruerdev 

How about if you use:

```php
$this->redirect('/your-url');
// Or
return redirect()->to('/your-url');
```

This is described [here](https://livewire-framework.com/docs/redirecting/).

**Comment by ruerdev** [comment] 2019-09-16 12:30
@oliverbj 

Thanks! I've tried that before, but I can't lose the query string, which is essential for my application. So that won't work.

**Comment by oliverbj** [comment] 2019-09-16 12:38
> @oliverbj
> 
> Thanks! I've tried that before, but I can't lose the query string, which is essential for my application. So that won't work.

I am pretty sure you can still access your query string.

Maybe something like this?

```php
$query =request()->query();

return redirect()->to('/your-url' . $query);
```

**Comment by intellow** [comment] 2019-09-16 12:51
You could also use the `mount()` function to pass in the query string parameters and store them in your Livewire class.

**Comment by ruerdev** [comment] 2019-09-16 13:42
> 
> 
> > @oliverbj
> > Thanks! I've tried that before, but I can't lose the query string, which is essential for my application. So that won't work.
> 
> I am pretty sure you can still access your query string.
> 
> Maybe something like this?
> 
> ```
> $query = request()->query();
> 
> return redirect()->to('/your-url' . $query);
> ```

Thank you, this does work. I will use this approach for now.
@intellow I'm sure that will also work.

I still think that refreshing the page is a better way of doing this. I'll try to find the cause and open a pr.

**Comment by lancepioch** [comment] 2019-12-18 16:53
@calebporzio Should this solution be marked in the docs if not already?

**Comment by calebporzio** [comment] 2020-03-20 21:22
Going to close this. Haven’t seen enough demand for a docs addition.

**Closed by calebporzio** 2020-03-20 21:22 UTC
Labels: Type: Question

**Comment by RJFares** [comment] 2020-10-08 06:53
I think it's good to have it in the docs. I wanted to access the parent request(), but obviously can't do that thru the livewire component, so I had to fetch it from the mount() as suggested above.
