### ISSUE TITLE
wire:model Refresh Removes JQuery DOM Updates

### ISSUE THREAD

**Issue by drj378** [livewire/livewire#2319] opened 2021-01-07 18:16 UTC
### Description

After using jQuery to update something on the page (text, class, etc.), a Livewire refresh removes the changes.

### Exact steps to reproduce

- Use `wire:model` on a `select` input
- Use a jQuery function to change an element on the page when the `select` input is updated
- Result: Livewire will remove the changes

### Stripped-down, copy-pastable code snippets

```
<h2 id="slide-over-heading" class="text-lg font-medium text-gray-900">Original Name</h2>
```

```
<select id="location" class="form-select rounded-md shadow-sm mt-1 block w-full" wire:model="location">
    <option value="">Select Location</option>
    @foreach($locations as $location)
        <option value="{{ $location->id }}">{{ $location->name }}</option>
    @endforeach
</select>
```

```
<script>

$('#location').change(function()
{
    $('#slide-over-heading').text('Something New');
    $('#slide-over-heading').addClass('text-2xl');
});

</script>
```

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.21.0
- Alpine version: 2.7.3
- Browser: Chrome
- JQuery: 3.5.1

### More Information

Removing `wire:model="location"` from the `select` input prevents the desired changes from being undone.

When I use the browser to pause on breakpoints for the `id="slide-over-heading"` element, I see:

![DOM Revert](https://user-images.githubusercontent.com/59666225/103926962-a7ee1e80-50e7-11eb-81ca-c5eb4b2658d5.PNG)

**Comment by marispro** [comment] 2021-01-07 20:10
This can be solved in three different approaches
1. Simpliest: Use wire:ignore
`<h2 wire:ignore id="slide-over-heading" class="text-lg font-medium text-gray-900">Original Name</h2>`

2. switch to alpine.js
3. do the same by using only php (blade)

**Comment by drj378** [comment] 2021-01-08 16:08
Yes, thank you. wire:ignore prevents the changes from being overwritten.

But I'm curious - is overwriting the changes the expected behavior? If so, why? Is there a way to force Livewire to recognize the changes to the DOM? Or am I misunderstanding how/why Livewire is used?

For more context, I have also run into this problem: I am loading a page and want an element to initially be hidden. When I use Alpine to hide/show the element (and it is initially hidden), it still flashes as visible on the page when it loads. It is hidden quickly, but it looks unprofessional for what I'm trying to do. I tried to fix the problem by using `invisible` when the page initially loads and then using JQuery to remove the `invisible` class when I need to.

```
<div x-data="{ itemDetail: false }">

    <div onclick="removeClass()" @click="itemDetail = true" wire:click="openItemDetail({{ $item->id }})">
        // stuff...
    </div>

    <div id="itemDetail" x-show="itemDetail === true" class="invisible">
        // stuff...
    </div>

</div>

<script>

function removeClass()
{
    $('#itemDetail').removeClass('invisible');
}

</script>

```

This works for the initial page load, but after I use JQuery to remove `invisible` it returns anytime wire:model is triggered.

**Comment by marispro** [comment] 2021-01-08 16:17
Livewire renders page on server and then does DOM diffing by javascript, this is expected behaviour and works perfectly.

For another issue, try `x-cloak` https://github.com/alpinejs/alpine#x-cloak .
`<div x-cloak x-data="{ itemDetail: false }">`
Also add x-cloak class to your stylesheet.
`<style>
    [x-cloak] { display: none; }
</style>`


When I switched to livewire+alpine stack jquery was not needed anymore for me.

**Comment by drj378** [comment] 2021-01-08 16:26
Thank you! This is exactly what I needed. And yes, using Livewire and Alpine has been amazing. Thanks again.

**Comment by austenc** [comment] 2021-01-08 18:22
Yeah, this is expected behavior.

Sounds like this has been solved via `x-cloak`? Since that seems like the case, I'm going to close this for now. Thank you!

**Comment by squishythejellyfish** [comment] 2021-01-08 18:22
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed** 2021-01-08 18:22 UTC

**Comment by hamed8993** [comment] 2022-04-04 14:38
i have similar problem!
i have <select> tag that uses selectric library of JQuery.
my problem:
when click on SUBMIT button, the selectric library disables and disrupts, and the <select> tag, returns to it's default style ( it do lose the selectric's styles). and also, the livewire for back end, can't receive this <select> element's data, until this tag return to it's default style to select again the option.
in another word:
1)first time, click on SUBMIT button, in result: the <select> tag, loses it's styles that have from "selectric" library of JQuery and it's view returns to default <select> tag.
also, data, do not send to backend.
2)selected option, be reset.
3)in reset <select> tag(it have not the "selectric style any more), again should select the option.
4)in this state, the data will be send to back end.
 

my markup code:
`<select wire:model="type">
   <option>select...</option>
   <option style='color: red;' value="real">personal</option>
   <option value="legal">official</option>
</select>
<button wire:click="createVendor" type="button" class="o-btn o-btn--confirm o-btn--color">SUBMIT</button>`

my JQuery code:
` window.addEventListener("DOMContentLoaded", function() {
$('select').selectric({
    forceRenderBelow: true
}); });
(function($) {
    'use strict';
    jQuery(document).ready(function ($) {
        //Selectric
        $('select').selectric({
            forceRenderBelow: true
        });
    });
});`

**Comment by marispro** [comment] 2022-04-04 15:55
> i have similar problem! i have tag that uses selectric library of JQuery. my problem: when click on SUBMIT button, the selectric library disables and disrupts, and the tag, returns to it's default style ( it do lose the selectric's styles). and also, the livewire for back end, can't receive this element's data, until this tag return to it's default style to select again the option. in another word: @ 1)first time, click on SUBMIT button, gives this result: the tag, loses it's styles that have from "selectric" library of JQuery and it's view returns to default tag. also, data, do not send to backend. @ 2)selected option, be reset ( in state that user do not selected ant option). @ 3)in reset tag(it have not the "selectric style any more), again should select the option. @ 4)in this state, the data will be send to back end.
> 
> my markup code: `<select wire:model="type">` `<option>select...</option>` `<option style='color: red;' value="real">personal</option>` `<option value="legal">official</option>` `</select>` `<button wire:click="createVendor" type="button" class="o-btn">SUBMIT</button>`
> 
> `
> 
> my JQuery code: ` window.addEventListener("DOMContentLoaded", function() {` `$('select').selectric({` ` forceRenderBelow: true` `}); });` `(function($) {` ` 'use strict';` ` jQuery(document).ready(function ($) {` ` //Selectric:` ` $('select').selectric({` ` forceRenderBelow: true` ` });` ` });` `});`

You should reinitiate this jquery script on each livewire request. 
Or put it into wire:ignore .

**Comment by hamed8993** [comment] 2022-04-04 18:46
> > i have similar problem! i have tag that uses selectric library of JQuery. my problem: when click on SUBMIT button, the selectric library disables and disrupts, and the tag, returns to it's default style ( it do lose the selectric's styles). and also, the livewire for back end, can't receive this element's data, until this tag return to it's default style to select again the option. in another word: @ 1)first time, click on SUBMIT button, gives this result: the tag, loses it's styles that have from "selectric" library of JQuery and it's view returns to default tag. also, data, do not send to backend. @ 2)selected option, be reset ( in state that user do not selected ant option). @ 3)in reset tag(it have not the "selectric style any more), again should select the option. @ 4)in this state, the data will be send to back end.
> > my markup code: `<select wire:model="type">` `<option>select...</option>` `<option style='color: red;' value="real">personal</option>` `<option value="legal">official</option>` `</select>` `<button wire:click="createVendor" type="button" class="o-btn">SUBMIT</button>`
> > `
> > my JQuery code: ` window.addEventListener("DOMContentLoaded", function() {` `$('select').selectric({` ` forceRenderBelow: true` `}); });` `(function($) {` ` 'use strict';` ` jQuery(document).ready(function ($) {` ` //Selectric:` ` $('select').selectric({` ` forceRenderBelow: true` ` });` ` });` `});`
> 
> You should reinitiate this jquery script on each livewire request. Or put it into wire:ignore .

thanks dear marispro.
i tried  ` wire:ignore` in `<select wire:ignore style='border:solid red;' wire:model="type" >` element, but it didn't worked.
this livewire, also has this conflict by pure javascript in all other parts. it clears DOM completely!

**Comment by marispro** [comment] 2022-04-04 18:56
Wrong, put wire:ignore for parent element, not select.

**Comment by hamed8993** [comment] 2022-04-04 20:13
> Wrong, put wire:ignore for parent element, not select.

yes. i tried latter this.
it worked, it's styles worked truly, but in this situation, this dropdown's data, do not send to back end! like situation that, user, do not selected any options of that select element.

**Comment by GiroeStefanBogdan** [comment] 2023-11-14 07:30
> > Wrong, put wire:ignore for parent element, not select.
> 
> yes. i tried latter this. it worked, it's styles worked truly, but in this situation, this dropdown's data, do not send to back end! like situation that, user, do not selected any options of that select element.

Did you find a solution for your problem?

**Comment by parthkapatel** [comment] 2023-11-21 07:44
Hello all,
    I'm also facing issue same like this I used multiple Select in livewire and when I used wire:ignore then reinitialized the UI but when I click the submit button then I did not get the selected values on submit function and variable data is blanked 

If anyone have solution for this then help us to resolved this problem
