### ISSUE TITLE
wire:dblckick in forloop sometimes not responding.

### ISSUE THREAD

**Issue by ellemaker** [livewire/livewire#755] opened 2020-03-21 18:31 UTC
![Screenshot_42](https://user-images.githubusercontent.com/4677416/77233566-4fdf3d80-6be3-11ea-9bb1-21eca019514c.png)

![Screenshot_44](https://user-images.githubusercontent.com/4677416/77233750-7fdb1080-6be4-11ea-933b-e49ee56070d2.png)

going to the child directory and go back to root directory, repeating this process until wire:dblclick is not working except the first directory.  I also try wire:click it also having issue. Any advice on this.

thank you

**Comment by calebporzio** [comment] 2020-06-28 14:14
Closing this for now because the example provided is too domain-specific.

Please provide a simple, copy and pastable example to reproduce this issue and re-submit.

Thank you.

**Closed by calebporzio** 2020-06-28 14:14 UTC
