### ISSUE TITLE
 "driver does not support creating temporary URLs" with image temporaryUrl() + validation

### ISSUE THREAD

**Issue by ahmadeyamin** [livewire/livewire#2215] opened 2020-12-13 14:59 UTC
### Description
When the user uploads the wrong file format it should prevent $photo to get updated and keep it null or previous value so temporaryUrl() should not work.

but when the user uploads the wrong file format it still changes $photo so in frontend temporaryUrl() gets called and shows an error.

validation should work before $photo update but it works after the update so it shows this kind of error :(

![image](https://user-images.githubusercontent.com/29674341/102015378-7f436500-3d85-11eb-96ff-e678e02dbce6.png)
![image](https://user-images.githubusercontent.com/29674341/102015398-9aae7000-3d85-11eb-8815-35704526e5e5.png)

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: [e.g. 2.3]
- Laravel version: [e.g. 8.*]
- Browser: [e.g. Chrome, Safari]

**Comment by mblarsen** [comment] 2020-12-13 16:36
Duplicate of https://github.com/livewire/livewire/issues/1106 — see possible workaround in the comments.

**Comment by IsraH** [comment] 2021-03-08 22:35
Hi, 
go to  livewire.php in config folder of your app,
then add , 'jpg' or another image that can  render on browser at 
'temporary_file_upload' => [
     ...
     'preview_mimes' => [
      ...
      'jpeg', 'jpg', 'mpga', ...
     ...

This solve the issue, this happened to me after upgrade livewire

**Closed** 2021-06-19 17:28 UTC
