### ISSUE TITLE
Weird bug when using @entangle with an array property.

### ISSUE THREAD

**Issue by phuclh** [livewire/livewire#2235] opened 2020-12-18 02:55 UTC
### Description

I have a property contains an array of Trix fields. Whenever user click add button, it will add a Trix input into that array.

This is my trix field (from Surge source code)

```
<div
    class="rounded-md shadow-sm"
    x-data="{
        value: @entangle($attributes->wire('model')),
        isFocused() { return document.activeElement !== this.$refs.trix },
        setValue() { this.$refs.trix.editor.loadHTML(this.value) },
    }"
    x-init="setValue(); $watch('value', () => isFocused() && setValue())"
    x-on:trix-change="value = $event.target.value"
    {{ $attributes->whereDoesntStartWith('wire:model') }}
    wire:ignore
>
    <input id="x" type="hidden">
    <trix-editor x-ref="trix" input="x" class="form-textarea block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5"></trix-editor>
</div>

```

How I use it:
`<x-input.trix wire:model.lazy="followUps.{{ $loop->index }}.body"/>`

The issue is when I press remove, it throws this error:

<img width="596" alt="Screen Shot 2020-12-17 at 6 51 12 PM" src="https://user-images.githubusercontent.com/6707194/102568698-d81e4080-4098-11eb-8bf7-e67ac5b8545a.png">

I noticed that if I use `wire:model.lazy` it will throw that error, but doesn't with `wire:model.defer`. However, if I use `wire:model.defer` and the `body` is empty it will throw the same error unless I type something.

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.19.0
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by joshhanley** [comment] 2020-12-18 03:20
@phuclh yeah there is a bug with how entangle handles arrays.

Have a look at this open PR which fixes the issue #2224.

Hope this helps!

**Comment by ighmouraceneb** [comment] 2020-12-18 08:59
@phuclh 
I have the same problem with trix-editor, and since 3 days I have been blocking on it. Could you have had a solution?

**Comment by joshhanley** [comment] 2020-12-18 19:49
@ighmouraceneb have a look at my comment above there is an open PR which has a solution to the problem, but that's not much help until it gets fixed.

It would be a hack, but maybe you could clear the alpine variable before removing the element from the array, so that way the entangle is no longer active before the element is deleted.

**Comment by ighmouraceneb** [comment] 2020-12-19 18:40
in my case, I generate the inputs automatically. so we can have 0,1,2 ... trix-editor
so in the view I have this

```
@foreach($fields as $index => $field)
   <x-back.input.label for="'{{ $field->field->value }}-{{ $index }}'">{{__($field->config['label'])}}</x-back.input.label>
     <x-back.input.trix-text
                 id="'{{ $field->field->value }}-{{ $index }}'"
                wire:model.defer="textFormattedLongSummary.{{ $index }}"
                :error="$errors->first('textFormattedLongSummary.'.$index)">
     </x-back.input.trix-text>
@endforeach
```



and in the controller I defined as follows:

 ```  public $TextFormattedLongSummary = [];```
in the console I have this error

```
Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at SupportAlpine.js:70
    at Array.forEach (<anonymous>)
    at SupportAlpine.js:55
    at alpine.js:1465
    at Array.forEach (<anonymous>)
    at new Component (alpine.js:1465)
    at Object.initializeComponent (alpine.js:1870)
    at alpine.js:1857
    at alpine.js:1835
```

**Comment by ighmouraceneb** [comment] 2020-12-19 22:28
I init the array in the mount function and it worked : 

```
   public function mount()
    {
        foreach ($this->fields as $index => $field) {
 
            if($field->field->value === "TextFormattedLongSummary") {
                $this->TextFormattedLongSummary[$index] = "";
                $this->bodySummary[$index] = "";
            }
        }
    }
```

**Comment by joshhanley** [comment] 2020-12-22 01:31
The fix for this issue PR #2224 has been merged, and should be available in the next release 🙂

**Comment by phuclh** [comment] 2021-01-11 03:52
@joshhanley I did update to Livewire 2.3.6, but I got another issue with PerformDataBindingUpdates class.

This is my screen recording: https://youtu.be/7GLKY0b-f3k

In the last 10 seconds of the video, I submit the form with an empty follow-up array but it automatically adds an item to the array. Do you have any idea? Looks like the data was synced not correctly with entangle.

**Comment by joshhanley** [comment] 2021-01-12 04:33
@phuclh can you review the data that is being sent from the browser to the server in the network tab of your dev tools and see if it is sending the expected data or not? That way we can tell if it's an entangle issue or a morphdom issue.

Check under Headers tab, request payload > updates

![image](https://user-images.githubusercontent.com/882837/104269859-5da3dd80-54eb-11eb-9f7b-1e4cd69a8ce6.png)

**Comment by phuclh** [comment] 2021-01-12 07:51
@joshhanley It sends expected data until I remove an item from the follow-up array. 

https://youtu.be/hfbUC9l1JNE

When I select an email template, it will fill the subject + body field as normal, but after I removed an item from the array, it didn't fill the data for the body field (which was Trix field that using entangle) but it did fill the subject field (which was text field that NOT using entangle). Therefore, I think the problem is from entangle.

**Comment by joshhanley** [comment] 2021-01-12 23:15
@phuclh ah ok. Any chance you could provide me a repo that replicates the issue? I'll see if I can work out what's happening.

**Comment by phuclh** [comment] 2021-01-12 23:17
@joshhanley Cool. I can port that part into a repo and send it to you. Can I have your email? Thank you!

**Comment by joshhanley** [comment] 2021-01-12 23:19
@phuclh if you can put it into a github repo and share me the link, that would be better, so I can just clone it 🙂  if you'd prefer to keep the code private, just make a private repo and invite me to it.

**Comment by phuclh** [comment] 2021-01-13 08:05
@joshhanley I just invited you to the repo, I also attach a video in Readme. Thank you!

**Comment by joshhanley** [comment] 2021-01-14 01:36
@phuclh ok I have pushed up some fixes to your repo, so please test and let me know how it goes 🙂 I'll also list the issues and the fixes here incase anyone else is interested.

## First issue

First issue I looked at was your follow up emails, which are added dynamically. When you added two of them, removed the second one and the modified the first, the second would re-appear. This is a morphdom issue and was caused by the wire:key not being unique enough.

To fix this, I added an `id` key to your array and generated a `uniqid()` each time a new one was added to the array, so there was a way to track them properly. This is recommended if the elements don't have a unique ID say from a database as a loop index/ loop key isn't unique to the "item/row". And then updated the `wire:key` to use this (see first screenshot).

It is also best practice to wrap a div around a foreach loop to ensure only the stuff inside that div are the generated elements (see second screenshot, not sure why it's highlighting the second close div tag but you get the idea).

**First screenshot**
![image](https://user-images.githubusercontent.com/882837/104532091-9666c280-5663-11eb-80b2-2b46ffe979b4.png)

**Second screenshot**
![image](https://user-images.githubusercontent.com/882837/104532211-d0d05f80-5663-11eb-8d90-6d68805c1d16.png)

## Second issue

The second issue was your initial email template, if you had added some follow up emails and removed them, then tried to change the main email template a couple times, it would also error.

This was caused by your Trix component having a fixed ID, causing multiple inputs on the page to have the same ID causing all sorts of issues.So I have made it unique to the input, by making the ID the Livewire property name you pass into the blade component (see third screenshot).

**Third screenshot**
![image](https://user-images.githubusercontent.com/882837/104532481-6ff55700-5664-11eb-94cd-52ef2e3f40ba.png)

Hope this helps!

**Comment by phuclh** [comment] 2021-01-14 04:05
@joshhanley Wow, thank you so much. You are so great! 👍👍👍👍.

However, there is a notice here:

`$attributes->wire('model')->value }}` doesn't create a unique id in this case because I am using `array_unshift` to push a new item into the top of the array so the id is always `followUps.0.body`.

<img width="1686" alt="Screen_Shot_2021-01-13_at_7_55_20_PM" src="https://user-images.githubusercontent.com/6707194/104543433-44c62580-55da-11eb-8a41-1fd6279884bc.png">

**Comment by joshhanley** [comment] 2021-01-14 04:24
@phuclh good catch! Hmm I guess because now that the wire:key is set, Livewire isn't touching it (which is desired) so you will need to change to something other than `$loop->index`. The best way I can imagine, is instead of using `id` as an element of the array, maybe instead trying to make the `uniqid()` the key for the for each element in your follow ups array like

```php
public function addFollowUp()
{
    if ($this->canAddMoreFollowUp()) {
        $newFollowUp = array(uniqid() => [
            'days'     => 1,
            'template' => '',
            'subject'  => 'Re: ' . $this->subject,
            'body'     => ''
        ]);

        $this->followUps = array_merge(
            $newFollowUp,
            $this->followUps
        );
    }
}
```

In your blade, change your foreach loop to have the ID `@foreach ($followUps as $id => $followUp)`

Change your `wire:key` to `wire:key="{{ $id }}"`

Then replace all of your `{{ $loop->index }}`, inside the followUps foreach loop, with `{{ $id }}`.

**Comment by phuclh** [comment] 2021-01-14 07:09
@joshhanley When I do that, it will throw an error when removing an item in the follow-up array.

```
Uncaught SyntaxError: Invalid or unexpected token
    at Directive.parseOutMethodAndParams (wire-directives.js:93)
    at Directive.get (wire-directives.js:58)
    at node_initializer.js:204
    at Component.value (index.js:564)
    at HTMLButtonElement.<anonymous> (node_initializer.js:196)
```

So I use this one instead: `wire:key="follow-up-form-{{ $i . time() }}"`, and it returns 2 different `wire:key`

<img width="608" alt="Screen Shot 2021-01-13 at 11 02 28 PM" src="https://user-images.githubusercontent.com/6707194/104555861-6c75b780-55f3-11eb-906c-1e4978a7ced3.png">

But I found another issue.

If I add 2 items to the follow-up array without typing anything in Trix field, and then remove them. It works fine!

But if I type something in the Trix field, it automatically adds a weird item to the array, so I have to click 3 times to remove 2 items.

I pushed the new code to the repo. And below is the video.

https://youtu.be/Vh851KGHrSs

**Comment by phuclh** [comment] 2021-01-16 04:51
@joshhanley do you have any idea on why the Trix append weird data into the array?

**Comment by joshhanley** [comment] 2021-01-30 20:34
@phuclh hey sorry just realised I didn't reply to this! Did you manage to get it working? I started looking at it locally and it was just a morphdom issue, which I can help you fix if you haven't already.

Let me know 🙂

**Comment by phuclh** [comment] 2021-01-30 20:45
> @phuclh hey sorry just realised I didn't reply to this! Did you manage to get it working? I started looking at it locally and it was just a morphdom issue, which I can help you fix if you haven't already.
> 
> Let me know 🙂

I haven't fixed it. Thank you

**Comment by joshhanley** [comment] 2021-01-30 22:28
@phuclh I have pushed up a branch called `keyChange`, your key setup in master wasn't working properly, so I made the changes like I would do, to get it working.

I have then also fixed up your trix editor, the watcher you had setup on it was causing issues where it was causing another change to fire when it was getting removed and setting the value to an empty string. But as it was deferred, you weren't noticing that until another request was sent, which was why the second box kept popping back up when you added another one.

Let me know how it goes.

Hope this helps!

**Comment by phuclh** [comment] 2021-02-06 06:26
@joshhanley Thank you so much. It seems to work now, just have a small issue, Trix cannot fill the initial value on the edit page.

**Comment by turboMagneTT** [comment] 2021-02-19 23:41
@joshhanley It seems I have a similar issue and I can't really find the problem right now. 

I have a forelse and for every element I must have 2 datepickers and other text fields that I will omit for now. I'm using pikaday, Laravel blade component and Alpine to make everything work. The solution work when i'm not in a foreach, in fact, I got the problem everytime I send a string with dots to the @entangle blade directive.

The exact error I get is "Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" and the pikaday doesn't work. I guess it just break the JS.

First, my blade loop (my index here is simply an incrementing int) : 
`@foreach ($accidentContributoryAnomalies as $index => $accidentContributoryAnomaly)

            <div wire:key="accidentContributoryAnomalies_{{ $index . time() }}">

                // Some texts fields

                <x-input.group label="Échéancier" for="accidentContributoryAnomalies.{{ $index }}.timelineDate" required>
                    <x-input.date wire:model="accidentContributoryAnomalies.{{ $index }}.timelineDate"
                                  name="accidentContributoryAnomalies.{{ $index }}.timelineDate"
                    />
                </x-input.group>

                <x-input.group label="Date de mise en œuvre" for="accidentContributoryAnomalies.{{ $index }}.implementationDate" required>
                    <x-input.date wire:model="accidentContributoryAnomalies.{{ $index }}.implementationDate"
                                  name="accidentContributoryAnomalies.{{ $index }}.implementationDate"
                    />
                </x-input.group>

            </div>

        @endforeach`

And here is my blade component dor the date : 
`@props([
    'min' => null,
    'max' => null,
])

<div
    x-data="{ value: @entangle($attributes->wire('model')) }"
    x-init="
        new Pikaday({
            field: $refs.datetimeInput,
            format: 'YYYY-MM-DD',
            @if ($min) minDate: new Date('{{ $min }}'), @endif
            @if ($max) maxDate: new Date('{{ $max }}'), @endif
            i18n: {
                previousMonth : 'Mois précédent',
                nextMonth     : 'Mois prochain',
                months        : ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
                weekdays      : ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
                weekdaysShort : ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam']
            }
        });
    "
    x-on:change="value = $event.target.value"
    class="flex input-group"
>

    <div class="input-group-prepend">
        <span class="input-group-text"><i class="fas fa-calendar"></i></span>
    </div>

    <input
        {{ $attributes->whereDoesntStartWith('wire:model') }}
        x-ref="datetimeInput"
        x-bind:value="value"
        type="text"
        placeholder="AAAA-MM-JJ"
        class="form-control"
    />

</div>
`

I tried using 'accidentContributoryAnomalies.0.timelineDate' instead of $attributes->wire('model') in the @entangle directive.

I'm quite stuck, Is the problem on my end?

**Comment by turboMagneTT** [comment] 2021-03-12 16:14
I found an answer to my problem. It is found in an other issue.

[Issue #2611](https://github.com/livewire/livewire/issues/2611)

**Comment by joshhanley** [comment] 2021-03-13 22:17
@phuclh just going back through my notifications, did you ever manage to sort it out?

**Comment by joshhanley** [comment] 2021-03-24 20:37
I'm going to close this for now @phuclh if you are still having issues. Please let me know 🙂 or maybe open a new issue as I think it's different to what this original issue was about.

**Comment by squishythejellyfish** [comment] 2021-03-24 20:37
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Closed** 2021-03-24 20:37 UTC
